KhronosGroup/OpenCL-CTS

.travis.yml
=> Add OSX to the list of Travis CI OSes

test_conformance/clcpp/images/main.cpp, test_conformance/clcpp/synchronization/test_sub_group_barrier.hpp, test_conformance/clcpp/synchronization/test_work_group_barrier.hpp
This should allow #16 to proceed (@kpet).
=> Fix macOS build for 2.2

test_conformance/allocations/allocation_fill.cpp, test_conformance/allocations/allocation_utils.cpp, test_conformance/allocations/allocation_utils.h
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/62
=> cl21: Khronos Bug 15271 allocations test doesn't check if all events on the wait list are valid

test_conformance/allocations/allocation_fill.cpp, test_conformance/allocations/allocation_utils.cpp, test_conformance/allocations/allocation_utils.h
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/62
=> cl22: Khronos Bug 15271 allocations test doesn't check if all events on the wait list are valid

test_conformance/compatibility/test_conformance/api/test_api_min_max.c
Fix Issue https://github.com/KhronosGroup/OpenCL-CTS/issues/82
=> cl22: Khronos Bug 15683 Missing OpenCL 2.1 support in API compatibility tests

test_conformance/images/clCopyImage/main.cpp
=> cl20: Convert images/clCopyImage to testHarness

test_conformance/images/clCopyImage/main.cpp
=> cl21: Convert images/clCopyImage to testHarness

test_conformance/images/clCopyImage/main.cpp
=> cl22: Convert images/clCopyImage to testHarness

test_conformance/images/kernel_read_write/main.cpp
=> cl22: Convert images/kernel_read_write to testHarness

test_conformance/images/kernel_read_write/main.cpp
=> cl20: Convert images/kernel_read_write to testHarness

test_conformance/compatibility/test_conformance/api/test_api_min_max.c, test_conformance/compatibility/test_conformance/basic/test_constant.c
Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/79
=> cl21: Khronos Bug 15347 fix for the same issue in the compatibility tests

test_conformance/compatibility/test_conformance/api/test_api_min_max.c, test_conformance/compatibility/test_conformance/basic/test_constant.c
Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/79
=> cl22: Khronos Bug 15347 fix for the same issue in the compatibility tests

test_conformance/allocations/main.cpp, test_conformance/allocations/testBase.h
=> cl22: Convert allocations to testHarness

test_conformance/allocations/main.cpp, test_conformance/allocations/testBase.h
=> cl21: Convert allocations to testHarness

test_conformance/select/test_select.c
=> cl22: Convert select to testHarness

test_conformance/select/test_select.c
=> cl21: Convert select to testHarness

test_conformance/images/clFillImage/main.cpp
=> cl22: Convert images/clFillImage to testHarness

test_conformance/images/clFillImage/main.cpp
=> cl21: Convert images/clFillImage to testHarness

test_conformance/compatibility/test_common/harness/compat.h, test_conformance/compatibility/test_common/harness/msvc9.c
Fix for issue https://github.com/KhronosGroup/OpenCL-CTS/issues/105
=> cl20: Fix issue 105 - lost fixes for some version of Visual Studio

test_conformance/compatibility/test_common/harness/compat.h, test_conformance/compatibility/test_common/harness/msvc9.c
Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/105
=> cl21: Fix issue 105 - lost fixes for some version of Visual Studio

test_conformance/compatibility/test_common/harness/compat.h, test_conformance/compatibility/test_common/harness/msvc9.c
Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/105
=> cl22: Fix issue 105 - lost fixes for some version of Visual Studio

test_conformance/printf/CMakeLists.txt, test_conformance/printf/test_printf.c
=> cl21: Convert printf to testHarness

test_conformance/printf/CMakeLists.txt, test_conformance/printf/test_printf.c
=> cl22: Convert printf to testHarness

test_conformance/SVM/test_set_kernel_exec_info_svm_ptrs.cpp
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/120
=> cl21: Khronos Bug 15208 test_set_kernel_exec_info_svm_ptrs stack corruption

test_conformance/SVM/test_set_kernel_exec_info_svm_ptrs.cpp
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/120
=> cl22: Khronos Bug 15208 test_set_kernel_exec_info_svm_ptrs stack corruption

test_conformance/SVM/test_migrate.cpp
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/123
=> cl21: Khronos Bug 15617 SVM memory migrate test issues

test_conformance/SVM/test_migrate.cpp
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/123
=> cl22: Khronos Bug 15617 SVM memory migrate test issues

test_common/harness/parseParameters.cpp, test_common/harness/parseParameters.h, test_conformance/conversions/test_conversions.c, test_conformance/half/main.c, test_conformance/math_brute_force/main.c, test_conformance/select/test_select.c
Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/154
=> cl22: Make wimpy factor argument parsing logic common

test_common/harness/testHarness.c, test_common/harness/testHarness.h, test_conformance/compatibility/test_common/harness/testHarness.c, test_conformance/compatibility/test_common/harness/testHarness.h
Add option to save results to JSON file by passing environment variable.
=> cl20: Save results to JSON file

test_common/harness/testHarness.c, test_common/harness/testHarness.h, test_conformance/compatibility/test_common/harness/testHarness.c, test_conformance/compatibility/test_common/harness/testHarness.h
Add option to save results to JSON file by passing environment variable.
=> cl21: Save results to JSON file

test_common/harness/testHarness.c, test_common/harness/testHarness.h, test_conformance/compatibility/test_common/harness/testHarness.c, test_conformance/compatibility/test_common/harness/testHarness.h
Add option to save results to JSON file by passing environment variable.
=> cl22: Save results to JSON file

test_conformance/multiple_device_context/test_multiple_devices.cpp
Cherry-picked from cl21_trunk to reduce diff.
=> Fix bug 16270 by raising device limit

test_conformance/half/cl_utils.c
fix issue: https://github.com/KhronosGroup/OpenCL-CTS/issues/136
=> cl20: Proposed fix for bug 16239

test_conformance/half/cl_utils.c
fix issue: https://github.com/KhronosGroup/OpenCL-CTS/issues/136
=> cl21: Proposed fix for bug 16239

test_conformance/half/cl_utils.c
fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/136
=> cl22: Proposed fix for bug 16239

test_conformance/conversions/test_conversions.c
=> cl20: Reuse test harness code in conversions

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Please see https://github.com/KhronosGroup/OpenCL-CTS/pull/55
=> cl20: Compiler - updated extension list for compiler_defines_for_exensions

test_common/harness/testHarness.c, test_conformance/compatibility/test_common/harness/testHarness.c
* Report an error when unimplemented test was specified
* Merge two common functions
=> cl20: Test Harness minor cleanup

test_common/harness/testHarness.c, test_conformance/compatibility/test_common/harness/testHarness.c
* Report an error when unimplemented test was specified
* Merge two common functions
=> cl21: Test Harness minor cleanup

test_common/harness/testHarness.c, test_conformance/compatibility/test_common/harness/testHarness.c
* Report an error when unimplemented test was specified
* Merge two common functions
=> cl22: Test Harness minor cleanup

test_conformance/allocations/main.cpp
=> cl22: Reuse test harness code in allocations

test_conformance/allocations/main.cpp
=> cl21: Reuse test harness code in allocations

test_conformance/printf/test_printf.c
This patch solves #100 by using a unique file for each test, so that parallel printf tests will not fail.
=> cl20: Use unique tmp file to allow parallel printf tests

test_conformance/CMakeLists.txt
=> cl12: Ignore C++11 narrowing errors for now

test_conformance/contractions/contractions.c
=> cl20: Reuse test harness code in contractions

README.md
=> Update Travis badge to master branch

.travis.yml
=> cl12: Fix Issue 264 - travis builds configuration fixed because of changes in icd loader project

.travis.yml
=> cl20: Fix Issue 264 - travis builds configuration fixed because of changes in icd loader project

.travis.yml
=> master: Fix Issue 264 - travis builds configuration fixed because of changes in icd loader project

.travis.yml
=> cl21: Fix Issue 264 - travis builds configuration fixed because of changes in icd loader project

test_common/autotest/test_suite.hpp
=> Test case registration fix test Issue 278

test_conformance/computeinfo/main.c, test_conformance/conversions/test_conversions.c, test_conformance/d3d10/harness.cpp, test_conformance/d3d10/main.cpp, test_conformance/spir/run_services.cpp
=> Fix Issue #35 - ask for capability size. Too small size could cause errors

test_conformance/computeinfo/main.c, test_conformance/conversions/test_conversions.c, test_conformance/d3d10/harness.cpp, test_conformance/d3d10/main.cpp, test_conformance/spir/run_services.cpp
Fix Issue https://github.com/KhronosGroup/OpenCL-CTS/issues/35
=> cl21: Fix Issue #35 - ask for capability size. Too small size could cause errors

test_conformance/computeinfo/main.c, test_conformance/conversions/test_conversions.c, test_conformance/d3d10/harness.cpp, test_conformance/d3d10/harness.h, test_conformance/d3d10/main.cpp, test_conformance/spir/run_services.cpp
related with https://github.com/KhronosGroup/OpenCL-CTS/pull/36
Fix Issue #35
=> cl20: Fix Issue #35 - ask for capability size. Too small size could cause errors

test_common/harness/compat.h
=> cl20: Intel compiler changes compat.h

test_conformance/SVM/main.cpp
=> cl20: Intel compiler - fix assert when checking OCL version

CMakeLists.txt
=> cl20: Intel compiler changes in cmake

test_conformance/math_brute_force/reference_math.c
=> cl20: Intel compiler bruteforce -  fix signbitl function

test_common/harness/compat.h
=> cl12: Intel compiler changes compat.h

test_conformance/CMakeLists.txt
=> cl12: Intel compiler changes in cmake

test_conformance/math_brute_force/Utility.h
=> cl12: Intel compiler - changes in Utility.h

test_conformance/contractions/CMakeLists.txt, test_conformance/conversions/CMakeLists.txt, test_conformance/geometrics/CMakeLists.txt, test_conformance/math_brute_force/CMakeLists.txt, test_conformance/multiple_device_context/CMakeLists.txt, test_conformance/profiling/CMakeLists.txt, test_conformance/relationals/CMakeLists.txt, test_conformance/select/CMakeLists.txt, test_conformance/spir/CMakeLists.txt, test_conformance/thread_dimensions/CMakeLists.txt, test_conformance/vec_align/CMakeLists.txt, test_conformance/vec_step/CMakeLists.txt
=> cl12: Fix compilation errors using ICC and MSVC - cmakes files

test_conformance/CMakeLists.txt, test_conformance/spir/CMakeLists.txt
=> cl21: Enable compilation of spir 1.2 tests

test_conformance/CMakeLists.txt, test_conformance/spir/CMakeLists.txt
=> cl20: Enable compilation of spir 1.2 tests

test_conformance/CMakeLists.txt, test_conformance/spir/CMakeLists.txt
=> Enable compilation of spir 1.2 tests

test_conformance/geometrics/test_geometrics_double.cpp
=> cl12: Test geometrics - compilation errors using Intel compiler - fix

test_conformance/api/test_queue_hint.cpp
=> Fix test_api - query for device extensions in queue hint test

test_conformance/math_brute_force/reference_math.c, test_conformance/math_brute_force/unary.c, test_conformance/math_brute_force/unary_two_results.c, test_conformance/math_brute_force/unary_two_results_i.c, test_conformance/math_brute_force/unary_u.c
=> cl12: Bruteforce tests - make compatibility to cl20_trunk branch

test_conformance/c11_atomics/test_atomics.cpp
Cast operand type to AddSubOperandType. See #325
=> cl21: fix ambiguous call atomic_fetch_add in c11_atomics

test_common/harness/kernelHelpers.c, test_common/harness/parseParameters.cpp, test_common/harness/parseParameters.h, test_conformance/compiler/test_build_helpers.c
These are preliminary changes to the offline compiler support, intended to simplify later changes that will allow the use of an external script for offline compilation.
=> Preliminary changes to offline compiler support

test_common/harness/kernelHelpers.c, test_common/harness/parseParameters.cpp, test_common/harness/parseParameters.h, test_conformance/build_script_source.py, test_conformance/compiler/test_build_helpers.c, test_conformance/spirv_new/main.cpp
These are preliminary changes to the offline compiler support, intended to simplify later refactoring of this infrastructure.
=> cl21: Preliminary changes to offline compiler support

test_conformance/math_brute_force/main.c
=> Fix spirv path in bruteforce tests

test_conformance/math_brute_force/main.c
=> cl21: Fix spirv path in bruteforce tests

test_conformance/math_brute_force/main.c
=> cl20: Fix spirv path in bruteforce tests

test_conformance/conversions/basic_test_conversions.c
=> cl12: Update conversion test reference functions to use CL_CHAR_MIN for clamping

test_common/harness/kernelHelpers.c
These changes fix refactor the offline compilation code so that it is more maintainable.
=> Refactor offline compilation code

test_common/harness/kernelHelpers.c
These changes fix error handling in create_single_kernel_helper(), and refactor the offline compilation code so that it is more maintainable.
=> Cl21 Refactor offline compilation code

test_conformance/d3d10/harness.h, test_conformance/d3d11/harness.h
=> Fix compilation in D3D cases

test_conformance/d3d10/harness.h, test_conformance/d3d11/harness.h
=> cl21: Fix compilation in D3D cases

test_conformance/d3d10/harness.h, test_conformance/d3d11/harness.h
=> cl20: Fix compilation in D3D cases

CMakeLists.txt, test_extensions/CMakeLists.txt, test_extensions/media_sharing/CMakeLists.txt, test_extensions/media_sharing/main.cpp, test_extensions/media_sharing/procs.h
=> Fix building media sharing tests

CMakeLists.txt, test_extensions/CMakeLists.txt, test_extensions/media_sharing/CMakeLists.txt, test_extensions/media_sharing/main.cpp, test_extensions/media_sharing/procs.h
=> cl21: Fix building media sharing tests

CMakeLists.txt, test_extensions/CMakeLists.txt, test_extensions/media_sharing/CMakeLists.txt, test_extensions/media_sharing/main.cpp, test_extensions/media_sharing/procs.h
=> cl20: Fix building media sharing tests

test_conformance/spirv_new/main.cpp
=> cl21: Fix test spirv_new - define test cache path

CMakeLists.txt, build_win.bat, test_common/harness/kernelHelpers.c, test_common/harness/kernelHelpers.h, test_conformance/CMakeCommon.txt, test_conformance/CMakeLists.txt, test_conformance/opencl_conformance_tests_full_no_math_or_conversions.csv, test_conformance/run_conformance.py
A first round of whitespace, formatting and uncontroversial changes.
=> Reduce diff with master branch

test_conformance/SVM/main.cpp, test_conformance/api/main.c, test_conformance/device_timer/main.c
=> Specify minimum required version for all OpenCL 2.1 tests

test_common/harness/testHarness.h, test_conformance/subgroups/main.cpp
To prepare for merging the cl20_trunk branch.
=> Extend version checks in subgroup test to support all cases

test_conformance/SVM/test_enqueue_api.cpp
=> test clEnqueueSVMMemcpy in case of host memory allocation

test_conformance/SVM/test_fine_grain_memory_consistency.cpp, test_conformance/SVM/test_fine_grain_sync_buffers.cpp
Signed-off-by: Georgios Pinitas <georgios.pinitas@arm.com>
=> Add missing event release calls in SVM tests

test_conformance/SVM/common.h, test_conformance/SVM/main.cpp, test_conformance/SVM/test_fine_grain_memory_consistency.cpp
=> Fix verification if atomics 64bit extensions supported by device

test_conformance/images/kernel_read_write/test_write_1D.cpp, test_conformance/images/kernel_read_write/test_write_1D_array.cpp, test_conformance/images/kernel_read_write/test_write_2D_array.cpp, test_conformance/images/kernel_read_write/test_write_3D.cpp, test_conformance/images/kernel_read_write/test_write_image.cpp
Cherry-pick of PR-445 to cl12_trunk
=> cl12 Remove re-declarations of totalErrors variable (#27)

test_conformance/images/image_helpers.cpp
Cherry-pick of PR-443 for cl12_trunk
=> cl12 Missing break overwrites special float generation (346)

test_conformance/math_brute_force/macro_unary.c
PR-444 cherry-pick for cl12_trunk
=> cl12 Fix incoming errors overwritten by exit block (#249)

test_conformance/SVM/test_enqueue_api.cpp
=> Fix Issue 462 - test_svm crash

test_conformance/api/test_queries.cpp, test_conformance/images/clGetInfo/test_2D.cpp
=> Fix a couple of typos

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
=> Fixes #486 - add build option for devices OCL2.X

CMakeLists.txt, test_conformance/d3d10/CMakeLists.txt, test_conformance/d3d11/CMakeLists.txt, test_extensions/CMakeLists.txt, test_extensions/media_sharing/CMakeLists.txt
=> Fixes #488 - cmake adjustment d3d and media_sharing

test_conformance/mem_host_flags/checker_image_mem_host_no_access.hpp, test_conformance/mem_host_flags/checker_mem_host_read_only.hpp, test_conformance/mem_host_flags/checker_mem_host_write_only.hpp
- Add missing error checks
- Add missing return
- Fix flag check
=> A few error handling and flag test fixes for mem_host_flags

test_common/harness/testHarness.c
Use clCreateCommandQueue before OpenCL 2.0.
This enables most of the binaries to run to completion on a
1.2 implementation.
=> harness: select queue creation function based on OpenCL version

test_conformance/basic/main.c, test_conformance/basic/test_sizeof.c
=> Fixes issue #499 - Test basic from master branch on OCL 1.2 device

test_common/gl/gl_headers.h, test_common/gl/setup_win32.cpp, test_conformance/CMakeLists.txt, test_conformance/gl/CMakeLists.txt
=> cl12: GL sharing: Fix WIN compilation and add some clarification.

test_common/harness/kernelHelpers.c
=> Fixes Issue #514 - Offline compilation does not work. Null device reported

test_conformance/math_brute_force/main.c
=> Fixes issue #502 - bruteforce do not need build option

test_conformance/integer_ops/main.c
=> Fixes issue #502 - Integer ops ctz case add test version 2.X

test_conformance/images/kernel_image_methods/main.cpp, test_conformance/images/kernel_image_methods/test_1D.cpp, test_conformance/images/kernel_image_methods/test_1D_array.cpp, test_conformance/images/kernel_image_methods/test_2D.cpp, test_conformance/images/kernel_image_methods/test_2D_array.cpp, test_conformance/images/kernel_image_methods/test_3D.cpp, test_conformance/images/kernel_image_methods/test_loops.cpp, test_conformance/images/kernel_read_write/main.cpp, test_conformance/images/kernel_read_write/test_iterations.cpp, test_conformance/images/kernel_read_write/test_loops.cpp, test_conformance/images/kernel_read_write/test_read_1D.cpp, test_conformance/images/kernel_read_write/test_read_1D_array.cpp, test_conformance/images/kernel_read_write/test_read_2D_array.cpp, test_conformance/images/kernel_read_write/test_read_3D.cpp, test_conformance/images/kernel_read_write/test_write_1D.cpp, test_conformance/images/kernel_read_write/test_write_1D_array.cpp, test_conformance/images/kernel_read_write/test_write_2D_array.cpp, test_conformance/images/kernel_read_write/test_write_3D.cpp, test_conformance/images/kernel_read_write/test_write_image.cpp, test_conformance/images/samplerlessReads/main.cpp, test_conformance/images/samplerlessReads/test_iterations.cpp, test_conformance/images/samplerlessReads/test_loops.cpp, test_conformance/images/samplerlessReads/test_read_1D.cpp, test_conformance/images/samplerlessReads/test_read_1D_array.cpp, test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp, test_conformance/images/samplerlessReads/test_read_2D_array.cpp, test_conformance/images/samplerlessReads/test_read_3D.cpp
=> Fixes issue #497 - Image tests from master branch on OCL 1.2 device

test_conformance/printf/util_printf.c
=> Test printf - Use stdlib implementation. Do not redefine

test_conformance/SVM/test_enqueue_api.cpp
=> test_svm - enqueue_api - lack of synchronization points

CMakeLists.txt
=> Remove redundant variable in CMakeLists.txt

test_conformance/gl/main.cpp
=> Remove gDeviceType definition

CMakeLists.txt, test_conformance/events/test_userevents.cpp
=> Remove some dead code

test_conformance/thread_dimensions/test_thread_dimensions.c
* function get_maximums sets variables with maximum
image width and height but those values are not used
in the entire test
=> Remove unused variables from thread_dimensions test

test_conformance/SVM/main.cpp, test_conformance/api/test_create_context_from_type.cpp, test_conformance/api/test_kernels.c, test_conformance/api/test_queue_properties.cpp, test_conformance/basic/test_enqueue_map.cpp, test_conformance/compiler/test_build_helpers.c, test_conformance/generic_address_space/main.cpp, test_conformance/images/clFillImage/test_fill_generic.cpp, test_conformance/profiling/execute.c, test_conformance/profiling/execute_multipass.c, test_conformance/subgroups/main.cpp
Fix error reporting in clFillImage as a result.
=> Fix warnings reported by -Wconversion-null

test_common/harness/testHarness.cpp
=> Fix - Windows build errors - utsname sysctl files

test_conformance/images/kernel_read_write/CMakeLists.txt, test_conformance/images/kernel_read_write/test_common.cpp, test_conformance/images/kernel_read_write/test_common.h, test_conformance/images/kernel_read_write/test_iterations.cpp, test_conformance/images/kernel_read_write/test_read_1D.cpp, test_conformance/images/kernel_read_write/test_read_1D_array.cpp, test_conformance/images/kernel_read_write/test_read_2D_array.cpp, test_conformance/images/kernel_read_write/test_read_3D.cpp
=> Make it possible to run kernel_read_write on a 1.x implementation

test_common/harness/testHarness.cpp, test_common/harness/testHarness.h, test_conformance/images/clFillImage/main.cpp, test_conformance/images/clGetInfo/main.cpp, test_conformance/images/clReadWriteImage/main.cpp, test_conformance/images/kernel_image_methods/main.cpp, test_conformance/images/kernel_read_write/main.cpp, test_conformance/images/samplerlessReads/main.cpp
This is now done in the test harness.
=> Get rid of checkDeviceTypeOverride

test_conformance/printf/test_printf.cpp
Fixes KhronosGroup/OpenCL-CTS#492
=> Use format string for sprintf

test_common/harness/alloc.h, test_common/harness/imageHelpers.cpp, test_common/harness/kernelHelpers.cpp, test_common/harness/kernelHelpers.h, test_common/harness/mt19937.cpp
Also use it instead of duplicating the code.
Fixes #326
=> Remove duplicate definition of align_{malloc,free}

test_common/harness/os_helpers.cpp
Fixes KhronosGroup/OpenCL-CTS#493
=> Fix sterror_r usage for Android API >=23

test_common/harness/errorHelpers.h, test_common/harness/testHarness.cpp, test_conformance/allocations/allocation_functions.cpp, test_conformance/allocations/main.cpp, test_conformance/basic/test_fpmath_float.cpp, test_conformance/basic/test_fpmath_float2.cpp, test_conformance/basic/test_fpmath_float4.cpp, test_conformance/basic/test_queue_priority.cpp, test_conformance/events/test_userevents.cpp, test_conformance/gl/main.cpp, test_conformance/gl/test_fence_sync.cpp, test_conformance/gles/main.cpp, test_conformance/half/main.cpp, test_conformance/images/kernel_image_methods/main.cpp, test_conformance/images/kernel_read_write/main.cpp, test_conformance/math_brute_force/Utility.h, test_conformance/math_brute_force/main.cpp, test_conformance/printf/test_printf.cpp, test_conformance/printf/test_printf.h, test_conformance/select/test_select.cpp, test_conformance/select/test_select.h, test_conformance/select/util_select.cpp, test_conformance/vec_step/test_step.cpp
=> Get rid of test_finish macro and related ATF cruft

test_conformance/images/clCopyImage/main.cpp, test_conformance/images/clFillImage/main.cpp, test_conformance/images/clGetInfo/main.cpp, test_conformance/images/clReadWriteImage/main.cpp, test_conformance/images/kernel_image_methods/main.cpp, test_conformance/images/kernel_read_write/main.cpp, test_conformance/images/samplerlessReads/main.cpp
This is handled in testHarness.cpp
Fixes #652
=> Test images - remove setting gDeviceType.

test_conformance/gl/test_images_write_common.cpp
=> Test GL: Add pragma cl_khr_3d_image_writes

test_conformance/gl/test_images_read_common.cpp, test_conformance/gl/test_images_write_common.cpp
=> Test GL: Make it possible run test_gl on device OpenCL 1.2

test_conformance/SVM/test_pointer_passing.cpp
=> Test SVM: Fix - do not use unmapped pointer.

test_conformance/c11_atomics/main.cpp, test_conformance/compiler/main.cpp, test_conformance/generic_address_space/main.cpp, test_conformance/non_uniform_work_group/main.cpp, test_conformance/workgroups/main.cpp
=> Set minimum expected OpenCL version for the test.

test_conformance/SVM/main.cpp, test_conformance/device_execution/main.cpp, test_conformance/pipes/main.cpp, test_conformance/subgroups/main.cpp
=> Fix test skip handling while test initialization

test_conformance/basic/test_progvar.cpp
This adds checks to progvar_prog_scope_uninit which ensure that
program-scope variables are default-initialized to the zero-value for
their type.
=> Fixes #498 - Extend progvar_prog_scope_uninit checks

test_common/harness/imageHelpers.cpp
=> Fix image required format - sRGB

test_conformance/conversions/test_conversions.cpp, test_conformance/images/kernel_read_write/main.cpp, test_conformance/math_brute_force/main.cpp
All tests that have this code are using the harness which does
this already.
=> Remove duplicate code setting _cpu_capabilities

test_conformance/c11_atomics/main.cpp, test_conformance/generic_address_space/main.cpp, test_conformance/non_uniform_work_group/main.cpp
=> Fix - add TEST_PASS test status in group of tests

test_conformance/thread_dimensions/test_thread_dimensions.cpp
Replaced a kernel used for memseting a large buffer with clEnqueueFillBuffer.
Fixes #692. Addresses #684.
=> Thread Dimensions: Improve execution time.

test_common/gl/setup_win32.cpp
=> Fix typo device -> devices

test_common/harness/kernelHelpers.cpp, test_common/harness/kernelHelpers.h, test_conformance/SVM/main.cpp, test_conformance/atomics/test_atomics.cpp, test_conformance/basic/test_sizeof.cpp, test_conformance/clcpp/workitems/test_workitems.hpp, test_conformance/compiler/test_compiler_defines_for_extensions.cpp
They are duplicate functions
Fixes #709
=> Replace get_device_version with get_cl_device_version

.clang-format
This addresses comments from recent PR reviews.
=> clang-format: indent continued lines

test_conformance/compiler/test_build_helpers.cpp
See the usage of this array [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/e72cff3e7d4af0127c69db7b105bf200faac37cb/test_conformance/compiler/test_build_helpers.cpp#L157).
=> Fix buffer overflow in compiler suite

test_conformance/d3d11/harness.cpp
=> is_extension_available - extension not found in case of space in string pattern

.appveyor.yml
Changes in appveyor configuration file to be able build d3d10 and d3d11 tests.
=> Turn on d3d binaries - Windows

test_conformance/api/test_kernels.cpp
=> Fix initialization of input data for api test

test_conformance/api/test_kernels.cpp
The test was also invalid, since it was testing that you can pass a
structure containing cl_mem objects to a kernel without SVM.
=> Remove unused API test

test_conformance/multiple_device_context/test_multiple_contexts.cpp, test_conformance/multiple_device_context/test_multiple_devices.cpp
Fixes a signed integer overflow issue caught by UBSan.
=> Use unsigned integers in multiple_device_context

test_conformance/api/test_kernels.cpp
Also remove one unused test function.
=> Replace magic constants in api/kernels tests

test_conformance/basic/test_arrayimagecopy.cpp, test_conformance/basic/test_arrayimagecopy3d.cpp
=> Mem-leaks from conformance test_basic

test_conformance/subgroups/main.cpp, test_conformance/subgroups/procs.h, test_conformance/subgroups/subhelpers.h, test_conformance/subgroups/test_barrier.cpp, test_conformance/subgroups/test_queries.cpp, test_conformance/subgroups/test_workgroup.cpp, test_conformance/subgroups/test_workitem.cpp
Before fixes in my previous PRs I need to format this test suit according to .clang-format
=> Format subgroups tests according to clang-format

test_conformance/api/test_api_min_max.cpp
* Correct khronos extension device version checks so that 2.0, 2.1 and
2.2 extensions are only require for devices versions < 3.0
(`cl_khr_3d_image_writes`, `cl_khr_image2d_from_buffer` and
`cl_khr_depth_images` are all optional for devices supporting
OpenCL-3.0).
* Remove `cl_khr_fp64` from list or required extensions for 2.0,
`cl_khr_fp64` is a required extension for OpenCL-1.2 devices if they
suport doubles. Check for support of `cl_khr_fp64` on 1.2 devices.
* Remove duplicated `cl_khr_byte_addressable_store` from list of 2.0
extensions. Since this is a 1.1 extension and all versions greater than
1.1 are backwards compatible with 1.1 this will be checked anyway.
=> Correct khr Extension Checks for Device Versions

test_conformance/mem_host_flags/checker.h, test_conformance/mem_host_flags/checker_image_mem_host_no_access.hpp, test_conformance/mem_host_flags/checker_image_mem_host_read_only.hpp, test_conformance/mem_host_flags/checker_image_mem_host_write_only.hpp, test_conformance/mem_host_flags/checker_mem_host_read_only.hpp, test_conformance/mem_host_flags/checker_mem_host_write_only.hpp, test_conformance/mem_host_flags/mem_host_buffer.cpp
Fix various resource leaks in the tests for mem_host_flags.
=> Mem-leaks from conformance mem_host_flags

test_conformance/subgroups/CMakeLists.txt, test_conformance/subgroups/main.cpp, test_conformance/subgroups/procs.h, test_conformance/subgroups/subhelpers.h, test_conformance/subgroups/test_barrier.cpp, test_conformance/subgroups/test_ifp.cpp, test_conformance/subgroups/test_queries.cpp, test_conformance/subgroups/test_workgroup.cpp, test_conformance/subgroups/test_workitem.cpp
=> Fix test_subgroups - test as core feature.

test_conformance/math_brute_force/reference_math.cpp
=> Test bruteforce - fix islessgreater function for intel compiler

test_conformance/events/test_userevents_multithreaded.cpp
Also fixes a thread leak reported by TSan.
=> Use std::thread for userevents_multithreaded test

test_conformance/math_brute_force/binaryOperator.cpp
=> Fix relaxed mode in math bruteforce - binaryOperator

.travis.yml, test_conformance/gl/test_fence_sync.cpp, test_conformance/gl/test_image_methods.cpp, travis.sh
Add building test_gl binaries on Ubuntu - reopen #803
=> Turn on building test_gl in travis

test_conformance/profiling/copy.cpp, test_conformance/profiling/execute.cpp, test_conformance/profiling/readArray.cpp, test_conformance/profiling/readImage.cpp, test_conformance/profiling/writeArray.cpp, test_conformance/profiling/writeImage.cpp
Code uses outdated API calls
Fixes #715
Change-Id: I575c8ec4003fd30a3cec28ad114d5749f2e83d0f
=> Remove code under USE_LOCAL_THREADS

test_common/harness/kernelHelpers.cpp, test_common/harness/testHarness.cpp, test_common/harness/testHarness.h, test_conformance/SVM/main.cpp, test_conformance/c11_atomics/main.cpp, test_conformance/conversions/test_conversions.cpp, test_conformance/device_execution/main.cpp, test_conformance/device_timer/main.cpp, test_conformance/generic_address_space/main.cpp, test_conformance/math_brute_force/main.cpp, test_conformance/non_uniform_work_group/main.cpp, test_conformance/pipes/main.cpp, test_conformance/printf/test_printf.cpp, test_conformance/spirv_new/main.cpp, test_conformance/spirv_new/test_linkage.cpp, test_conformance/spirv_new/test_op_opaque.cpp, test_conformance/workgroups/main.cpp
=> SPIR-V handling on different OpenCL devices version

test_conformance/events/test_userevents.cpp
Spotted some missing releases in this test.
=> Release some dangling objects in userevents.

test_conformance/conversions/CMakeLists.txt, test_conformance/conversions/fplib.cpp
Tested with currently supported Android NDK r21d.
=> Fix 32-bit Android build for ARMv7

test_conformance/basic/test_enqueued_local_size.cpp
* `test_enqueued_local_size` will be skipped for OpenCL < 2.0. However,
non-uniform work-groups became optional in 3.0 and so check that they
are supported before running `test_enqueued_local_size` and otherwise
skip.
=> Skip test_enqueued_local_size if non-uniform work-groups not supported

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Signed-off-by: Einar Hov <einar.hov@arm.com>
=> Add cl_khr_device_uuid as approved extension

test_conformance/api/CMakeLists.txt, test_conformance/api/main.cpp, test_conformance/api/procs.h, test_conformance/api/test_mem_object_properties_queries.cpp
=> Test against clCreateBufferWithProperties and clCreateImageWithProperties OpenCL 3.0 API

test_conformance/select/test_select.cpp
=> Simplify call to create_single_kernel_helper() in test_select

test_conformance/basic/test_rw_image_access_qualifier.cpp
* Skip `rw_image_access_qualifier` if images are not supported.
* Skip `rw_image_access_qualifier` if read-write images are optionally
not supported on a OpenCL-3.0 or later device.
* Stop assuming `-cl-std=CL3.0` and default to latest OpenCL C supported
by the device.
=> Update `rw_image_access_qualifier` for OpenCL-3.0

test_common/harness/clImageHelper.h, test_common/harness/typeWrappers.cpp, test_conformance/integer_ops/verification_and_generation_functions.cpp
=> Remove empty statements due to use of double semicolons

test_common/harness/deviceInfo.cpp, test_common/harness/deviceInfo.h, test_common/harness/kernelHelpers.cpp
=> Print the latest conformance version passed reported by the device

test_conformance/c11_atomics/common.h
The generator function for atomic_fence uses the current workgroup
size to determine the number of non atomic variables per thread
in the kernel. The kernel should hence be regenerated when the
workgroup size changes.
However regenerating the kernel can itself change the workgroup
size. This change introduces an iterative loop that reduces the
workgroup sizes by 2 each time re-generating the kernel until
we find one that works (or exit at groupsize == 1)
Change-Id: Ic32fe967e32de6643e01c6775f4bddbcad0a299a
=> c11_atomics: Fix to iteratively reduce workgroup size  (#939)

test_conformance/submission_details_template.txt
=> A first set of updates to the submission template

test_common/harness/errorHelpers.h, test_conformance/compiler/CMakeLists.txt, test_conformance/compiler/main.cpp, test_conformance/compiler/procs.h, test_conformance/compiler/test_feature_macro.cpp
=> Test feature macro OpenCL 3.0

test_common/harness/conversions.cpp
=> Fix compilation failure with -Werror=narrowing

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Changes related with extended subgroups.
=> Add new subgroup extensions to the compiler test

test_conformance/spirv_new/main.cpp, test_conformance/spirv_new/procs.h
=> Fix min version for SPIRV test registration.

test_conformance/api/test_zero_sized_enqueue.cpp
=> [api][test_zero_sized_enqueue] Add CL_SUBMITTED check for waiting status

test_common/harness/errorHelpers.cpp, test_conformance/events/test_event_dependencies.cpp, test_conformance/images/samplerlessReads/main.cpp
=> Fix a few typos and remove unused code

test_conformance/c11_atomics/common.h
=> c11_atomics - change arg type to unsigned int from signed int

CMakeLists.txt, test_common/gles/gl_headers.h, test_common/gles/helpers.cpp, test_conformance/gles/CMakeLists.txt, test_conformance/gles/main.cpp, test_conformance/gles/setup_egl.cpp, test_conformance/gles/test_fence_sync.cpp
For 32 and 64-bit Visual Studio and the Android Q NDK.
=> gles: Fix compile errors.

test_conformance/api/test_kernel_private_memory_size.cpp
=> Implement test for CL_KERNEL_PRIVATE_MEM_SIZE

test_conformance/half/Test_vLoadHalf.cpp
OpenCL-C code must respect aliasing rules as in C99.
Therefore, accessing data from multiple pointer sizes
must all point to character type to keep strict aliasing
rules. If not, when the compiler performs optimization,
the dataflow was broken leading to failure.
We also fix the formatting and refactor few things.
=> Fix aliasing issue for test_half (#45)

test_conformance/math_brute_force/Utility.h, test_conformance/math_brute_force/binary.cpp, test_conformance/math_brute_force/binaryOperator.cpp, test_conformance/math_brute_force/binary_i.cpp, test_conformance/math_brute_force/binary_two_results_i.cpp, test_conformance/math_brute_force/i_unary.cpp, test_conformance/math_brute_force/macro_binary.cpp, test_conformance/math_brute_force/macro_unary.cpp, test_conformance/math_brute_force/mad.cpp, test_conformance/math_brute_force/ternary.cpp, test_conformance/math_brute_force/unary.cpp, test_conformance/math_brute_force/unary_two_results.cpp, test_conformance/math_brute_force/unary_two_results_i.cpp, test_conformance/math_brute_force/unary_u.cpp
This change was present on the GitLab branch but missed out during the transition to GitHub.
This change is intentionally as close as possible to the patch on GitLab.
Fixes #1045
=> Restored the embedded reduction factor to bruteforce.

test_conformance/api/test_queries.cpp
=> Test api fix - sampler properties is 0 in compatibility mode

test_conformance/CMakeLists.txt
=> Install generate_spirv_offline.py script

test_common/harness/imageHelpers.cpp
=> Minor fixes for CL_ARGB channel order.

test_conformance/SVM/test_fine_grain_memory_consistency.cpp, test_conformance/SVM/test_fine_grain_sync_buffers.cpp, test_conformance/device_execution/enqueue_ndrange.cpp
I've found more tests that requires this change as was introduced in #1031
=> Change arg type to unsigned int from signed int

test_conformance/math_brute_force/main.cpp
See https://github.com/KhronosGroup/OpenCL-CTS/pull/1127#issuecomment-770778474 and commit message for further details.
=> Fix command line interface for math_brute_force

test_conformance/api/test_api_min_max.cpp
The current test would always end up assuming a minimum of 16 KB
regardless of the exposed OpenCL version, and the logic for testing the
OpenCL version was hard to follow.
Besides fixing the test for OpenCL 1.1 through 2.1, it also
* adds support for OpenCL 2.2, 3.0, and future OpenCL versions (as long
as `get_device_cl_version()` supports those);
* adapts the error message to mention the currently exposed OpenCL
version rather than a hardcoded OpenCL 1.1;
* reports the advertised local memory size as KB and not Kb, since local
memory size is given in bytes.
=> api: Fix testing of local memory size requirement

test_conformance/buffers/test_buffer_fill.cpp, test_conformance/buffers/test_buffer_write.cpp, test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Fix vairous memory leaks in test_buffer and test_compiler.
=> Fix Minor memory leaks in test_buffer/compiler.

test_conformance/buffers/test_buffer_map.cpp, test_conformance/buffers/test_buffer_read.cpp
This change fixes buffer tests, broken by PR #1082. This pull request is similar to #1160.
=> Fix buffer tests memory leaks

test_conformance/math_brute_force/binary_double.cpp, test_conformance/math_brute_force/binary_float.cpp, test_conformance/math_brute_force/binary_i_double.cpp, test_conformance/math_brute_force/binary_i_float.cpp, test_conformance/math_brute_force/binary_operator_double.cpp, test_conformance/math_brute_force/binary_operator_float.cpp, test_conformance/math_brute_force/binary_two_results_i_double.cpp, test_conformance/math_brute_force/binary_two_results_i_float.cpp, test_conformance/math_brute_force/i_unary_double.cpp, test_conformance/math_brute_force/i_unary_float.cpp, test_conformance/math_brute_force/macro_binary_double.cpp, test_conformance/math_brute_force/macro_binary_float.cpp, test_conformance/math_brute_force/macro_unary_double.cpp, test_conformance/math_brute_force/macro_unary_float.cpp, test_conformance/math_brute_force/mad_double.cpp, test_conformance/math_brute_force/mad_float.cpp, test_conformance/math_brute_force/main.cpp, test_conformance/math_brute_force/reference_math.cpp, test_conformance/math_brute_force/ternary_double.cpp, test_conformance/math_brute_force/ternary_float.cpp, test_conformance/math_brute_force/unary_double.cpp, test_conformance/math_brute_force/unary_float.cpp, test_conformance/math_brute_force/unary_two_results_double.cpp, test_conformance/math_brute_force/unary_two_results_float.cpp, test_conformance/math_brute_force/unary_two_results_i_double.cpp, test_conformance/math_brute_force/unary_two_results_i_float.cpp, test_conformance/math_brute_force/unary_u_double.cpp, test_conformance/math_brute_force/unary_u_float.cpp, test_conformance/math_brute_force/utility.h
Prefer C++ headers and remove some unnecessary includes.
=> Use C++ headers instead of C headers

test_conformance/gles/test_fence_sync.cpp
fix #1170 ,out of boundary when strcpy
=> fix out of boundary when strcpy

test_conformance/conversions/fplib.cpp
=> Fix conversion fail when build with -O2 fail

test_conformance/buffers/test_buffer_fill.cpp
=> Fix test_buffer - undefined behavior in case of CL_MEM_USE_HOST_PTR

test_common/harness/fpcontrol.h
Needed for the `int64_t` and `uint64_t` in this file.
=> Add missing cstdint include

test_conformance/api/test_context_destructor_callback.cpp, test_conformance/gl/test_buffers.cpp, test_conformance/gl/test_fence_sync.cpp
=> Fix double release of object in test_api and test_gl

test_conformance/half/Test_vLoadHalf.cpp
See #1002.
Tagging @AlexeySachkov.
=> remove testing for scalar vloada_half

CMakeLists.txt
=> Remove unused definitions in CMakeLists.txt

test_common/harness/integer_ops_test_info.h
Fixes a build issue on one of our platforms introduced by #1276.
=> Add missing include for gRandomSeed

test_common/harness/deviceInfo.cpp, test_common/harness/deviceInfo.h, test_conformance/integer_ops/test_integer_dot_product.cpp
Signed-off-by: Marco Cattani <marco.cattani@arm.com>
=> Update cl_khr_integer_dot_product tests for v2

test_conformance/subgroups/test_subgroup_non_uniform_arithmetic.cpp
=> Remove unused inclusion of <cstdio>

test_conformance/api/negative_platform.cpp
=> Remove invalid negative_get_platform_info testcase

test_conformance/basic/test_vector_swizzle.cpp, test_conformance/buffers/test_buffer_fill.cpp, test_conformance/buffers/test_buffer_read.cpp, test_conformance/vectors/test_step.cpp
Fixed memory leaks in: buffers, basic, and vectors
=> Fix memory leaks

test_conformance/pipes/test_pipe_info.cpp
The test now checks that CL_KERNEL_ARG_INFO_NOT_AVAILABLE is returned when calling clGetKernelArgInfo() with offline compilation modes.
The correct function name is printed if clGetKernelArgInfo() fails when using online compilation (and not "clSetKernelArgInfo()").
When using online compilation, if the actual arg type is not as expected, the actual arg type is now logged, and the return value is now TEST_FAIL (-1) as per other failures (and not 1).
All other test pass/fail values used in the test now use TEST_PASS and TEST_FAIL instead of 0 and -1 literals.
An unnecessary cast of pipe_kernel_code has been removed.
=> Improve testing of kernel arg info in pipe_info test

test_conformance/subgroups/subhelpers.h
This will simplify subsequent changes to test::run() in cases where multiple run-and-check sequences are needed for the testing of a single kernel.
=> Refactor kernel execution in subgroup tests

test_conformance/subgroups/subhelpers.h
This will be used for the testing of cl_khr_subgroup_clustered_reduce.
=> Add cluster size handling in subgroup test helpers

test_conformance/subgroups/test_subgroup_clustered_reduce.cpp
=> Test all cluster sizes for cl_khr_subgroup_clustered_reduce

test_conformance/api/test_kernel_arg_info.cpp
Code taken from api/test_min_image_formats.cpp
=> api/kernel_arg_info: Check for read_write image support before testing

test_conformance/images/kernel_read_write/test_iterations.cpp, test_conformance/images/kernel_read_write/test_read_1D.cpp, test_conformance/images/kernel_read_write/test_read_1D_array.cpp, test_conformance/images/kernel_read_write/test_read_2D_array.cpp, test_conformance/images/kernel_read_write/test_read_3D.cpp, test_conformance/images/kernel_read_write/test_write_1D.cpp, test_conformance/images/kernel_read_write/test_write_1D_array.cpp, test_conformance/images/kernel_read_write/test_write_2D_array.cpp, test_conformance/images/kernel_read_write/test_write_3D.cpp, test_conformance/images/kernel_read_write/test_write_image.cpp
=> Enable mipmap extension pragmas

test_conformance/subgroups/CMakeLists.txt, test_conformance/subgroups/main.cpp, test_conformance/subgroups/procs.h, test_conformance/subgroups/subgroup_common_templates.h, test_conformance/subgroups/subhelpers.h, test_conformance/subgroups/test_subgroup_rotate.cpp
=> Add tests for cl_khr_subgroup_rotate

test_conformance/subgroups/subgroup_common_templates.h, test_conformance/subgroups/subhelpers.h, test_conformance/subgroups/test_queries.cpp, test_conformance/subgroups/test_subgroup_ballot.cpp
Add missing newlines and improve wording of messages.
=> Tidy up subgroup log messages

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
=> Add missing external memory/sync extensions to list of known khr extensions

CMakeLists.txt, test_conformance/basic/test_arraycopy.cpp, test_conformance/basic/test_multireadimageonefmt.cpp, test_conformance/basic/test_writeimage_fp32.cpp, test_conformance/basic/test_writeimage_int16.cpp, test_conformance/commonfns/test_sign.cpp, test_conformance/commonfns/test_step.cpp, test_conformance/events/test_callbacks.cpp, test_conformance/half/Test_vStoreHalf.cpp, test_conformance/images/clReadWriteImage/test_read_1D.cpp, test_conformance/multiple_device_context/test_multiple_devices.cpp, test_conformance/profiling/execute.cpp, test_conformance/profiling/writeImage.cpp
=> Fix misleading indentation and enable -Wmisleading-indentation

test_conformance/events/test_waitlists.cpp
=> fix indentation of test_waitlists.cpp

test_conformance/subgroups/subgroup_common_templates.h, test_conformance/subgroups/subhelpers.h, test_conformance/subgroups/test_barrier.cpp, test_conformance/subgroups/test_subgroup.cpp, test_conformance/subgroups/test_subgroup_ballot.cpp, test_conformance/subgroups/test_subgroup_clustered_reduce.cpp
=> Remove unused variables in subgroup tests

test_conformance/run_conformance.py
Fix whitespace issues and remove superfluous parens in the run_conformance.py script.  This addresses 288 out of the 415 issues reported by pylint.
=> [NFC] Fix whitespace issues in run_conformance.py

test_conformance/run_conformance.py
Use the print function from futures for Python 3 compatibility, remove an unreachable statement, remove unused imports, and add a missing sys.exit call when opening the log file fails.
=> Minor cleanups for run_conformance.py

test_conformance/events/action_classes.cpp, test_conformance/events/action_classes.h, test_conformance/events/main.cpp, test_conformance/events/procs.h, test_conformance/events/testBase.h, test_conformance/events/test_callbacks.cpp, test_conformance/events/test_event_dependencies.cpp, test_conformance/events/test_events.cpp, test_conformance/events/test_userevents.cpp, test_conformance/events/test_userevents_multithreaded.cpp, test_conformance/events/test_waitlists.cpp
=> [NFC] Reformat code in events test

test_conformance/events/test_callbacks.cpp
=> [NFC] Fix typo (enevt_type -> event_type)

test_conformance/atomics/main.cpp, test_conformance/atomics/procs.h, test_conformance/atomics/testBase.h, test_conformance/atomics/test_atomics.cpp, test_conformance/atomics/test_indexed_cases.cpp
Add some clang-format off/on comments to keep lists and kernel code readable.
=> [NFC] clang-format test_atomics

test_conformance/pipes/test_pipe_read_write.cpp, test_conformance/pipes/test_pipe_subgroups.cpp
=> pipes: Fix typos in skip messages

test_conformance/basic/test_sizeof.cpp
=> Use CTS type wrappers for  test_sizeof.

test_conformance/basic/test_enqueued_local_size.cpp
=> Use CTS type wrappers for test_enqueued_local_size

test_conformance/basic/test_progvar.cpp, test_conformance/c11_atomics/test_atomics.cpp, test_conformance/conversions/test_conversions.cpp, test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
Fix a few instances where an incorrect number of arguments was supplied when calling (v)log_error.
=> Fix -Wformat-extra-args warnings

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Add missing newlines, and log all unknown extensions instead of logging only the first unknown extension found.
=> Improve logging of unknown extensions

test_conformance/basic/test_readimage.cpp
=> Fix image type on format check for test_readimage.

test_conformance/generic_address_space/advanced_tests.cpp
Conformance tests should not assume support for OpenCL 2.0, or specific features. This patch removes uses of
`__opencl_c_program_scope_global_variables` for devices which do not support it in the generic address space conformance tests. Additionally, the `clCompileProgram` options have been updated to select between `CL2.0` and `CL3.0` depending on which the device under test supports.
=> Fix generic address space OpenCL 2.0 assumption

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Replace repetitions of extensions_supported[num_of_supported_extensions] with a single pointer variable.
Replace character-by-character comparisons with a new string_has_prefix function.
=> Partial clean up of test_compiler_defines_for_extensions

test_conformance/mem_host_flags/checker_image_mem_host_write_only.hpp
Unblocks https://github.com/KhronosGroup/OpenCL-CTS/pull/1599
=> [NFC] clang-format mem_host_flags/checker_image_mem_host_write_only.hpp

test_conformance/mem_host_flags/C_host_memory_block.h, test_conformance/mem_host_flags/checker.h, test_conformance/mem_host_flags/checker_image_mem_host_no_access.hpp, test_conformance/mem_host_flags/checker_image_mem_host_read_only.hpp, test_conformance/mem_host_flags/checker_mem_host_no_access.hpp, test_conformance/mem_host_flags/checker_mem_host_read_only.hpp, test_conformance/mem_host_flags/checker_mem_host_write_only.hpp, test_conformance/mem_host_flags/main.cpp, test_conformance/mem_host_flags/mem_host_buffer.cpp, test_conformance/mem_host_flags/procs.h, test_conformance/mem_host_flags/testBase.h
clang-format all of mem_host_flags in advance of some more warning fixes that I plan to push.
=> [NFC] clang-format mem_host_flags

test_conformance/gl/common.h, test_conformance/gl/helpers.cpp, test_conformance/gl/main.cpp, test_conformance/gl/procs.h, test_conformance/gl/testBase.h, test_conformance/gl/test_fence_sync.cpp, test_conformance/gl/test_image_methods.cpp, test_conformance/gl/test_images_1D.cpp, test_conformance/gl/test_images_1Darray.cpp, test_conformance/gl/test_images_2D.cpp, test_conformance/gl/test_images_2Darray.cpp, test_conformance/gl/test_images_3D.cpp, test_conformance/gl/test_images_depth.cpp, test_conformance/gl/test_images_getinfo_common.cpp, test_conformance/gl/test_images_multisample.cpp, test_conformance/gl/test_images_read_common.cpp, test_conformance/gl/test_images_write_common.cpp, test_conformance/gl/test_renderbuffer.cpp, test_conformance/gl/test_renderbuffer_info.cpp
Add some clang-format off/on comments to keep kernel code readable.
Unblocks #1610
=> [NFC] clang-format gl

test_common/harness/imageHelpers.cpp, test_conformance/images/kernel_read_write/test_common.cpp
This change attempts to shorten the time it takes to run the image streams test, primarily through vectorization of the `read_image_pixel_float()` and `sample_image_pixel_float()` functions, where the most time is spent. With this, I was able to reduce the time the test takes from 45 minutes to 37 minutes.
Unfortunately, most of the time in the test is spent waiting for memory fetches, particularly in the 3D case, where the image does not fit neatly into the cache, especially with linear sampling, where pixels from two 2D slices must be sampled. Randomized offsets are likely a factor, because they throw off the hardware prefetcher. Software prefetching won't help, because that only moves around the long waits for memory; experimentally, this actually totally negates the performance …
=> Image streams optimization

test_conformance/basic/procs.h, test_conformance/conversions/basic_test_conversions.cpp, test_conformance/conversions/basic_test_conversions.h, test_conformance/conversions/test_conversions.cpp, test_conformance/math_brute_force/utility.h, test_conformance/relationals/test_comparisons_float.cpp
Those are provided by testHarness.h.
=> [NFC] Remove duplicate symbol declarations

test_conformance/events/test_event_dependencies.cpp
=> fixing test events

test_conformance/math_brute_force/common.cpp
When generating the kernel code, consider the return type(s) and the types of all parameters, instead of only the first parameter type. This fixes a missing extension pragma for certain cases (such as `nan`).
=> math_brute_force: consider all types for extension pragmas

test_conformance/basic/CMakeLists.txt, test_conformance/basic/test_int2float.cpp
=> Deduplicate test_basic int2float/float2int

test_conformance/extensions/cl_khr_command_buffer/command_buffer_get_command_buffer_info.cpp
Added check for state CL_COMMAND_BUFFER_STATE_EXECUTABLE_KHR in state info tests.
=> Add check for CL_COMMAND_BUFFER_STATE_EXECUTABLE_KHR after completion.

test_conformance/basic/test_hiloeo.cpp
=> Added cl_khr_fp16 extension support for test_hiloeo from basic

test_conformance/basic/test_astype.cpp, test_conformance/basic/utils.h
=> Added cl_khr_fp16 extension support for test_astype from basic

test_conformance/basic/test_async_copy2D.cpp, test_conformance/basic/test_async_copy3D.cpp
The latest version of the cl_khr_extended_async_copies extension uses element size rather the element type as its base. The means it can be called with arbitrary and in particular non power of 2 sizes, such as 3 or 13.
Update the test_async_copy2D and test_async_copy3D tests to make them element size based rather than type based.
As well as this run all tests that can fit into the memory of the target rather than presumed large elements cannot fit.
Make some addtional good practice changes in terms of const usage, declaring variables where they are use, and usage of iterators.
The test coverage increases from 1224 cases to 1332 cases for the test_async_copy2D and test_async_copy3D cases.
Ticket: #1579
Signed-off-by: Chris Gearing <chris.gearing@mobileye.com>
=> Make extended_async_copy tests type agnostic

test_conformance/basic/test_async_copy.cpp
=> Added cl_khr_fp16 extension support for test_async_copy from basic

test_conformance/basic/test_vec_type_hint.cpp
=> Added cl_khr_fp16 extension support for test_vec_type_hint from basic

test_conformance/spirv_new/spirv_asm/op_neg_half.spvasm32, test_conformance/spirv_new/spirv_asm/op_neg_half.spvasm64, test_conformance/spirv_new/test_op_negate.cpp, test_conformance/spirv_new/types.hpp
According to issue request #142
=> Added cl_khr_fp16 extension support for test_op_negate from spirv_new

test_conformance/device_execution/enqueue_block.cpp
Modernize by using raw string literals, which makes the kernel sources easier to read/extract.
=> [NFC] device_execution: use raw string literals for block kernels

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
https://github.com/KhronosGroup/OpenCL-CTS/issues/1424#issuecomment-1554680436
=> add  cl_khr_expect_assume to test_compiler_defines_for_extensions

test_conformance/basic/test_image_r8.cpp
=> Use the CTS type wrappers in image_r8

test_conformance/basic/test_constant.cpp
Change-Id: I8181badb4c0b91db65c504a00e4578e033e4d6a7
=> Use CTS type wrappers for test_constant.

test_conformance/images/kernel_read_write/test_cl_ext_image_from_buffer.cpp
Inverted the comparisons as we expect the alignments reported from the 
extension query to always be greater or equal to what is reported from 
the device in pixels through 
CL_DEVICE_IMAGE_PITCH_ALIGNMENT/CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT.
=> Image2d_from_buffer_positive comparison fix

test_conformance/thread_dimensions/main.cpp, test_conformance/thread_dimensions/procs.h, test_conformance/thread_dimensions/test_thread_dimensions.cpp
Proposal: tuning parameters to run thread dimensions tests. 
Sometimes such limiting is useful especially in more extensive tests running on low power/performance platforms.
=> Enhancement: Thread dimensions user parameters

test_conformance/api/test_sub_group_dispatch.cpp
A couple of small subgroup-related fixes.
=> Subgroup test fixes

test_common/harness/testHarness.cpp
enable the CTS to run on custom devices
=> add support for custom devices

test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/CMakeLists.txt, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/main.cpp, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_basic.h, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_full_dispatch.cpp, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/procs.h
According to #1481 issue description, point 2.1
=> Added command buffer test with all mutable parameters dispatch

test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/CMakeLists.txt, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/main.cpp, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_basic.h, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_simultaneous.cpp, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/procs.h
-cross queue simultaneous use
-in-order queue with simultaneous use
According to issue description #1481
=> Added new tests for simultaneous use with mutable dispatch

test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/CMakeLists.txt, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/main.cpp, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_multiple_dispatches.cpp, test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/procs.h
According to issue description #1481, point 2.1.1 (a)
=> Added new test to cover multiple commands dispatch in one enqueued update

test_conformance/extensions/cl_khr_command_buffer/CMakeLists.txt, test_conformance/extensions/cl_khr_command_buffer/main.cpp, test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_get_info.cpp, test_conformance/extensions/cl_khr_command_buffer/procs.h
According to description #1668
=> Added negative tests for clGetCommandBufferInfoKHR

test_conformance/api/CMakeLists.txt, test_conformance/api/main.cpp, test_conformance/api/procs.h, test_conformance/api/test_wg_suggested_local_work_size.cpp, test_conformance/workgroups/CMakeLists.txt, test_conformance/workgroups/main.cpp, test_conformance/workgroups/procs.h
=> fix: move suggested_local_size to test_api

test_conformance/spirv_new/spirv_asm/expect_bool.spvasm32, test_conformance/spirv_new/spirv_asm/expect_bool.spvasm64, test_conformance/spirv_new/test_cl_khr_expect_assume.cpp
Adds a missing test case for OpExpectKHR with boolean sources.
=> add testing for OpExpectKHR with boolean sources

test_conformance/basic/test_if.cpp
Signed-off-by: John Kesapides [john.kesapides@arm.com](mailto:john.kesapides@arm.com)
=> Use CTS type wrappers for test_basic test_if.

test_conformance/basic/test_imagedim.cpp
=> Deduplicate test_imagedim

test_conformance/printf/util_printf.cpp
according to work plan for issue https://github.com/KhronosGroup/OpenCL-CTS/issues/1058
=> Extended printf test to support more vector cases

test_conformance/conversions/basic_test_conversions.cpp
The handling of NaN values in the templated function was incorrect due to improper initialization of the input data source. Specifically, the function ZeroNanToIntCases used a global pointer gIn, which was not correctly set or did not point to the same data as the local input pointer s used in the non-templated implementation.
to solve the issue I updated the templated function ZeroNanToIntCases to take an additional parameter for the input data source.
and then passed the correct input data (s) to the templated function during its invocation.
=> conversions: fix ZeroNanToIntCases from https://github.com/KhronosGroup/OpenCL-CTS/pull/1975

test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
1. Fix memory leak by making `context2` use the context wrapper.
2. Create two separate events to associate with the two calls to `clEnqueueSignalSemaphoresKHR()`, as events cannot be reused.
Also delete the unused helper function
`semaphore_external_cross_queue_helper()` (which was a duplicate of `external_semaphore_cross_queue_helper()` anyway).
=> Fix issues in `test_external_semaphores_cross_queues_io2`

test_conformance/basic/test_global_linear_id.cpp
=> Use CTS type wrappers for test_global_linear_id.

test_conformance/atomics/test_atomics.cpp
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1793 according to description
=> Added unique_ptrs and MTdataHolder to test_atomics.cpp

test_conformance/profiling/copy.cpp, test_conformance/profiling/execute.cpp, test_conformance/profiling/execute_multipass.cpp, test_conformance/profiling/main.cpp, test_conformance/profiling/procs.h, test_conformance/profiling/profiling_timebase.cpp, test_conformance/profiling/readArray.cpp, test_conformance/profiling/readImage.cpp, test_conformance/profiling/writeArray.cpp, test_conformance/profiling/writeImage.cpp
=> [NFC] Migrate profiling suite to new registration framework

test_conformance/allocations/main.cpp
=> Migrate allocations suite to the new test registration framework

test_conformance/select/test_select.cpp
=> Migrate the select suite to the new test registration framework

test_conformance/gl/test_images_getinfo_common.cpp, test_conformance/gl/test_images_read_common.cpp, test_conformance/gl/test_renderbuffer.cpp
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1982 according to description
=> Removed checking for supporting half

test_conformance/profiling/readArray.cpp, test_conformance/profiling/writeArray.cpp
These tests are broken, have been disabled for the longest time, and don't add significant value.
=> Delete read_array_half and write_array_half tests

.gitignore
Introduce a `.gitignore` file to the repository matching a build folder `[Bb]uild/` pattern.
=> [NFC] Add .gitignore file

test_conformance/printf/test_printf.cpp
=> Migrate printf suite to the new test registration framework

test_conformance/c11_atomics/main.cpp, test_conformance/c11_atomics/test_atomics.cpp
=> Migrate c11_atomics suite the new test registration framework

test_conformance/computeinfo/conforming_version.cpp, test_conformance/computeinfo/device_uuid.cpp, test_conformance/computeinfo/extended_versioning.cpp, test_conformance/computeinfo/main.cpp, test_conformance/computeinfo/pci_bus_info.cpp
=> Migrate computeinfo suite to the new test registration framework

test_conformance/contractions/contractions.cpp
=> Migrate contractions suite to the new test registration framework

test_conformance/half/Test_roundTrip.cpp, test_conformance/half/Test_vLoadHalf.cpp, test_conformance/half/Test_vStoreHalf.cpp, test_conformance/half/main.cpp
=> Migrate half suite to the new test registration framework

test_conformance/generic_address_space/advanced_tests.cpp, test_conformance/generic_address_space/atomic_tests.cpp, test_conformance/generic_address_space/basic_tests.cpp, test_conformance/generic_address_space/main.cpp, test_conformance/generic_address_space/stress_tests.cpp
Contributes to https://github.com/KhronosGroup/OpenCL-CTS/issues/2181.
=> Migrate generic_address_space suite to the new test registration framework

test_conformance/conversions/test_conversions.cpp
=> Migrate conversions suite to the new test registration framework

test_conformance/images/clCopyImage/main.cpp, test_conformance/images/clFillImage/main.cpp, test_conformance/images/clGetInfo/main.cpp, test_conformance/images/clReadWriteImage/main.cpp, test_conformance/images/kernel_image_methods/main.cpp, test_conformance/images/kernel_read_write/main.cpp, test_conformance/images/samplerlessReads/main.cpp
=> Migrate images suite to the new test registration framework

test_conformance/allocations/main.cpp
Make the number of work-items proportional to size of the allocation so we launch more work-items and do less work per work-item as buffer sizes go up with device capabilities. 
To test:
test_allocations multiple 5 buffer
test_allocations single 5 buffer
=> allocations: Scale number of work-items in relation to input size

test_conformance/basic/CMakeLists.txt, test_conformance/basic/test_arraycopy.cpp, test_conformance/basic/test_arrayimagecopy.cpp, test_conformance/basic/test_hostptr.cpp, test_conformance/basic/test_if.cpp, test_conformance/basic/test_image_multipass.cpp, test_conformance/basic/test_imagearraycopy.cpp, test_conformance/basic/test_imagecopy.cpp, test_conformance/basic/test_imagecopy3d.cpp, test_conformance/basic/test_imagenpot.cpp, test_conformance/basic/test_imagerandomcopy.cpp, test_conformance/basic/test_imagereadwrite.cpp, test_conformance/basic/test_imagereadwrite3d.cpp, test_conformance/basic/test_kernel_call_kernel_function.cpp, test_conformance/basic/test_multireadimagemultifmt.cpp, test_conformance/basic/test_multireadimageonefmt.cpp
=> Enable -Wnarrowing for the basic test suite
