- test_conformance/math_brute_force/reference_math.cpp
-Wabsolute-value warning reported as error (long double truncated to
double)
Fixes #1303
> Fix build error for linux with clang-8

- test_conformance/conversions/basic_test_conversions.cpp
Use volatile to prevent clang optimizations, fix int2float
> Use volatile qualifier to prevent optimizations

- test_conformance/subgroups/subgroup_common_templates.h
Test cases where the index/mask/delta is greater than or equal to the
maximum subgroup size.  These are cases that return undefined results
but are not undefined behavior.
The index/mask/delta values now include values less than twice the
subgroup size, and 0xffffffff.
Testing for sub_group_shuffle_xor() already allowed inputs that were
greater or equal to the subgroup size for the last subgroup in a
workgroup, but did not properly account for this in the verification
function, potentially resulting in out of bounds accesses.
> Improve cl_khr_subgroup_shuffle* test coverage

- test_conformance/api/test_api_min_max.cpp
In some rare cases where get_global_id() is larger than 2G, the 32bit int type would convert the value into a negative integer.
> test_api_min_max.cpp: use size_t for get_global_id() value

- test_conformance/subgroups/test_subgroup_ballot.cpp
As per the OpenCL Extension Specification § 38.6 Ballots:
If no bits representing predicate values from all work items in
the subgroup are set in the bitfield value then the return value
is undefined.
The case with no bits set is still worth testing, as it does not result
in undefined behavior, but only an undefined return value.
> Fix sub_group_ballot_find_msb/lsb tests

- CMakeLists.txt
- test_common/harness/imageHelpers.cpp
- test_common/harness/imageHelpers.h
Lossy casts due to inexact float representation of CL_INT_MAX
Fixes #1250
Fixed #855
> Fix clang 10 build errors

- test_common/harness/imageHelpers.cpp
Working on a device supporting CL_UNORM_SHORT_565 image data type, I
noticed that the max absolute error authorized was not the right one
for such image data type.
Also because of normalization, there is always an absolute error
authorized whatever the filtering of the sampler.
Ref #1140
> imageHelpers: add CL_UNORM_SHORT_{555, 565} in get_max_absolute_error

- test_conformance/c11_atomics/common.h
memory_order_acq_rel with memory_scope_device is now used to guarantee that the correct memory consistency is observed before final results are stored.
Previously it was possible for kernels to be generated that all used relaxed memory ordering, which could lead to false-positive failures.
Fixes #1370
> Change memory order and scope for atomics that gate final results being stored.

- test_conformance/images/kernel_read_write/test_common.cpp
- test_conformance/images/kernel_read_write/test_iterations.cpp
- test_conformance/images/kernel_read_write/test_loops.cpp
- test_conformance/images/kernel_read_write/test_read_1D.cpp
- test_conformance/images/kernel_read_write/test_read_1D_array.cpp
- test_conformance/images/kernel_read_write/test_read_2D_array.cpp
If the device type also advertises CL_DEVICE_TYPE_DEFAULT (which should
be valid), this causes it to be considered a CPU device and the tests
enforce different precision and rounding expectations.
> images: Stop checking gDeviceType != CL_DEVICE_TYPE_GPU

- test_conformance/images/clCopyImage/test_copy_generic.cpp
The slice pitch/padding calculation assumed that the 'height' variable contained the pixel height of the image, which it doesn't for IMAGE1D_ARRAY.
Fixes #1257
> Fixes incorrect slice pitch calculation in clCopyImage 1Darray

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
GCC 11.2.0 warns about a possible string overflow (when
num_not_supported_extensions+num_of_supported_extensions == 0)
since no space would be allocated for the terminating
null byte that string manipulation fns expect to find.
This unconditionally adds an extra byte to the allocation to silence
the warning and fix building with -Werror.
> test_compiler_defines_for_extensions: fix overflow

- test_conformance/c11_atomics/common.h
Description copied from #1285 :
In the error condition, the atomic_fence kernel can illegally access local memory addresses.
In this snippet, localValues is in the local address space and provided as a kernel argument. Its size is effectively get_local_size(0) * sizeof(int). The stores to localValues lead to OoB accesses.
```
size_t myId = get_local_id(0);
...
if(hisAtomicValue != hisValue)
{ // fail
atomic_store(&destMemory[myId], myValue-1);
hisId = (hisId+get_local_size(0)-1)%get_local_size(0);
if(myValue+1 < 1)
localValues[myId*1+myValue+1] = hisId;
if(myValue+2 < 1)
localValues[myId*1+myValue+2] = hisAtomicValue;
if(myValue+3 < 1)
localValues[myId*1+myValue+3] = hisValue;
}
```
> Fix local memory out of bounds issue in atomic_fence (replaces PR #1285)

- test_conformance/half/Test_vStoreHalf.cpp
(#1298) Workitems in the last workgroup calls async_work_group_copy with
different argument values depending on 'adjust'. According to spec,
this results in undefined values.
> Fix test_half async_work_group_copy arguments (#1298)

- test_conformance/basic/test_async_copy2D.cpp
- test_conformance/basic/test_async_copy3D.cpp
Update the 2D and 3D extended async copies tests. Previously they were based on
an older provisional version of the extension.
Also update the variable names to only use 'stride' to refer to the actual
stride values. Previously the tests used 'stride' to refer to the end of one
line or plane and the start of the next. This is not the commonly understood
meaning.
> Update cl_khr_extended_async_copies tests to the latest extension version

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/main.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Simplify code by avoiding manual resource management.
This allows removing `clReleaseProgram` from `MakeKernels` to reduce
behavioral differences between `MakeKernels` and `MakeKernel`.
> Use clProgramWrapper in math_brute_force

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Move the main `BuildKernelInfo` definition into `common.h` to reduce
code duplication.
Some tests (e.g. `i_unary_double.cpp`) use a different struct; rename
those structs to `BuildKernelInfo2` for now to avoid ambiguity.
> Share BuildKernelInfo struct definition

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Remove the `offset` field from both structures, because it was always
set to the global `gMinVectorSizeIndex`.
Improve documentation and rename some variables:
- `i` becomes `vectorSize`;
- `kernel_count` becomes `threadCount`.
> Tidy up BuildKernelInfo

- test_conformance/select/test_select.cpp
When verification of the computed result fails, the test would still
report as "passed".  This is because `s_test_fail` is only written to
and never read.
Fix the immediate issue by returning a failure value and incrementing
`gFailCount` if any error was detected.  The error handling can be
improved further, but I'm leaving that out of the scope of this fix.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1445
> Fix test_select verification failure reporting

- test_conformance/math_brute_force/reference_math.cpp
Fixes a missing-field-initializers warning.  The original intent was
most likely to initialize both fields (similar to other functions in
this file), but a `,` was missed.
> [NFC] Fix missing `double_double.lo` initializer

- test_conformance/math_brute_force/main.cpp
This will enable compiling math_brute_force with `-Wall`, for which I'll create a followup patch.
> [NFC] Fix sign-compare warnings in math_brute_force

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
Simplify code by avoiding manual resource management.
This commit only modifies tests that use one queue per thread.  The
other unmodified tests are single-threaded and use the global
`gQueue`.
> Use clCommandQueueWrapper in math_brute_force

- test_conformance/math_brute_force/main.cpp
Commit 9666ca3c ("[NFC] Fix sign-compare warnings in math_brute_force
(#1467)", 2022-08-23) inadvertently changed the semantics of the if
condition.  The `i > gEndTestNumber` comparison was relying on
`gEndTestNumber` being promoted to unsigned.  When casting `i` to
`int32_t`, this promotion no longer happens and as a result any tests
given on the command line were being skipped.
Use an unsigned type for `gStartTestNumber` and `gEndTestNumber` to
eliminate the casts and any implicit conversions between signed and
unsigned types.
> Fix test skipping in math_brute_force

- test_conformance/extensions/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_base.h
- test_conformance/extensions/cl_khr_command_buffer/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/procs.h
Introduce some basic testing of the [cl_khr_command_buffer](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_command_buffer) provisional extension. This code is intended as a starting point from which we can iteratively build up tests for the extension.
> Initial command-buffer extension tests

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
Simplify code by avoiding manual resource management.
This is a continuation of #1463 .
> Use clMemWrapper in math_brute_force

- test_conformance/api/test_kernel_attributes.cpp
test_error returns the err given as the first argument. As the
run_test function returns a bool, we end up returning true (meaning
pass) when an api function fails.
Instead return explicitly false (meaning fail).
> fix test kernel attributes when api fcts are failing

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Add [cl_khr_command_buffer_mutable_dispatch](https://github.com/KhronosGroup/OpenCL-Docs/pull/819) and [cl_khr_extended_async_copies](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_extended_async_copies) to the list of known extensions used in `test_compiler_defines_for_extensions`
> Update known extensions in compiler define test

- test_conformance/c11_atomics/common.h
- test_conformance/c11_atomics/test_atomics.cpp
Having 1 non atomic variable per thread on the c11 atomic fence test would sometimes make it so that one of the threads of the pair that is trying to synchronise will read the memory written by another thread not part of this pair causing a failure.
More info: https://github.com/KhronosGroup/OpenCL-CTS/issues/1274.
> Minimum 2 non atomic variables per thread for the c11 atomic fence test for embedded profile devices.

- test_conformance/basic/test_progvar.cpp
The condition inside the assert is dropped in Release builds, so `num_printed` becomes unused.
> [NFC] Fix unused variable warning in Release builds

- test_conformance/SVM/test_shared_address_space_fine_grain.cpp
Memory is allocated for cl_int,
but mapped as size_t.
Use size_t instead of cl_int during
allocation and mapping for consistency
Fixes OpenCL-CTS #1421
> Use correct size for memory allocation in SVM test

- test_conformance/gl/common.h
- test_conformance/gl/test_images_getinfo_common.cpp
- test_conformance/gl/test_images_read_common.cpp
- test_conformance/gl/test_images_write_common.cpp
Without `const`, these variables would be flagged up by `-Wunused-variable`.
Preserve constness across functions that use these variables.
> [NFC] Declare format tables as const

- test_conformance/gles/main.cpp
Fix unused-variable errors by limiting variable definition to the case that would use it
> gles: Limit variable definition to the same scope as usage

- .github/workflows/presubmit.yml
- presubmit.sh
The "Ninja" CMake generator does not support multiple configurations, i.e. it does not support use of the '--config' option when running 'cmake --build'.  As such, the default configuration (i.e. Debug) was getting used for all builds.
Use the CMAKE_BUILD_TYPE variable instead, so that we do release builds, but change one build (ubuntu-20.04 aarch64) to use Debug as its build type, to keep some build coverage for asserts, etc.
For Vulkan-Loader and OpenCL-ICD-Loader, we do release builds unconditionally, as we assume there is no need in the CI workflow to actually run the binaries that are built, and therefore no need for any additional debug info.
> Include release builds in GitHub Actions

- test_conformance/math_brute_force/main.cpp
- test_conformance/math_brute_force/reference_math.cpp
This should unblock #1477 
* Fix "‘nadj’ may be used uninitialized in this function [-Werror=maybe-uninitialized]".
* Fix "specified bound 4096 equals destination size [-Werror=stringop-truncation]".
> Fix more warnings in math_brute_force

- test_common/harness/mt19937.h
- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/main.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
Improve the design of the MTdataHolder wrapper:
* Make it a class instead of a struct with a private member, to clarify that there is no direct access to the MTdata member.
* Make the 1-arg constructor `explicit` to avoid unintended conversions.
* Forbid copy construction/assignment as MTdataHolder is never initialised from an MTdataHolder object in the codebase.
* Define move construction/assignment as per the "rule of five".
Use the MTdataHolder class throughout math_brute_force, to simplify code by avoiding manual resource management.
> Improve MTdataHolder design and use it in math_brute_force

- test_conformance/half/main.cpp
Allocate memory for argc arguments
instead of argc - 1.
> Fix memory oob problem in test half

- test_conformance/math_brute_force/CMakeLists.txt
math_brute_force compiles cleanly with `-Wall` currently, so avoid
regressing from that state.  Ideally we would enable `-Wall` in the
top-level CMakeLists.txt, but other tests do not compile cleanly with
`-Wall` yet.
> [NFC] Enable -Wall for math_brute_force

- CMakeLists.txt
- test_conformance/images/kernel_read_write/CMakeLists.txt
- test_conformance/math_brute_force/CMakeLists.txt
Factor out a macro to set module-specific compilation flags for GNU-like compilers.  This simplifies setting compilation flags per test.
> cmake: Add set_gnulike_module_compile_flags

- test_conformance/contractions/contractions.cpp
- test_conformance/conversions/test_conversions.cpp
- test_conformance/half/main.cpp
- test_conformance/math_brute_force/main.cpp
- test_conformance/printf/test_printf.cpp
- test_conformance/select/test_select.cpp
These macros make the build non-deterministic.
> Remove __DATE__ and __TIME__ usage.

- test_conformance/SVM/test_cross_buffer_pointers.cpp
- test_conformance/SVM/test_shared_sub_buffers.cpp
9ad48998 generally made memory allocation and mapping consistent with a size of size_t. Apply that fix to the final two allocations.
> SVM: Fix memory allocation size.

- test_conformance/subgroups/subhelpers.h
Fix a `-Wsign-compare` warning in the `run()` function, which resulted in many repeated warnings when compiling with `-Wall` due to the many template instantiations.
Both `clGetKernelSubGroupInfo` queries return a `size_t`, so it is unclear why the results of these queries were being cast to `int`.
The `dynsc` uses don't seem to work with negative values, so make the field unsigned.
> [NFC] Avoid mixing signed and unsigned in subhelpers run

- test_conformance/atomics/test_indexed_cases.cpp
The "succeed" variables are never read and they don't seem to serve any purpose that's not already provided by the "fail" variables.
In `add_index_bin_test` the "fail" variable is also set but unused, but that may require an actual fix, so leaving that out of this commit.
> [NFC] atomics: Remove set-but-unused "succeed" variables

- test_conformance/math_brute_force/CMakeLists.txt
- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/main.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
* Printing of 64-bit types, which is now done using the `PRI*64` macros from <cinttypes> to ensure portability across 32 and 64-bit builds.
* Printing of `size_t` types that lacked a `z` length modifier.
* Printing of values with a `z` length modifier that weren't a `size_t` type.
Code reformatting has been split out into a separate commit for ease of reviewing.
> math_brute_force: Fix -Wformat warnings

- test_conformance/atomics/test_atomics.cpp
* Printing of `i` which is a `size_t` requiring the `%zu` specifier.
* Printing of `cl_long` which is now done using the `PRId64` macro to ensure portability across 32 and 64-bit builds.
> atomics: Fix -Wformat warnings

- test_conformance/vulkan/vulkan_interop_common/vulkan_list_map.hpp
- test_conformance/vulkan/vulkan_interop_common/vulkan_utility.cpp
- test_conformance/vulkan/vulkan_interop_common/vulkan_wrapper.cpp
This is an alternative proposal to fix 32-bit compiles, see #1465.
This version removes the implicit conversion to a pointer and relies on an explicit conversion instead, by overloading `operator()`.  Note that this is a similar pattern used by the OpenCL C++ bindings:
https://github.com/KhronosGroup/OpenCL-CLHPP/blob/main/include/CL/opencl.hpp#L1913
By removing the implicit conversion there is only one overload for both 32-bit and 64-bit builds.
> remove implicit conversion to pointer to fix 32-bit compile

- test_conformance/math_brute_force/CMakeLists.txt
- test_conformance/math_brute_force/common.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
Use a common function to create the kernel source code for testing 3-argument math builtins.  This reduces code duplication.  1-argument and 2-argument math kernel construction will be factored out in a future PR.
Change the kernels to use preprocessor defines for argument types and undef values, to make the CTS code easier to read.
Co-authored-by: Marco Antognini <marco.antognini@arm.com>
> math_brute_force: Factor out GetTernaryKernel

- test_conformance/images/kernel_read_write/test_cl_ext_image_from_buffer.cpp
This test is failing in case when extensions `cl_ext_image_requirements_info` is not supported and `cl_khr_image2d_from_buffer` is supported. In function `get_image_requirement_alignment` there is macro run `GET_EXTENSION_FUNC` with function `clGetImageRequirementsInfoEXT`. Then test should check if extension `cl_ext_image_requirements_info` is supported
> Fix image test image2d_from_buffer_positive

- test_conformance/pipes/test_pipe_read_write.cpp
Use the appropriate function for verifying double precision values in the `pipe_readwrite_double` test.
There doesn't seem to be a significant functional difference between `verify_readwrite_double` and `verify_readwrite_long` as both functions use 64-bit integer data types.
Found by compiling with `-Wunused-function`, which flagged `verify_readwrite_double` as unused.
> pipes: Fix readwrite verification function for fp64

- test_conformance/basic/test_progvar.cpp
Manually reformat the `prog_src` variable which contains kernel code and disable clang-format on it as it doesn't handle embedded kernel code nicely.
> [NFC] clang-format basic/test_progvar.cpp

- test_common/harness/conversions.cpp
- test_common/harness/imageHelpers.cpp
- test_common/harness/propertyHelpers.cpp
- test_common/harness/testHarness.cpp
* Printing of a `size_t` which requires the `%zu` specifier.
* Printing of `cl_long`/`cl_ulong` which is now done using the `PRI*64` macros to ensure portability across 32 and 64-bit builds.
> harness: Fix -Wformat warnings

- CMakeLists.txt
- test_conformance/CMakeLists.txt
Allow enabling/disabling building of the Vulkan interop tests via CMake option without modifying the CMake. This matches the optionality of the D3D10, D3D11, GL, and GLES interop tests.
> Make building the Vulkan interop tests optional

- test_conformance/vulkan/test_vulkan_interop_image.cpp
- test_conformance/vulkan/vulkan_interop_common/vulkan_list_map.cpp
- test_conformance/vulkan/vulkan_interop_common/vulkan_wrapper.cpp
Thich change allow build tests on Windows and Intel compiler:
error : namespace "std" has no member "max"
> Fix vulkan test build issue on Intel compiler

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/common.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Use common functions to create the kernel source code for testing 1-argument and 2-argument math builtins.  This reduces code duplication.
Use appropriate patterns to initialise variables to their full bit widths.  For example, `0xdead` was previously used to initialise 32-bit integers, while now a larger number spanning all bytes is used.
Co-authored-by: Marco Antognini <marco.antognini@arm.com>
> math_brute_force: Factor out GetUnaryKernel and GetBinaryKernel

- test_conformance/images/kernel_read_write/test_cl_ext_image_from_buffer.cpp
- test_conformance/images/kernel_read_write/test_cl_ext_image_requirements_info.cpp
Also use log_info instead of printf for skipped tests, for consistency.
> Add missing newlines in log messages for image tests

- test_common/harness/ThreadPool.cpp
While testing an OpenCL driver with ThreadSanitizer enabled the OpenCL-CTS suffers from thread leaks in conversions and bruteforce on posix systems. This is because `pthread_join` is never called in `ThreadPool_Exit` for the `pthread_t`s created by the thread pool. Instead, the threads are only informed to stop waiting on the condition variable which unblocks the worker thread but does not clean up after itself.
```
ThreadPool: thread 1 exiting.
ThreadPool: thread 5 exiting.
ThreadPool: thread 4 exiting.
ThreadPool: thread 2 exiting.
ThreadPool: thread 7 exiting.
ThreadPool: thread 0 exiting.
ThreadPool: thread 3 exiting.
ThreadPool: thread 6 exiting.
Thread pool exited in a orderly fashion.
==================
WARNING: ThreadSanitizer: thread leak (pid=2292842)
Thread T9 (tid=2292855, …
```
> Fix thread leaks in the thread pool

- test_conformance/subgroups/CMakeLists.txt
- test_conformance/subgroups/subgroup_common_templates.h
- test_conformance/subgroups/subhelpers.cpp
- test_conformance/subgroups/subhelpers.h
- test_conformance/subgroups/test_subgroup_ballot.cpp
- test_conformance/subgroups/test_subgroup_clustered_reduce.cpp
The main source of warnings was the use of `%d` for printing a templated type `T`, where `T` could be any cl_ scalar or vector type.
Introduce `print_expected_obtained`.  It takes const references to handle alignment of the cl_ types.
Define `operator<<` for all types used by the subgroup tests.  Ideally those would be template functions enabled by TypeManager data, but that requires some more work on the TypeManager (which we'd ideally do after more warnings have been enabled).  So for now, define the `operator<<` instances using preprocessor defines.
Also fix a few instances where the wrong format specifier was used for `size_t` types.
> subgroups: Fix Wformat warnings

- test_conformance/workgroups/test_wg_suggested_local_work_size.cpp
`value_range` was only used in an `NELEMS` expression; its values were never read.
> [NFC] workgroups: Remove unused array

- test_conformance/api/test_sub_group_dispatch.cpp
The sub-group dispatch tests were making two invalid assumptions about the behaviour of the `clGetKernelSubGroupInfo` API:
1. That for the `CL_KERNEL_LOCAL_SIZE_FOR_SUB_GROUP_COUNT` query the actual size of the local size array being queried via the `param_value_size_ret` must be equal to the size of the out parameter used to query the local size `param_value_size`. If this is not the case it wouldn't be possible to query the required size via `param_value_size_ret` without passing `param_value_size` at the same time, which is the very thing you are querying to find out.
2. That querying the local size (via `CL_KERNEL_LOCAL_SIZE_FOR_SUB_GROUP_COUNT`) for a sub-group count obtained from a `CL_KERNEL_SUB_GROUP_COUNT_FOR_ND_RANGE` with local size `{x, y, z}` will result in the same local …
> Remove invalid assumptions from sub-group tests

- test_conformance/spir/main.cpp
- test_conformance/spir/run_build_test.cpp
`std::exception` and `std::runtime_error` are polymorphic types and as such they shouldn't be passed by value.
> spir: Fix -Wcatch-value warnings

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/common.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/main.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
- test_conformance/math_brute_force/utility.h
Simplify code by relying on RAII to free resources.  Reduce code duplication.
This commit only affects tests that use `BuildKernelInfo`, which are the multi-threaded tests.  Another patch will deal with the single-threaded tests, i.e., those using `BuildKernelInfo2`.
> math_brute_force: Use clKernelWrapper in threaded tests

- test_conformance/relationals/test_shuffles.cpp
It seems the intent was to use `.xyzw` vector component accessors in
the kernel whenever `vecSize` is 2, 3, or 4.  The condition was wrong
(i.e., always true for any value of `vecSize`), causing it to always
create a kernel with numeric (`.s0123...`) vector component accessors.
The restriction on the use of `.xyzw` for 8 and 16-component vectors
has been lifted a while ago (see
https://github.com/KhronosGroup/OpenCL-Docs/issues/549) so we do not
need this check at all.
Also, fix the `vecSize` argument of two calls of `get_order_string`
when getting the order string for the "in" kernel argument.  Pass
`inVecSize` in these cases, not `outVecSize`.
> relationals: Fix vector component accessor selection

- test_conformance/mem_host_flags/mem_host_image.cpp
This would have been an NFC, except that the function name is printed on line 147/148.
> mem_host_flags: Fix WRITE_ONLY typo

- test_conformance/relationals/test_shuffles.cpp
Remove a misleading comment at the end.  Improve comments in general, and use `true`/`false` for `bool`s.
> [NFC] relationals: Tidy up get_order_string

- test_conformance/images/samplerlessReads/main.cpp
So we get finer grain reporting and better parallelisation in the future.
> samplerlessReads: split out 1D Buffer testing into a separate test

- test_conformance/basic/test_progvar.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/spir/run_build_test.cpp
Initialize class members in the order in which they are declared in the class.
> Fix -Wreorder warnings

- test_conformance/events/action_classes.cpp
- test_conformance/events/action_classes.h
`BufferAction::Setup` has an additional parameter `allocate` which causes the virtual function `Action::Setup` to be hidden.  The additional parameter was unused anyway, so remove it.
Fixes a `-Woverloaded-virtual` warning.
> events: Remove unused BufferAction::Setup parameter

- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Simplify code by relying on RAII to free resources.
This commit only affects tests that use `BuildKernelInfo2`, which are the single-threaded tests.
#1562 migrated the threaded math_brute_force tests to `clKernelWrapper` objects; this PR migrates all remaining math_brute_force tests.
> math_brute_force: Use clKernelWrapper in single-threaded tests

- test_conformance/commonfns/test_degrees.cpp
- test_conformance/commonfns/test_fmax.cpp
- test_conformance/commonfns/test_fmaxf.cpp
- test_conformance/commonfns/test_fmin.cpp
- test_conformance/commonfns/test_fminf.cpp
- test_conformance/commonfns/test_mix.cpp
- test_conformance/commonfns/test_radians.cpp
- test_conformance/commonfns/test_sign.cpp
- test_conformance/commonfns/test_step.cpp
The arrays were assigned to, but the values were never used again.
> [NFC] commonfns: Remove unused `values` arrays

- test_conformance/basic/test_image_param.cpp
Fail when an unhandled image format is encountered instead of continuing validation with uninitialized variables.
Fixes a `-Wsometimes-uninitialized` warning for e.g. the `tolerance` variable.
> basic: Return error on unhandled image format

- test_conformance/relationals/test_shuffles.cpp
print_hex_mem_dump was calling `sprintf` with source and destination buffers overlapping, which is explicitly forbidden.  Rewrite the function to use C++ stringstreams instead.
This commit only affects the error path and does not change the printed output.  Error logs before and after this commit should not differ.
> relationals: Use stringstream in print_hex_mem_dump

- test_conformance/extensions/cl_khr_command_buffer/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_queue_substitution.cpp
- test_conformance/extensions/cl_khr_command_buffer/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/procs.h
Introduce series of queue substitution tests for [cl_khr_command_buffer](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_command_buffer) extension according to point 1.3 of [issue](https://github.com/KhronosGroup/OpenCL-CTS/issues/1369) description.
> Command buffer queue substitution

- test_conformance/mem_host_flags/checker_image_mem_host_write_only.hpp
- test_conformance/spir/kernelargs.h
Align `verify_data` with `checker_image_mem_host_read_only.hpp`, that is, take an explicit pointer to compare against.
Add a missing (but unused) `float` parameter to `KernelArgSampler::compare`.
> Fix -Woverloaded-virtual warnings

- test_conformance/basic/test_rw_image_access_qualifier.cpp
There is no particular reason to limit the domain of unsigned 32-bit integers in the input, so use genrand_int32 directly.
> Avoid use of rand in test_rw_image_access_qualifier

- test_conformance/c11_atomics/test_atomics.cpp
I had a case where the test kernel wasn't building because atomic_store requires support for __opencl_c_atomic_order_seq_cst and the device didn't have it.
I believe this store is only used to record some data in the failure case, so it being relaxed is probably fine since further reads of the data come after barriers, like around here: https://github.com/KhronosGroup/OpenCL-CTS/blob/59a1198e5f2f04540736ea0ae03c88069b2a3543/test_conformance/c11_atomics/common.h#L1014-L1019
> c11 atomic fence: relaxed requirements for an auxiliary atomic_store

- test_conformance/select/test_select.cpp
Simplify code by avoiding manual resource management.
This fixes use of an uninitialized `d` in the `free_mtdata` call, in the case a `goto exit` was executed before initializing `d`.
> select: Use MTdataHolder

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_float.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_i_float.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_operator_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/macro_binary_double.cpp
- test_conformance/math_brute_force/macro_binary_float.cpp
- test_conformance/math_brute_force/macro_unary_double.cpp
- test_conformance/math_brute_force/macro_unary_float.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Simplify code by returning directly instead of using goto statements.
Although intended as an NFC commit, this changes the behaviour around
clFlush calls.  Before this commit, failure of the third clFlush call
would print "clFlush 3 failed" and return the clFlush error code.
This behaviour is inconsistent with the other clFlush calls in
math_brute_force, which are not fatal.  The lack of a `goto exit`
makes me suspect that this 3rd clFlush call was intended to be
non-fatal too.  As such, this commit makes all clFlush calls non-fatal
by returning `CL_SUCCESS` even when the third clFlush call fails.
> math_brute_force: Remove unnecessary gotos

- test_conformance/spirv_new/test_op_fmath.cpp
The OpenCL SPIR-V Environment Specification does not require the SPIR-V opcodes `OpFMod` and `OpFRem` to match any OpenCL C semantics, so implementations implementing those two instructions according to Vulkan and/or OpenGL semantics will fail those tests without actually violating any OpenCL specification.
Instead `OpExtInst fmod` should be checked against OpenCL C `fmod` as this is actually specified to match in precision by the SPIR-V Environment Specification and this is what the SPIRV-LLVM-Translator ends up using for fmod anyway.
This also allows implementations to relax their implementations of `OpFMod` and `OpFRem` to trade performance for precision, but also to allow for more consistent results between OpenCL and Vulkan using those SPIR-V instructions.
Closes #1548
Signed-off-by: …
> spirv: disable testing for OpFMod / OpFRem

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
The `command_buffer` member is initialized with `this`, and should thus be initialized after all other members have been initialized, to avoid any potential uninitialized data accesses by `command_buffer`'s constructor.  This is currently not a problem, but would become a problem when `command_buffer`'s constructor accesses the object through its parameter.
Fixes a `-Wreorder` warning.
> [NFC] Fix BasicCommandBufferTest initialization order

- test_conformance/extensions/cl_khr_command_buffer/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_event_info.cpp
- test_conformance/extensions/cl_khr_command_buffer/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/procs.h
Test clGetEventInfo() info queries from event returned by command-buffer enqueue for the single command-queue to command-buffer case:
* CL_EVENT_COMMAND_TYPE is CL_COMMAND_COMMAND_BUFFER_KHR
* CL_EVENT_COMMAND_QUEUE
* CL_EVENT_CONTEXT
* CL_EVENT_COMMAND_EXECUTION_STATUS
* CL_EVENT_REFERENCE_COUNT
> Add test for clGetEventInfo info queries.

- test_conformance/spirv_new/test_op_fmath.cpp
Disabling of frem and fmod by b81b49e1 ("spirv: disable frem and fmod tests for now (#1614)", 2023-02-07) introduced some new warnings about multi-line `//` comments due to the trailing backslashes.  Fix these.
Also fix a typo.
cc: @karolherbst
> [NFC] Fix multi-line comment warnings

- presubmit.sh
test_vulkan is disabled by default as part of
PR #1530.
Given the ongoing development to test_vulkan,
it is important to have this enabled in CI builds
to avoid breaking test builds.
Enable the test build as part of presubmit script.
> Enable test_vulkan by default in presubmit

- test_conformance/spirv_new/test_op_composite_construct.cpp
- test_conformance/spirv_new/test_op_constant.cpp
- test_conformance/spirv_new/test_op_copy_object.cpp
- test_conformance/subgroups/test_subgroup_ballot.cpp
The `cl_*` types need two levels of braces for initialization: the outer braces for the union and the inner braces for the array.
> [NFC] Fix -Wmissing-braces warnings

- test_conformance/gl/test_images_read_common.cpp
`sizes` is a pointer argument, so the expression does not compute the presumably intended number of elements in `sizes`.
Fixes a `-Wsizeof-pointer-div` warning.
> gl: Fix array size expression

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
The OpenCL Headers have cl_khr_external_memory_dx, cl_khr_external_memory_dma_buf and cl_khr_external_semaphore_dx_fence as extension strings, but CTS Compiler fails if an implementation says that it supports them.
> Add compiler test external memory/semaphore extensions

- test_common/harness/os_helpers.cpp
- test_conformance/computeinfo/main.cpp
- test_conformance/device_partition/test_device_partition.cpp
- test_conformance/spir/main.cpp
- test_conformance/spirv_new/test_get_program_il.cpp
Fix some sign-compare warnings.
In `os_helpers.cpp`, the preceding `if` already handles negative values, so cast to unsigned.
> [NFC] Fix some sign-compare warnings

- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
Replace occurrences of `BuildKernelInfo2` with `BuildKernelInfo`. This aligns the kernel creation code of the non-threaded tests to the kernel creation code of the threaded tests, giving opportunities for further code deduplication.
> math_brute_force: Drop BuildKernelInfo2

- .github/workflows/presubmit.yml
Node.js 12 actions are deprecated, so update to v3 which uses Node 16.
See also https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> [CI] Upgrade to actions/checkout@v3

- test_conformance/images/kernel_read_write/test_read_1D.cpp
This variable is shadowed by another variable further down (line 475).
> [NFC] Remove unused imagePtr variable

- test_common/harness/testHarness.cpp
In tests that use the harness, such as SVM svm_atomic_fetch_add, a failure in the clCreateContext call does not result in an overall fail status because of the way error codes are returned in the harness. This patch fixes it so that the conformance test correctly identifies and reports specific subtests that failed.
> test_harness: Update test status upon api failure

- test_conformance/images/kernel_read_write/test_cl_ext_image_from_buffer.cpp
The slice pitch for 1D array image corresponds to a 1D array slice, but the test was computing it as 2D resulting in an incorrect slice pitch after aligning to the slice pitch alignment.
> Fix slice pitch for 1D array images on image_from_buffer_read_positive kernel_read_write images subtest.

- test_conformance/images/kernel_read_write/test_cl_ext_image_from_buffer.cpp
Disable vendor extension formats from image_from_buffer_fill_positive cl_ext_image_from_buffer test, as the verification step is incorrect and can cause seg fault, e.g. for YUV images.
> Disable vendor extension formats from image_from_buffer_fill_positive cl_ext_image_from_buffer test.

- test_conformance/SVM/test_shared_address_space_coarse_grain.cpp
- test_conformance/api/test_api_min_max.cpp
- test_conformance/basic/test_float2int.cpp
- test_conformance/basic/test_int2float.cpp
- test_conformance/buffers/test_buffer_read.cpp
- test_conformance/commonfns/test_mix.cpp
- test_conformance/events/test_events.cpp
- test_conformance/mem_host_flags/checker_mem_host_write_only.hpp
- test_conformance/relationals/test_shuffles.cpp
- test_conformance/workgroups/test_wg_all.cpp
- test_conformance/workgroups/test_wg_any.cpp
- test_conformance/workgroups/test_wg_broadcast.cpp
To the best of my understanding, these occurrences of the `-Wunused-but-set` warnings do not reveal any underlying issues, so we can safely remove these variables.  There are more occurrences of this warning in other places (not touched by this commit) that require further analysis.
> Fix some Wunused-but-set warnings

- test_conformance/api/test_api_consistency.cpp
- test_conformance/api/test_api_min_max.cpp
- test_conformance/api/test_kernel_arg_info.cpp
- test_conformance/api/test_min_image_formats.cpp
- test_conformance/api/test_queries.cpp
- test_conformance/api/test_queue_properties.cpp
Fix sign-compare warnings in the api tests.  Most of these come from comparing an `int` iterator with the result of the `ARRAY_SIZE` macro, which "returns" a `size_t`.
> [NFC] api: Fix sign-compare warnings

- CMakeLists.txt
Enable a larger set of compiler warnings globally for gcc/clang-like compilers.  This should help catch issues early and result in better code quality.  These warnings are primarily aimed at OpenCL-CTS developers, so only enable them for non-release builds.
Ensure `-Wall` and `-Werror` are set before any `-Wno-...` options, as the `-Wall`/`-Werror` flags undo `-Wno-...` for some compilers.
The code base does not compile cleanly with `-Wall` yet, so disable some warnings.  Do this globally for now, to keep this patch small and localized.
Silence `-Wunknown-pragmas` (instead of only making them non-fatal), to avoid verbose warning logs.
> cmake: Enable -Wall for non-release builds

- CMakeLists.txt
This is an alternative to PR #1313.  I think this is a much more straightforward fix, so unless there is some other reason to want extension function prototypes in the near future I think we should go with this solution instead.
Fixes #1254.
In the latest version of the generated headers the `CL_NO_PROTOTYPES` define will suppress declaration of extension functions, so we can continue to declare function pointers with the same name.
> define CL_NO_EXTENSION_PROTOTYPES

- test_conformance/api/test_create_kernels.cpp
- test_conformance/device_partition/test_device_partition.cpp
- test_conformance/multiple_device_context/test_multiple_devices.cpp
Fixed use-after-free and class-memaccess errors when compiling with GCC 12.2.0.
> Changes to make test suite compile on GCC 12.2.0

- test_common/harness/imageHelpers.cpp
Remove the remaining unused variables in the test harness.
Even though this commit does not change behavior, I'm not sure if the lack of a use of these variables highlights an underlying issue?
> [NFC] Remove unused depth_lod variables

- test_common/harness/parseParameters.cpp
- test_common/harness/testHarness.cpp
- test_common/harness/testHarness.h
- test_conformance/gl/main.cpp
- test_conformance/gles/main.cpp
- test_conformance/vulkan/main.cpp
This change introduces a new command-line parameter to enable parallel execution by a specified number of worker threads. When parallel execution is requested, tests are distributed across the worker threads. This behaviour is disabled by default.
This does not currently work for all suites as some of them are using global variables to configure tests. For the suites that do not use global state, this change reduced the execution time by up to 5x on an 8-core machine.
> Add basic support to the harness for parallel test execution

- test_conformance/atomics/test_indexed_cases.cpp
Remove a variable that was set when an OpenCL API call failed, but never read again.  Instead, return immediately upon failure.
> atomics: Remove unused variable in atomic_add_index_bin

- test_conformance/math_brute_force/common.cpp
The OpenCL specification states that the build log is only for clBuildProgram, clCompileProgram or clLinkProgram.  Calling it after clCreateKernel should not give any additional information, so this is effectively dead code.  In case building failed, any logs would already have been printed by `create_single_kernel_helper`.
> math_brute_force: don't get build log after clCreateKernel

- CMakeLists.txt
- test_conformance/basic/CMakeLists.txt
- test_conformance/conversions/CMakeLists.txt
- test_conformance/device_timer/CMakeLists.txt
- test_conformance/images/clCopyImage/CMakeLists.txt
- test_conformance/images/clReadWriteImage/CMakeLists.txt
- test_conformance/images/kernel_read_write/CMakeLists.txt
- test_conformance/mem_host_flags/CMakeLists.txt
- test_conformance/non_uniform_work_group/CMakeLists.txt
Only disable `-Wunused-but-set-variable` for tests that do not compile cleanly with this warning enabled.  This re-enables the warning for most other tests, so that it can catch any new occurrences.
> [NFC] cmake: do not suppress -Wunused-but-set-variable globally

- test_conformance/integer_ops/test_absdiff.cpp
After compiling OpenCL CTS with -fsanitize=undefined I stumbled upon some signed integer overflows.
test_absdiff.cpp:103:24: runtime error: signed integer overflow:
419625160 - -1937831252 cannot be represented in type 'int'
test_absdiff.cpp:101:28: runtime error: signed integer overflow:
1277901399 - -1294103363 cannot be represented in type 'int'
test_absdiff.cpp:140:24: runtime error: signed integer overflow:
8945130301981949496 - -2872789959208163723 cannot be represented in type
'long int'
test_absdiff.cpp:138:29: runtime error: signed integer overflow:
5488544718097069860 - -5558131619970145206 cannot be represented in type
'long int'
The result from these operations was used to compare against the kernel result.
This patch replaces the abs_diff manual computations by a function …
> Avoid integer overflows when computing reference in test_absdiff

- test_conformance/basic/test_progvar.cpp
Fixes issue #1380
These changes will query the device for the latest supported CL C version instead of using a hardcoded value. The create_single_kernel_helper function queries for the latest CL C version internally, so calls to create_single_kernel_helper_with_build_options were replaced with calls to create_single_kernel_helper instead.
> Removed hardcoded -cl-std=CL2.0 build option from progvar tests

- test_conformance/basic/test_get_linear_ids.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
Printing a `size_t` requires the `%zu` specifier.
> Fix some Wformat size_t warnings

- test_conformance/computeinfo/main.cpp
The variable `config_size_ret` is only assigned to inside the `if` by the clGetPlatformInfo/clGetDeviceInfo calls. If the condition is false, we would read uninitialized data.
> computeinfo: fix uses of uninitialized config_size_ret

- test_conformance/allocations/allocation_execute.cpp
- test_conformance/api/test_null_buffer_arg.cpp
- test_conformance/images/clCopyImage/test_loops.cpp
- test_conformance/images/clFillImage/test_loops.cpp
All of these if-else chains compare against enums, which is better done using switch statements.  This helps avoid some `-Wsometimes-uninitialized` warnings of variables that are assigned inside the switch.
> Convert some if-else chains to switch statements

- test_conformance/basic/test_vector_swizzle.cpp
> Added cl_khr_fp16 extension support for test_vector_swizzle from basic

- test_conformance/select/test_select.cpp
In this PR, I'd propose to replace clEnqueueMapBuffer with clEnqueueReadBuffer while reading data from buffers.
In my opinion:
- clEnqueueMapBuffer should be used to read/write small data randomly.
- clEnqueueReadBuffer should be used to read the whole data from the buffer **frequently**.
Vendors implement the clEnqueueMapBuffer API differently. If the buffer is located on the device, and clEnqueueMapBuffer is returning a CPU virtual address of it, the reading speed vary. For example, PCIe writing is asynchronous while PCIe reading is synchronous. This results a gap between the speed of reading and writing to the memory/pointer returned by clEnqueueMapBuffer.
Loading the buffer back to CPU using clEnqueueReadBuffer ensures the frequent data reading always happen on CPU, and it will …
> select: using clEnqueueReadBuffer rather than clEnqueueMapBuffer

- test_conformance/relationals/test_comparisons_fp.h
`RelationalsFPTest` contains a vector of `RelTestBase` pointers to `RelTestParams` instances, so the base class destructor should be virtual to avoid undefined behaviour.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1731
> relationals: add missing virtual destructor

- CMakeLists.txt
- test_conformance/SVM/CMakeLists.txt
- test_conformance/mem_host_flags/checker.h
Fix an instance of this warning in mem_host_flags.
Only disable `-Wsometimes-uninitialized` for the SVM test, which does not compile cleanly with this warning enabled.  Re-enable the warning for the other tests, so that it can catch any new occurrences.
> cmake: do not suppress -Wsometimes-uninitialized globally

- test_conformance/non_uniform_work_group/CMakeLists.txt
- test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.cpp
Remove the unused `nonRemainderGlobalSize` array.  Inspect the result of the `clGetDeviceInfo` call.
As this fixes all occurrences of this warning, remove the suppression flag from this test's CMakeLists.txt.
> non_uniform_work_group: fix unused-but-set variables

- test_conformance/relationals/test_comparisons_fp.cpp
With GCC 13 some headers are no longer included transitively through C++ Standard Library headers.
> relationals: fix missing includes

- presubmit.sh
https://github.com/KhronosGroup/Vulkan-Loader/pull/1212 broke builds that set `USE_GAS=OFF`.
It was originally added to fix aarch64 builds by @nikhiljnv 
>    Disable USE_GAS for Vulkan Loader build to fix aarch64 build.
but it seems we no longer need it.
> [CI] Build Vulkan loader with USE_GAS=ON

- test_conformance/basic/test_async_strided_copy.cpp
This bug was introduced by https://github.com/KhronosGroup/OpenCL-CTS/pull/1711
Ref google/clspv#1127
> fix async strided test outputing error during verify

- test_conformance/mem_host_flags/C_host_memory_block.h
More recent GCC versions (e.g. 12.2, 13.1) report that the array size argument to `new[]` in the `Init` methods exceeds the maximum object size, seemingly related to the negative range of the widened `int`.
Use an unsigned type to avoid the warning and propagate the signedness change to other uses of the `num_elements` member.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1582
> mem_host_flags: use size_t for element count

- test_common/harness/compat.h
- test_common/harness/crc32.h
- test_conformance/c11_atomics/common.h
- test_conformance/c11_atomics/host_atomics.h
- test_conformance/d3d10/harness.h
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_basic.h
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/procs.h
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_base.h
- test_conformance/extensions/cl_khr_command_buffer/procs.h
- test_conformance/extensions/cl_khr_external_semaphore/procs.h
- test_conformance/images/kernel_read_write/test_cl_ext_image_buffer.hpp
- test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.h
- test_conformance/non_uniform_work_group/tools.h
- test_conformance/pipes/kernels.h
- test_conformance/relationals/test_comparisons_fp.h
Names that begin with an underscore followed by an uppercase letter are reserved for the C++ implementation.
> [NFC] Do not use reserved names for include guards

- test_conformance/basic/CMakeLists.txt
- test_conformance/basic/test_work_item_functions.cpp
Remove the unused `numItems` variable.
As this fixes all occurrences of this warning in test_basic, remove the suppression flag.
> basic: fix unused-but-set variables

- test_conformance/compiler/test_compile.cpp
The result of the `strdup` was never freed.  The string duplication isn't necessary, so remove it.
> compiler: fix memory leak from unnecessary strdup

- test_conformance/spirv_new/spirv_asm/vector_times_scalar_half.spvasm32
- test_conformance/spirv_new/spirv_asm/vector_times_scalar_half.spvasm64
- test_conformance/spirv_new/test_op_vector_times_scalar.cpp
- test_conformance/spirv_new/types.hpp
> Added cl_khr_fp16 extension support for test vector_times_scalar from spirv_new

- test_conformance/extensions/cl_khr_command_buffer/command_buffer_get_command_buffer_info.cpp
- test_conformance/extensions/cl_khr_command_buffer/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/procs.h
Test coverage for spec PR https://github.com/KhronosGroup/OpenCL-Docs/pull/899 which introduces a new cl_khr_command_buffer query for the cl_context.
> Test CL_COMMAND_BUFFER_CONTEXT_KHR

- test_conformance/workgroups/test_wg_all.cpp
- test_conformance/workgroups/test_wg_any.cpp
- test_conformance/workgroups/test_wg_broadcast.cpp
- test_conformance/workgroups/test_wg_suggested_local_work_size.cpp
In preparation of re-enabling `-Wsign-compare` globally, fix some instances of this warning.
> workgroups: fix -Wsign-compare warnings

- test_conformance/workgroups/test_wg_suggested_local_work_size.cpp
`create_single_kernel_helper` is called in a loop, overwriting the objects contained in the wrapper classes.  The wrapper class is not aware of this, as the overwriting happens through its `operator&`.
Move the wrapper objects into the loop, so that the contained objects get released as soon as the program and kernel objects are no longer needed.
> workgroups: fix program/kernel object leak

- test_conformance/basic/test_enqueue_map.cpp
clang-format this file ahead of some warning fixes.  Especially the indentation in `test_enqueue_map_image` was quite wrong.
> [NFC] clang-format basic/test_enqueue_map.cpp

- test_conformance/conversions/conversions_data_info.h
For conversion from integers to floating point, the `DataInfoSpec` constructor tries to convert `CL_FLT_MAX` to an integer.  The float value cannot be represented as an integer, which is undefined behaviour.
Fix by only doing this conversion when `InType` is a floating point value.
The refactoring of the conversions test dropped the workaround added by 59a12047a ("Fix for test_conversions failure with Clang build on Linux #1057 (#1062)", 2021-05-11).
While at it, prefer `static_cast` for the conversions.
> conversions: fix undefined behaviour in DataInfoSpec

- test_conformance/conversions/basic_test_conversions.cpp
Avoid a shift by 64 on a `uint64_t`.  The value resulting from the spurious shift was overwritten later, so just avoid the shift in that case.
> conversions: fix undefined behaviour from shift by 64

- test_conformance/basic/test_int2fp.cpp
With GCC 13 some headers are no longer included transitively through C++ Standard Library headers.
> basic/int2fp: fix missing include

- test_conformance/conversions/test_conversions.cpp
`gMTdata` was initialized twice, but freed only once.
Drop the first initialization with a local seed, and initialize with `gRandomSeed` instead.
> conversions: fix memory leak from excess gMTdata initialization

- test_conformance/math_brute_force/unary_two_results_float.cpp
Avoid a maybe-uninitialized warning by ensuring that `oldMode` is always initialized to 0.  There is no need to use `memset` for this, as `FPU_mode_type` is either an `int` or an `int64_t`.
> math_brute_force: always initialize oldMode

- test_conformance/extensions/cl_khr_command_buffer/command_buffer_get_command_buffer_info.cpp
The enum value `CL_COMMAND_BUFFER_STATE_INVALID_KHR` no longer exists:
* https://github.com/KhronosGroup/OpenCL-Headers/pull/235
* https://github.com/KhronosGroup/OpenCL-Docs/pull/885
Replace variable initialization using this enum with a value where all the bits are set, requiring the runtime to write to it in `clGetCommandBufferInfoKHR` for the test to pass.
> [command-buffer] Remove deleted enum used to initialize variable

- test_common/harness/mt19937.cpp
The initialisation code is clearly meant to be run once but the volatile flag did not guarantee that at all:
- Volatile does not mean atomic and loading the flag vs. other writes was not safe.
- Multiple threads could have loaded 0 and performed the initialisation resulting in write collisions.
Rely on std::call_once to provide the guarantee.
This issue was flagged by TSAN.
> Make genrand_int32 thread safe

- test_conformance/atomics/test_indexed_cases.cpp
Before this change, `add_index_bin_test` would not always release `cl_mem` resources or `malloc`ed memory when encountering an error.  Fix by using `clMemWrapper` and `std::unique_ptr` to automatically release resources.
> atomics: fix memory leaks on error paths

- test_conformance/subgroups/subgroup_common_templates.h
- test_conformance/subgroups/subhelpers.cpp
- test_conformance/subgroups/subhelpers.h
- test_conformance/subgroups/test_workitem.cpp
The subgroup and workgroup sizes reported by clGetKernelSubGroupInfo and clGetKernelWorkGroupInfo are of type `size_t`.  Avoid changing the values to an `int` type as they are propagated through the tests and then compared against `size_t` again.
> subgroups: fix Wsign-compare warnings

- test_conformance/extensions/cl_khr_command_buffer/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_finalize.cpp
- test_conformance/extensions/cl_khr_command_buffer/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/procs.h
This patch adds two test cases related to command-buffer finalization:
1) That it is an error to finalize and already finalized command-buffer. See https://github.com/KhronosGroup/OpenCL-Docs/pull/817
2) That it is not an error to create, finalize, and execute an empty command-buffer. Closes issue #1781
> [Command-buffer] Test finalizing empty command-buffer

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_info.cpp
This change fixes a sporadic failure in the mutable_command_dimensions test.
The previous test passed an uninitialized `size_t` variable as the return location for the `CL_MUTABLE_DISPATCH_DIMENSIONS_KHR` query, though this query only returns a `cl_uint`.  This meant that the test sometimes passes, especially for 32-bit builds, where `sizeof(size_t) == sizeof(cl_uint)`, but will frequently fail for larger values of `size_t` if the upper bits of the uninitialized variable are non-zero.  Changing to a `cl_uint` instead fixes the sporadic failures.
I also fixed a few ambiguous or incorrect error messages.
With these changes I'm seeing a 100% pass rate for the mutable dispatch tests with the command buffer emulation layer.
> fix a sporadic failure in the mutable_command_dimensions test

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.hpp
- test_conformance/common/vulkan_wrapper/vulkan_api_list.hpp
- test_conformance/common/vulkan_wrapper/vulkan_list_map.cpp
- test_conformance/common/vulkan_wrapper/vulkan_list_map.hpp
- test_conformance/common/vulkan_wrapper/vulkan_utility.cpp
- test_conformance/common/vulkan_wrapper/vulkan_utility.hpp
- test_conformance/common/vulkan_wrapper/vulkan_wrapper.cpp
- test_conformance/common/vulkan_wrapper/vulkan_wrapper.hpp
- test_conformance/vulkan/main.cpp
- test_conformance/vulkan/test_vulkan_api_consistency.cpp
- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
- test_conformance/vulkan/test_vulkan_interop_image.cpp
- test_conformance/vulkan/vulkan_interop_common.hpp
Fix Vulkan spec violation issues:
- Program Vulkan descriptor set layouts as arrays where appropriate:
Vulkan shader code binds images and buffers as arrays:
layout(binding = 1) buffer Buffer
{
uint8_t ptr[];
} bufferPtrList[MAX_BUFFERS];
bufferPtrList is an array of size MAX_BUFFERS at binding 1.
This requires a VkDescriptorSetLayoutBinding with binding=1, and descriptorCount=MAX_BUFFERS.
From the Khronos spec "descriptorCount is the number of descriptors contained in the binding, accessed in a shader as an array"
The test previously assumed bufferPtrList[i] maps to binding site 1 + i, with descriptorCount=1.  This is not valid, and not portable.
See https://registry.khronos.org/vulkan/specs/1.1-extensions/html/vkspec.html#descriptorsets-sets
- Change VULKAN_QUEUE_FLAG_MASK_ALL to …
> External memory updates

- test_conformance/extensions/cl_khr_command_buffer/command_buffer_event_sync.cpp
queue has a command that depends on a command that resides in queue_sec, calling clFinish(queue) before clFinish(queue_sec) causes the test to hang as the queue_sec command never got a chance to finish.
> Command buffer wait_for_sec_queue_event subtest, call clFinish in the correct order.

- test_conformance/math_brute_force/macro_unary_float.cpp
Simplify code by returning directly instead of using goto statements.
Although intended as an NFC commit, this changes the behaviour when verification fails: the output buffer is no longer unmapped.  Although not ideal, this aligns the behaviour of `macro_unary_float` to the other math_brute_force tests.
> math_brute_force: remove gotos in macro_unary_float

- test_conformance/basic/test_enqueue_map.cpp
- test_conformance/basic/test_fpmath.cpp
- test_conformance/basic/test_intmath.cpp
- test_conformance/basic/test_vector_creation.cpp
- test_conformance/c11_atomics/test_atomics.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_get_command_buffer_info.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_profiling.cpp
- test_conformance/pipes/test_pipe_limits.cpp
- test_conformance/select/test_select.cpp
Fix `-Wsign-compare` warnings in multiple tests.  Most of these are trivial `for`-loop iterator type changes.
> Fix more -Wsign-compare warnings

- test_common/gl/helpers.cpp
In preparation of re-enabling -Wformat globally, fix format string warnings in test_common.
Printing a `size_t` requires the `%zu` specifier.
> test_common: fix -Wformat warnings

- test_common/gl/helpers.cpp
The `CHECK_GL_ERROR` macro was lowercase before, which confused clang-format and resulted in some odd indentations.  Capitalize the macro and run clang-format to fix the indentation.
> test_common: Capitalize macro and run clang-format

- CMakeLists.txt
- test_conformance/SVM/CMakeLists.txt
- test_conformance/allocations/CMakeLists.txt
- test_conformance/basic/CMakeLists.txt
- test_conformance/c11_atomics/CMakeLists.txt
- test_conformance/conversions/CMakeLists.txt
- test_conformance/device_execution/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/CMakeLists.txt
- test_conformance/geometrics/CMakeLists.txt
- test_conformance/images/kernel_read_write/CMakeLists.txt
Only disable `-Wsign-compare` for tests that do not compile cleanly with this warning enabled.  Re-enable the warning for the other tests, so that it can catch any new occurrences.
> [NFC] cmake: do not suppress -Wsign-compare globally

- test_conformance/select/test_select.cpp
- test_conformance/select/util_select.cpp
Fix the following issues in the select tests:
* Printing of a `size_t` requires the `%z` specifier.
* Printing of `cl_long`/`cl_ulong` is now done using the `PRI*64` macros to ensure portability across 32 and 64-bit builds.
> select: fix -Wformat warnings

- test_conformance/api/test_queue_properties.cpp
test_conformance/api/test_queue_properties.cpp uses a cl_queue_properties_khr value to query CL_DEVICE_QUEUE_PROPERTIES, however this should be a cl_command_queue_properties typed variable.
Fixes issue #1640
> Replace cl_queue_properties_khr with cl_command_queue_properties

- test_conformance/api/test_queries.cpp
OpenCL FULL profile requires that online compiler be available. OpenCL-CTS currently queries profile as well as online compiler availability via device queries, but doesn't check for the consistency.
Check for consistency that if CL_DEVICE_PROFILE is "FULL_PROFILE" (or technically is not "EMBEDDED_PROFILE") then CL_DEVICE_COMPILER_AVAILABLE is CL_TRUE for that device.
Fixes #1763
> Check that CL_DEVICE_COMPILER_AVAILABLE is CL_TRUE for FULL_PROFILE

- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
The suite's `main()` function already disables the FTZ mode prior to invoking `runTestHarnessWithCheck` and restores the FP state afterwards, so tests don't have to do so themselves.
> math_brute_force: don't set/restore FTZ mode twice

- test_conformance/api/test_mem_object_info.cpp
The spec requires implementations return NULL for CL_MEM_HOST_PTR when the flags passed at memory object creation time do not contain CL_MEM_USE_HOST_PTR
CTS was not checking this. Add the same check.
Fixes #1752
> Add NULL CL_MEM_HOST_PTR check for clGetMemObjectInfo

- test_conformance/conversions/conversions_data_info.h
We haven't tested this since we don't support the data type but the build fix is needed to build for x86 Windows.
> conversions: Build fix for x86 toolchain

- test_conformance/c11_atomics/common.h
Initialize the `_memoryOrder` and `_memoryScope` members to avoid `CBasicTestMemOrderScope::MaxHostThreads()` accessing uninitialized data.
> c11_atomics: fix uninitialized member accesses

- test_conformance/profiling/main.cpp
* Printing of `size_t` requires the `%z` specifier.
* Printing of `cl_ulong` is now done using the `PRIu64` macro to ensure portability across 32 and 64-bit builds.
> profiling: fix -Wformat warnings

- test_conformance/c11_atomics/host_atomics.h
Some `HOST_` types were declared with signedness different from the `HOST_ATOMIC_` counterparts, leading to sign-compare warnings when comparing between types.  Fix by aligning the signedness.
> c11_atomics: align signedness of host types

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
- test_conformance/vulkan/test_vulkan_api_consistency.cpp
fixes #1807 
Switches to the new specific device handle list enums for external memory and semaphores, rather then the old overloaded device handle list enum.
I've added some preprocessor checks at the top of each file so these tests will continue to build with older headers, for now at least.  I'd be fine removing these checks right now, in this PR, or we could remove them at some point in the future once the header changes are in place (see: https://github.com/KhronosGroup/OpenCL-Headers/pull/240).
> switch to the new memory and semaphore specific device handle lists

- test_conformance/allocations/allocation_execute.cpp
The test uses a fixed number of work items to process very large buffers and images. As devices support more and more memory, this leads to an ever-increasing amount of work done in each work item. This results in some implementations and devices hitting timeout issues.
Furthermore, a greater number of work items can provide performance benefits on some devices.
Long term, this test should be redesigned to scale the number of threads dynamically as a function of the max allocation size.
> Increase the number of work items used by the allocations test

- test_conformance/allocations/allocation_execute.cpp
> allocations: Move results array from stack to heap

- test_conformance/SVM/test_migrate.cpp
- test_conformance/basic/test_work_item_functions.cpp
Array size is too large so that there is stack overflow issue on Win32. Use std::vector to avoid the issue.
> Fix windows stack overflow.

- test_conformance/c11_atomics/test_atomics.cpp
Reduce the loop from 1000000 to 500000 since the former value makes the test run too long and cause system issues on certain platforms
> c11_atomics: Reduce the loopcounter for sequential consistency tests

- test_conformance/geometrics/CMakeLists.txt
- test_conformance/geometrics/test_geometrics_double.cpp
Fix all instances of Wsign-compare warnings in the geometrics test, and re-enable the warning so it can catch any new occurrences.
> geometrics: fix Wsign-compare warnings

- test_conformance/integer_ops/test_abs.cpp
- test_conformance/integer_ops/test_absdiff.cpp
- test_conformance/integer_ops/test_add_sat.cpp
- test_conformance/integer_ops/test_integers.cpp
- test_conformance/integer_ops/test_intmad24.cpp
- test_conformance/integer_ops/test_intmul24.cpp
- test_conformance/integer_ops/test_popcount.cpp
- test_conformance/integer_ops/test_sub_sat.cpp
- test_conformance/integer_ops/test_unary_ops.cpp
- test_conformance/integer_ops/test_upsample.cpp
- test_conformance/integer_ops/verification_and_generation_functions.cpp
* Printing of a `size_t` which requires the `%zu` specifier.
* Printing of `cl_long`/`cl_ulong` which is now done using the `PRI*64` macros to ensure portability across 32 and 64-bit builds.
I've split out the clang-formatting of my changes into a separate commit to ease reviewing.
> integer_ops: fix -Wformat warnings

- test_conformance/conversions/CMakeLists.txt
- test_conformance/conversions/fplib.cpp
Remove an assigned-to but unused variable.
Reenable the Wunused-but-set-variable warning for the conversions
suite, as it now compiles cleanly with this warning enabled.
> [NFC] conversions: reenable Wunused-but-set-variable

- test_conformance/conversions/conversions_data_info.h
If the input is long type, it should be load as long type, not ulong.
> Fix bug of conversion from long to double

- test_conformance/math_brute_force/unary_float.cpp
Fix the ULP error calculation for the `exp` and `exp2` builtins in relaxed math mode for the full profile.
Previously, the `ulps` value kept being added to while verifying the result buffer in a loop.  `ulps` could even become a `NaN` when the input argument being tested was a `NaN`.
> math_brute_force: fix exp/exp2 rlx ULP calculation

- CMakeLists.txt
32-bit executables built with MSVC linker have only 2GB virtual memory address space by default, which might not be sufficient for some tests.
Enable LARGEADDRESSAWARE linker flag for 32-bit targets to allow tests to handle addresses larger than 2 gigabytes.
Fixes #1842
https://learn.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=msvc-170
> Enable LARGEADDRESSAWARE for 32 bit compilation

- test_conformance/images/kernel_read_write/main.cpp
This function (do_test) starts by testing write and read individually. Both of them can have errors.
When readwrite image is not supported, the function returns TEST_SKIPPED_ITSELF potentially masking errors leading to the test returning EXIT_SUCCESS even with errors along the way.
> fix return code when readwrite image is not supported

- .github/workflows/presubmit.yml
- test_conformance/spir/CMakeLists.txt
- test_conformance/spir/main.cpp
fixes #1862 
This PR modernizes the CMakeLists.txt for test_spir.  It uses target specific commands to add compile options and compile definitions vs. setting COMPILE_FLAGS and adding definitions globally.  This fixes the macos builds, which broke when the runner updated to a new version of CMake.
> fix macos builds by avoiding double compilation of function_list.cpp for test_spir

- test_common/harness/crc32.h
- test_conformance/spirv_new/CMakeLists.txt
- test_conformance/spirv_new/main.cpp
- test_conformance/spirv_new/procs.h
- test_conformance/spirv_new/testBase.h
- test_conformance/spirv_new/test_cl_khr_spirv_no_integer_wrap_decoration.cpp
- test_conformance/spirv_new/test_decorate.cpp
- test_conformance/spirv_new/test_get_program_il.cpp
- test_conformance/spirv_new/test_linkage.cpp
- test_conformance/spirv_new/test_op_atomic.cpp
- test_conformance/spirv_new/test_op_branch.cpp
- test_conformance/spirv_new/test_op_branch_conditional.cpp
- test_conformance/spirv_new/test_op_composite_construct.cpp
- test_conformance/spirv_new/test_op_constant.cpp
- test_conformance/spirv_new/test_op_copy_object.cpp
- test_conformance/spirv_new/test_op_fmath.cpp
- test_conformance/spirv_new/test_op_function.cpp
- test_conformance/spirv_new/test_op_lifetime.cpp
- test_conformance/spirv_new/test_op_loop_merge.cpp
- test_conformance/spirv_new/test_op_negate.cpp
- test_conformance/spirv_new/test_op_opaque.cpp
- test_conformance/spirv_new/test_op_phi.cpp
- test_conformance/spirv_new/test_op_selection_merge.cpp
- test_conformance/spirv_new/test_op_spec_constant.cpp
- test_conformance/spirv_new/test_op_undef.cpp
- test_conformance/spirv_new/test_op_vector_extract.cpp
- test_conformance/spirv_new/test_op_vector_insert.cpp
- test_conformance/spirv_new/test_op_vector_times_scalar.cpp
- test_conformance/spirv_new/types.hpp
fixes #1471
The source files for the spirv-new tests were using the older Khronos license instead of the proper Apache-2.0 license.  This PR fixes the license header in all source files.
Note, I removed the license header from CMakeLists.txt instead of replacing it because none of the other CMakeLists.txt seemed to have a license header.  If we add a license header to CMakeLists.txt we should add it to all of them.
No functional changes.
> fix the license header on the spirv-new tests

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.hpp
- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
- test_conformance/vulkan/main.cpp
- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
- test_conformance/vulkan/test_vulkan_interop_image.cpp
Additionally updated common semaphore code to handle spec updates that restrict simultaneous importing/exporting of handles.
See docs issue #939
> Updated semaphore tests to use clSemaphoreReImportSyncFdKHR.

- test_conformance/math_brute_force/main.cpp
When the math brute force test printed the platform version it always printed information for the first platform in the system, which could be different than the platform for the passed-in device.  Fixed by querying the platform from the passed-in device instead.
> fix the reported platform information for math brute force

- test_conformance/api/test_mem_object_info.cpp
Add call of free_mtdata function in test_get_image_info. This fixes memory leak in api tests.
Fixes #1870.
> api tests fix: Free MTdata object in test_get_image_info

- test_common/harness/errorHelpers.cpp
- test_common/harness/errorHelpers.h
- test_conformance/math_brute_force/ternary_half.cpp
- test_conformance/math_brute_force/utility.h
Half-precision functions are generally tested against the single-precision reference. This causes double rounding: first to single precision, then from there to half precision. For the most part, it is good enough, but specifically in the case of fma, a correctly rounded result is required and is not obtained, for instance for arguments 0x1.eacp+7, 0x1.3f4p+4, 0x1.c04p+14, which produce an exact result of 0x1.065fffp+15 which should be rounded to half-prefcision 0x1.064p+15, but was previously first rounded to single-precision 0x1.066p+15, and from there to half-precision 0x1.068p+15. Testing against reference_fmal gives us sufficient precision that double rounding does not cause issues.
The f_fma(..., FLUSHED) calls for FTZ testing cannot be updated the same way but do not need to be: …
> Fix testing of half-precision fma.

- test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_main.spvasm32
- test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_main.spvasm64
- test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_noa_main.spvasm32
- test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_noa_main.spvasm64
- test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_obj.spvasm32
- test_conformance/spirv_new/spirv_asm/linkage_linkonce_odr_obj.spvasm64
- test_conformance/spirv_new/test_linkage.cpp
Adds a basic test for `cl_khr_spirv_linkonce_odr`.
This test compiles two SPIR-V modules and links them together to create the test kernel.
The first SPIR-V module defines two functions, `a` and `b`.  `a` has **LinkOnceODR** linkage, and `b` has **Export** linkage, as usual:
```c
int a(int x) { // LinkOnceODR
return x + 5;
}
int b(int x) { // Export
return -x;
}
```
The second SPIR-V module also defines `a` with **LinkOnceODR** linkage, and has an **Import** dependency on `b`.  The `test` kernel calls into both `a` and `b`:
```c
int a(int x) { // LinkOnceODR
return x + 5;
}
int b(int x); // Import
kernel void test(global int* dst) {
int id = get_global_id(0);
dst[id] = a(id) + b(id);
}
```
If the two modules are not linked together properly then the definition of `b` will not be found.
If …
> add test for cl_khr_spirv_linkonce_odr

- test_conformance/subgroups/procs.h
In C and C++ all functions have external linkage by default.
Also remove the unused `gMTdata` and `test_pipe_functions` declarations.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1137
> [NFC] subgroups: remove unnecessary extern keywords

- test_conformance/SVM/test_fine_grain_memory_consistency.cpp
- test_conformance/compiler/test_pragma_unroll.cpp
- test_conformance/computeinfo/main.cpp
- test_conformance/gl/test_image_methods.cpp
- test_conformance/spir/run_services.cpp
- test_conformance/subgroups/subgroup_common_templates.h
- test_conformance/workgroups/test_wg_broadcast.cpp
All of these warnings stem from printing `size_t` types, which should be done using the `z` length modifier.
> Fix -Wformat warnings in multiple tests

- test_conformance/subgroups/subhelpers.cpp
* Was causing a build error with GN
* fill_and_shuffle_safe_values() in subhelpers.cpp calls std::shuffle()
* std::shuffle is defined in <algorithm>
> subgroups: Add missing algorithm header

- test_conformance/vectors/structs.cpp
Use the `z` length modifier for printing `size_t` types.
Also fix a typo in the error messages.
> vectors: fix -Wformat warnings

- test_conformance/device_execution/device_queue.cpp
- test_conformance/device_execution/enqueue_block.cpp
- test_conformance/device_execution/enqueue_flags.cpp
- test_conformance/device_execution/enqueue_multi_queue.cpp
- test_conformance/device_execution/enqueue_ndrange.cpp
- test_conformance/device_execution/enqueue_profiling.cpp
- test_conformance/device_execution/enqueue_wg_size.cpp
- test_conformance/device_execution/host_multi_queue.cpp
- test_conformance/device_execution/host_queue_order.cpp
- test_conformance/device_execution/nested_blocks.cpp
When reporting errors from `clCreateCommandQueueWithProperties`, report the correct property names.  In particular:
`CL_QUEUE_DEVICE` should be `CL_QUEUE_ON_DEVICE`.
`CL_QUEUE_DEFAULT` should be `CL_QUEUE_ON_DEVICE_DEFAULT`.
> device_execution: fix CL_QUEUE_* in error messages

- .github/workflows/presubmit.yml
Node.js 16 actions are [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), so update to v4 which uses Node 20.
> [CI] Upgrade to actions/checkout@v4

- .github/dependabot.yml
see #1920 
This sets up dependabot updates to GitHub actions.
I have been using a similar config file in my repos and it has been working well.  Currently, it is setup to check for updates monthly, but we can check for updates more or less frequently as needed.
> configure depdendabot github actions version updates

- test_common/harness/imageHelpers.cpp
Add support for `CL_UNORM_INT_101010_2` in the `get_pixel_size` helper function. 
This fixes the following tests:
-  memInfo_image_from_buffer_positive
- image_from_buffer_alignment_negative
- imageInfo_image_from_buffer_positive
> Fix failing image tests for CL_UNORM_INT_101010_2

- test_conformance/relationals/test_shuffles.cpp
`inOrderStr` and `outOrderStr` are both written into `orderName` on line 261, which may not fit as all three are the same size.  Decrease the sizes of `inOrderStr` and `outOrderStr`.  The new sizes are still sufficiently large to hold the result of `get_order_string`.
This commit only affects the error path and does not change the printed output.  Error logs before and after this commit should not differ.
> relationals: fix -Wformat-truncation warning

- test_conformance/half/Test_roundTrip.cpp
- test_conformance/half/Test_vLoadHalf.cpp
- test_conformance/half/Test_vStoreHalf.cpp
- test_conformance/half/cl_utils.cpp
Avoid casting to `uint64_t` in some places; instead keep the types as `size_t` and use the `%z` length modifier, or as
`uint32_t` and use the `%u` specifier.
For printing of 64-bit types, use the `PRI*64` macros from `<cinttypes>` to ensure portability across 32 and 64-bit builds.
> half: fix -Wformat warnings

- test_conformance/subgroups/subhelpers.cpp
There appears to have been some confusion over `uint_mask` during the initial reviews of the subgroup tests.  Add a comment to clarify the purpose of the mask.
Use a 32-bit all-ones mask (`0xffffffff`) instead of a 64-bit all-ones mask to further clarify the intent, that is, don't delay discarding the upper 32 bits until the assignment but mask them out immediately.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1203
> [NFC] subgroups: clarify bs128 to uint4 conversion

- test_conformance/integer_ops/test_extended_bit_ops_extract.cpp
We compute the reference values using unsigned types exclusively, even when the input type is signed.  This fixes one place where an signed type was inadvertently used.
> fix the type used for bitfield_extract_signed

- test_conformance/spirv_new/test_decorate.cpp
- test_conformance/spirv_new/test_op_spec_constant.cpp
`log_error` was invoked from a template function, but the format specifiers weren't adjusted for the template parameter types.  Use a stringstream for printing instead.
> spirv_new: fix -Wformat warnings

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_arguments.cpp
-added verification of device capabilities against mutable arguments 
-general cleanup
> Corrections for mutable arguments tests

- test_conformance/extensions/cl_khr_external_semaphore/main.cpp
- test_conformance/extensions/cl_khr_external_semaphore/procs.h
- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
Multi-context test was not correctly testing cross-context functionality. Use semaphore import/export mechanism to signal across contexts.  Also add missing acquire/release calls. Fixes outstanding #1588 issues.
> Fix cross-context semaphore signals

- test_conformance/math_brute_force/binary_operator_half.cpp
In the fp32 divide test, the range clamps are needed for the "fast relaxed math" testing, but there is no "fast relaxed math" testing for fp16.  This means that the range clamps are unnecessary and can be removed.
> remove special-case range clamps for the fp16 divide test

- test_conformance/device_execution/enqueue_block.cpp
- test_conformance/device_execution/enqueue_flags.cpp
- test_conformance/device_execution/enqueue_ndrange.cpp
- test_conformance/device_execution/enqueue_wg_size.cpp
- test_conformance/device_execution/execute_block.cpp
- test_conformance/device_execution/nested_blocks.cpp
Printing of a `size_t` requires the `%zu` specifier.
> device_execution: fix -Wformat warnings

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
Only report an error (and include the error code), but don't throw an exception as that would call `terminate`.  Failure to release resources is not fatal in other parts of the CTS.
This fixes `-Wterminate` warnings:
warning: ‘throw’ will always call ‘terminate’ [-Wterminate]
note: in C++11 destructors default to ‘noexcept’
> test_vulkan: don't throw from destructors

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
The `test_compiler compiler_defines_for_extensions` test did not free all `malloc`'ed memory.
> compiler: fix memory leak

- test_conformance/printf/test_printf.cpp
- test_conformance/printf/test_printf.h
- test_conformance/printf/util_printf.cpp
According to work plan from issue #1058
> Corrections for printf test with floating point limits arguments

- test_conformance/SVM/CMakeLists.txt
- test_conformance/SVM/common.h
- test_conformance/SVM/main.cpp
- test_conformance/SVM/test_allocate_shared_buffer_negative.cpp
Isuue #875 clarified that CL_INVALID_BUFFER_SIZE should be returned if clCreateBuffer is passed a pointer returned by clSVMAlloc as its host_ptr and the size of the buffer exceeds the size of the SVM allocation.
Add a new negative test to ensure CL_INVALID_BUFFER_SIZE is returned when the size of buffer exceeds the size of the SVM allocation.
Fixes #1701
> Add negative test for test_svm size check

- test_common/harness/errorHelpers.cpp
- test_common/harness/imageHelpers.cpp
- test_common/harness/imageHelpers.h
- test_conformance/images/kernel_read_write/CMakeLists.txt
- test_conformance/images/kernel_read_write/main.cpp
- test_conformance/images/kernel_read_write/test_cl_ext_image_raw10_raw12.cpp
- test_conformance/images/kernel_read_write/test_iterations.cpp
Add support for cl_ext_image_raw10_raw12 testing
on test_image_streams.
> Raw10/12 CTS tests

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
- test_conformance/vulkan/test_vulkan_interop_image.cpp
Add acquire/release commands where appropriate.  This is related to 1886.
> Add acquire/release

- test_conformance/basic/test_vector_swizzle.cpp
Prevent the compiler from optimizing away initialization loops
> basic: workaround MSVC compiler bug with post-increment operator

- test_common/harness/integer_ops_test_info.h
test_common/harness/integer_ops_test_info.h is using std::vector but is not including the header.
This is breaking on Google internal CI.
> add missing header

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.hpp
- test_conformance/common/vulkan_wrapper/vulkan_api_list.hpp
- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
- test_conformance/vulkan/test_vulkan_interop_image.cpp
Except for SYNC_FD, current implementation doesn't import exported OpenCL semaphore in Vulkan and ends up doing signal and wait on essentially two unrelated semaphores (one created in OpenCL and one in Vulkan).
Since OpenCL exports the semaphore, import that in Vulkan to perform signal/wait on the same underlying payload.
> Import OpenCL exported semaphore in Vulkan 

- test_conformance/mem_host_flags/CMakeLists.txt
- test_conformance/mem_host_flags/checker_image_mem_host_no_access.hpp
- test_conformance/mem_host_flags/checker_mem_host_no_access.hpp
The specification states that `clEnqueueMapImage` and `clEnqueueMapBuffer` should return NULL on error.  Ensure this is checked.
This testing gap was caught by a compiler warning about `dataPtr` being written but not read.  With this fix, there are no more Wunused-but-set-variable warnings in this test, so reenable the warning.
> mem_host_flags: check returned pointer for NULL

- test_conformance/extensions/cl_khr_kernel_clock/kernel_clock.cpp
According to the [specification](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#kernel-clock-functions), the work_group and sub_group variants have an `_` in them.
> cl_khr_kernel_clock: fix builtin function names

- test_common/harness/imageHelpers.cpp
Currently we don't escape subnormal values when generating image data. In sampler read tests, we use `!=` to check the two values even when it is floating-point data, which requires the two values are bitwise equal. However, a sampler might flush subnormal values, causing the test case to fail.
In this patch, when generating random image data, we escape subnormal values.
> Escape subnormal values

- test_conformance/relationals/test_shuffles.cpp
The values in `src` are indices into an array in `get_order_string()`. Not initializing `src` resulted in out of bounds accesses there.
It seems that when the out of bounds accesses happened, the result of `get_order_string()` was not actually used, so at least the test was not using random data.  Fix the issue as it prevents a clean run of this test with e.g. AddressSanitizer.
> relationals: fix out of bounds accesses in shuffle test

- test_conformance/extensions/cl_khr_semaphore/test_semaphores.cpp
This PR addresses the first part of #1691 issue and #1875 issue.
> Added new query for cl_khr_semaphore test to verify device handle list

- test_conformance/images/kernel_read_write/test_cl_ext_image_from_buffer.cpp
The Image_from_buffer_alignment_negative test creates images with incorrect pitches by adding 1 and tests whether the image creation fails.
Devices that return 1 for either of CL_IMAGE_REQUIREMENTS_ROW_PITCH_ALIGNMENT_EXT, CL_IMAGE_REQUIREMENTS_SLICE_PITCH_ALIGNMENT_EXT or CL_IMAGE_REQUIREMENTS_BASE_ADDRESS_ALIGNMENT_EXT will successfully create the image and therefore fail the test.
This change allows to skip the image creation in this case as the error condition (pitch % pitch_alignment != 0) will not be triggered for these devices.
> Fixes for Image_from_buffer_alignment_negative when alignments are 1

- test_conformance/extensions/cl_khr_kernel_clock/kernel_clock.cpp
`create_single_kernel_helper` invokes `clBuildProgram` and sets `-cl-std` to the latest version supported by the context.
The vast majority of tests are using `create_single_kernel_helper` instead of the `..._create_program` variant, so use the former for the sake of consistency.
> cl_khr_kernel_clock: use create_single_kernel_helper

- test_conformance/api/CMakeLists.txt
- test_conformance/api/main.cpp
- test_conformance/api/negative_queue.cpp
- test_conformance/api/procs.h
Test that verifies `CL_INVALID_QUEUE_PROPERTIES` is returned from `clCreateCommandQueue`, `clCreateCommandQueueWithProperties`, and `clCreateCommandQueueWithPropertiesKHR` to match spec wording
> CL_INVALID_QUEUE_PROPERTIES if values specified in properties are valid but are not supported by the device.
> Negative test for CL_INVALID_QUEUE_PROPERTIES

- test_conformance/generic_address_space/CMakeLists.txt
- test_conformance/generic_address_space/atomic_tests.cpp
- test_conformance/generic_address_space/main.cpp
The atomic operations are tested with generic pointers but in a way where the compiler can infer the original pointer address space. This commit adds tests specifically for the case where the compiler cannot make inferences.
Test that the correct address is used with atomics when the address is group variant and invariant.
> Add special test for generic address space atomics

- .github/workflows/presubmit.yml
- check-format.sh
Default version coming with Ubuntu 22.04 that the CI now uses.
> Bump clang-format version to 14

- test_conformance/events/test_event_dependencies.cpp
clGetDeviceIDs 'num_devices' output parameter is described as:
> num_devices returns the number of OpenCL devices available that match device_type.
but the _test_events out_of_order_event_waitlist_multi_queue_multi_device_ test expects that after calling:
`clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, 2, two_device_ids, &number_returned);`
the content of number_returned needs to be 2, but it should be valid to return a larger number.
> Fixed incorrect usage of clGetDeviceIDs num_devices

- test_conformance/spirv_new/test_decorate.cpp
test_decorate was checking for half-precision NAN incorrectly, calling cl_half_from_float where cl_half_to_float was intended, causing a wrong expected result.
test_decorate was also printing the expected and actual results reversed, printing "got -1, want 0", when our implementation already returned 0.
> spirv_new: fix test_decorate.

- test_conformance/extensions/cl_khr_semaphore/CMakeLists.txt
- test_conformance/extensions/cl_khr_semaphore/main.cpp
- test_conformance/extensions/cl_khr_semaphore/procs.h
- test_conformance/extensions/cl_khr_semaphore/semaphore_base.h
- test_conformance/extensions/cl_khr_semaphore/test_semaphores_negative_wait.cpp
According to work plan from https://github.com/KhronosGroup/OpenCL-CTS/issues/1691
After consultations with @bashbaug I skipped this case:
`CL_INVALID_VALUE if any of the semaphore objects specified by sema_objects requires a semaphore payload and sema_payload_list is NULL`
> Added new cl_khr_semaphore tests to verify clEnqueueWaitSemaphoresKHR negative results

- test_conformance/spirv_new/test_decorate.cpp
The verification code assumes the hardware uses CL_HALF_RTE, which causes a mismatch computation results when the hardware uses RTZ. Fix to use the hardware's default rounding mode.
> spirv_new: fix test_decorate to use the device's default rounding

- test_conformance/printf/util_printf.cpp
We've had a couple of bugs inside mesa/rusticl processing %% correctly. I've added those cases locally to make sure all corner cases are properly handled.
> Extend printf tests with more %% corner cases

- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_barrier.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_copy_image.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_svm_mem.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_nd_range_kernel.cpp
- when calling command buffer APIs, test with `command_queue != NULL` should return `CL_INVALID_VALUE` only if the device doesn't support `cl_khr_command_buffer_multi_device` (added `Skip`)
- some tests enqueued commands with multiple invalid arguments, e.g. `clCommandCopyImageToBufferKHR` with two images and invalid sync points. AFAIK the order of argument checking is not defined, so implementation can return any valid error value for such API calls, but the tests assumed only one particular error would be returned. Fix the API calls to be unambiguous.
> fix bugs in negative command_buffer tests

- test_conformance/math_brute_force/README.txt
Half precision math functions are fully tested as of #1975.
> math_brute_force: update README.txt for half testing

- test_conformance/api/test_kernel_arg_multi_setup.cpp
- test_conformance/api/test_queries.cpp
- test_conformance/api/test_wg_suggested_local_work_size.cpp
The removed macros were never used.
Use the more common `ARRAY_SIZE` macro instead of defining an identical `NELEMS` macro.
> [NFC] api: remove duplicate and unused macros

- test_conformance/images/kernel_read_write/test_iterations.cpp
- test_conformance/images/kernel_read_write/test_read_1D.cpp
- test_conformance/images/kernel_read_write/test_read_1D_array.cpp
- test_conformance/images/kernel_read_write/test_read_2D_array.cpp
- test_conformance/images/kernel_read_write/test_write_1D.cpp
- test_conformance/images/kernel_read_write/test_write_1D_array.cpp
- test_conformance/images/kernel_read_write/test_write_2D_array.cpp
- test_conformance/images/kernel_read_write/test_write_3D.cpp
- test_conformance/images/kernel_read_write/test_write_image.cpp
* Printing of a `size_t` which requires the `%zu` specifier.
* Printing of 64-bit values which is now done using the `PRI*64` macros to ensure portability across 32 and 64-bit builds.
* Calling log_error with a format string of `"%f %f %f %f"` but specifying only three arguments.
> image_streams: fix -Wformat warnings

- test_conformance/computeinfo/main.cpp
Even on the common code path (i.e., no error paths taken), test_computeinfo failed to release its allocated memory, preventing a clean run with LeakSanitizer.
> computeinfo: fix memory leak

- test_conformance/extensions/cl_khr_external_semaphore/CMakeLists.txt
- test_conformance/vulkan/CMakeLists.txt
The `vulkan-wrapper` helper library's purpose is to eliminate the need to link targets directly to Vulkan, and load it dynamically instead at runtime, using `dlopen` and `LoadLibrary`.
Remove the direct linking of the Vulkan library from targets that link to `vulkan-wrapper`.
Fixes #1999
> Drop linking Vulkan directly

- presubmit.sh
Instead of selecting an arbitrary number for the number of parallel build jobs, use CMake's `--parallel` option instead.
Option was introduced in version 3.12, GitHub runners currently use CMake version 3.29.6 so this is supported.
Fixes #2003
> Use the `--parallel` build option in CI workflows

- test_conformance/math_brute_force/function_list.cpp
clang-format has already been disabled here.  Make the function list a bit easier to read.  Make the currently commented out functions stand out better on a line of their own.
> [NFC] math_brute_force: reformat function list manually

- test_conformance/printf/test_printf.cpp
Since GCC 13 some headers are no longer included transitively through C++ Standard Library headers.
> printf: add missing cstdint include

- test_conformance/computeinfo/main.cpp
The computeinfo test already checks that the cl_khr_fp16 extension is available before querying `CL_DEVICE_HALF_FP_CONFIG`, but never actually made the `CL_DEVICE_HALF_FP_CONFIG` query.
> computeinfo: add CL_DEVICE_HALF_FP_CONFIG

- test_conformance/math_brute_force/unary_float.cpp
The `skipTestingRelaxed` check suffers the following problems:
- The use of `skipTestingRelaxed` in the `if` seems reversed: when skipping correctness testing using the `-l` command line option, this variable causes correctness testing to be run for relaxed-mode `tan` regardless.
- Accuracy testing should only be skipped for derived `tan` implementations.  Non-derived `tan` implementations must still be tested for accuracy, so the condition for setting the `skipTestingRelaxed` variable is incomplete.
- It is unclear why only `tan` is conditionalized here.  There are other functions such as `tanpi` for which one would expect identical behaviour.
The actual skipping of accuracy checks for derived implementations happens in `Test()`, so just remove `skipTestingRelaxed` as it does not seem to …
> math_brute_force: remove spurious tan skip check

- test_conformance/printf/util_printf.cpp
> [printf]: input value should be exactly representable as 32-bit float

- test_conformance/printf/util_printf.cpp
> [printf] Test empty format string, and empty arg string

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/CMakeLists.txt
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_work_groups.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/procs.h
Added new tests for CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR with mutable dispatch according to this test plan https://github.com/KhronosGroup/OpenCL-CTS/issues/1897
> Added new tests for CL_MUTABLE_DISPATCH_ASSERT_NO_ADDITIONAL_WORK_GROUPS_KHR flag with mutable dispatch

- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_float.cpp
- test_conformance/math_brute_force/binary_two_results_i_half.cpp
- test_conformance/math_brute_force/i_unary_double.cpp
- test_conformance/math_brute_force/i_unary_float.cpp
- test_conformance/math_brute_force/i_unary_half.cpp
- test_conformance/math_brute_force/mad_double.cpp
- test_conformance/math_brute_force/mad_float.cpp
- test_conformance/math_brute_force/mad_half.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/ternary_half.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
- test_conformance/math_brute_force/unary_two_results_half.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_float.cpp
- test_conformance/math_brute_force/unary_two_results_i_half.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
- test_conformance/math_brute_force/unary_u_float.cpp
- test_conformance/math_brute_force/unary_u_half.cpp
The math_brute_force test has a link-check-only mode to quickly test if all math functions are present.
In link-check-only mode, most tests return immediately after kernel compilation, but some tests also run the kernel and read back the result data before returning.  Running the kernels takes a lot more time, defeating the purpose of the `-l` mode.
Break out at the start of the main `for` loops in link-check-only mode instead of returning directly, so that each test can still log its trailing message (in most cases just a `\n`).
> math_brute_force: skip all enqueues in -l mode

- test_conformance/math_brute_force/function_list.cpp
Skip the correctly rounded divide (divide_cr) and sqrt (sqrt_cr) tests for fp16 and fp64.
The corresponding build option to enable correctly rounded divide and sqrt is named `-cl-fp32-correctly-rounded-divide-sqrt` and the description refers only to "single precision floating-point", so this option should not apply to fp16 or fp64.
The specification states that fp16 and fp64 divide and sqrt must be correctly rounded for the full profile, without needing any additional build options.  This is already tested by the regular divide and sqrt tests.  For the embedded profile the ULP requirement is non-zero, but there is no build option to request a correctly rounded implementation anyway.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/1901 .
Relates to …
> math_brute_force: only test correctly rounded divide/sqrt for fp32

- test_conformance/api/main.cpp
- test_conformance/api/procs.h
- test_conformance/api/test_queue_properties_queries.cpp
Add test to check that clSetCommandQueueProperty
successfully changes command queue properties.
Fixes #904
> Add clSetCommandQueueProperty test

- test_common/harness/deviceInfo.cpp
- test_common/harness/deviceInfo.h
- test_conformance/allocations/allocation_functions.cpp
- test_conformance/allocations/main.cpp
- test_conformance/api/test_api_min_max.cpp
- test_conformance/api/test_kernels.cpp
- test_conformance/images/clGetInfo/test_1D.cpp
- test_conformance/images/clGetInfo/test_1D_2D_array.cpp
- test_conformance/images/clGetInfo/test_2D.cpp
- test_conformance/images/clGetInfo/test_3D.cpp
Some conformance tests use directly the size returned by the runtime
for max memory size to allocate buffers.
This doesn't leave enough memory for the system to run the tests.
> Limit buffers sizes to leave some memory for the platform

- test_conformance/printf/util_printf.cpp
according to work plan for issue #1058
> Added few missing format cases for zero and blank space padding

- test_common/harness/conversions.cpp
- test_common/harness/conversions.h
- test_conformance/basic/test_explicit_s2v.cpp
- test_conformance/basic/test_vector_creation.cpp
- test_conformance/commonfns/test_base.h
Basic explicit_s2v:
The verification step was always using round to even when converting a float to half even for round to zero cores.
Commonfns degrees:
The verification step was only taking into account infinities and not values that over/underflow. This resulted in an incorrect error calculation. E.g:
double cpu_result = 175668.85998711039;
cl_half gpu_result = 31743; // this is 65504 when converting to float, we overflowed.
float error = (cpu_result - gpu_result) * some_factor;
The fix adds the check if( (cl_half) reference == test ) before calculating the error.
> Fixes for basic explicit_s2v and commonfns degrees for cl_half

- test_conformance/basic/test_imagearraycopy.cpp
Use format aware memory comparison instead of memcmp.
> [basic] Enable image format aware scanline comparison.

- test_conformance/printf/util_printf.cpp
The length modifier is required with a vector specifier.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/2039
> printf: add missing vector length modifiers

- test_conformance/math_brute_force/ternary_float.cpp
- test_conformance/math_brute_force/ternary_half.cpp
- test_conformance/math_brute_force/unary_two_results_float.cpp
windows default stack size is 1M, BUFFER_SIZE is 2 * 1024 * 1024, use array with BUFFER_SIZE elemets on stack can exceed available stack size limits.
> [NFC] Use std::vector to store large size array.

- test_conformance/api/test_api_consistency.cpp
- test_conformance/api/test_api_min_max.cpp
- test_conformance/api/test_mem_object_info.cpp
- test_conformance/api/test_mem_object_properties_queries.cpp
- test_conformance/api/test_pipe_properties_queries.cpp
- test_conformance/api/test_platform.cpp
- test_conformance/api/test_queries.cpp
- test_conformance/api/test_queue_properties_queries.cpp
* Printing of a `size_t` which requires the `%zu` specifier.
* Printing of `cl_long`/`cl_ulong` which is now done using the `PRI*64` macros to ensure portability across 32 and 64-bit builds.
> api: fix -Wformat warnings

- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
An implementation may not support exportable semaphore, subtests available in cl_khr_external_semaphore assumes support for exportable semaphore, resulting in failure on such implementation. Allow implementations to use importable semaphore in such cases.
> Fix external semaphore test when exportability is not supported

- test_conformance/math_brute_force/binary_half.cpp
- test_conformance/math_brute_force/binary_i_half.cpp
- test_conformance/math_brute_force/common.h
- test_conformance/math_brute_force/macro_binary_half.cpp
- test_conformance/math_brute_force/macro_unary_half.cpp
- test_conformance/math_brute_force/unary_half.cpp
The various forms of `TestInfoBase` have many members in common, so avoid duplicating the struct definition and move it to `common.h`.
Provide a description and initializer for every struct member, and drop initializations done with `memset`.
> [NFC] math_brute_force: move TestInfoBase to common.h

- test_common/harness/compat.h
Include `cmath` instead of `math.h` in C++ mode under MSVC, to avoid
build errors inside the header.  Ideally we would not condition this
on `_MSC_VER`, but issue 1833 currently prevents doing so.
> Fix Windows build with MSVC 19.41

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_basic.h
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_full_dispatch.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_global_offset.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_global_size.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_image_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_iterative_arg_update.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_local_size.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_multiple_dispatches.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_overwrite_update.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_simultaneous.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_work_groups.cpp
CTS changes to reflect the spec changes merged in https://github.com/KhronosGroup/OpenCL-Docs/pull/1045 and requires header updates from https://github.com/KhronosGroup/OpenCL-Headers/pull/245
Tested using OCK implementation from https://github.com/codeplaysoftware/oneapi-construction-kit/pull/501
> Array based clUpdateMutableCommandsKHR changes

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_full_dispatch.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_image_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_info.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_simultaneous.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_work_groups.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_out_of_order.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_barrier.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_base.h
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_copy.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_fill.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_barrier.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_copy.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_copy_image.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_fill.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_svm_mem.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_nd_range_kernel.cpp
This is an update to #2050, with updates from the main branch.
> Add properties parameter to all command-buffer commands (update)

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_global_offset.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_global_size.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_image_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_local_size.cpp
Printing of a `size_t` requires the `%zu` specifier.
> cl_khr_mutable_dispatch: fix -Wformat warnings

- test_common/harness/errorHelpers.cpp
Add cases for `CL_INCOMPATIBLE_COMMAND_QUEUE_KHR` and `CL_INVALID_SYNC_POINT_WAIT_LIST_KHR`.
> Extend `IGetErrorString()`

- test_conformance/common/vulkan_wrapper/vulkan_utility.cpp
- test_conformance/common/vulkan_wrapper/vulkan_utility.hpp
- test_conformance/vulkan/CMakeLists.txt
- test_conformance/vulkan/shaders/CMakeLists.txt
- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
- test_conformance/vulkan/test_vulkan_interop_image.cpp
fixes #2040 
* Compiles the Vulkan SPIR-V files in a directory based off of CMAKE_CURRENT_BINARY_DIR.
* Changes the search path for the Vulkan SPIR-V files to this directory rather than a semi-arbitrary set of directories.
> compile Vulkan SPIR-V shaders in CMAKE_CURRENT_BINARY_DIR

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_arguments.cpp
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_simultaneous.cpp
fixes a few minor issues introduced by #1984.
edit: Tested with the updated command buffer emulation layer on a device that supports out-of-order queues and SVM and all of the `test_cl_khr_mutable_dispatch` tests pass.
> fix a few array-based mutable command buffer issues

- test_conformance/math_brute_force/CMakeLists.txt
All of these are already set in the top-level `CMakeLists.txt` nowadays, so no need to repeat them in the test's own `CMakeLists.txt`.
> [NFC] math_brute_force: remove warning options

- test_common/gl/setup_osx.cpp
I found an issue about CTS running gl / CL-GL interop case issue, I found glutInit double called in CTS CLGL test case code, which will lead to an error:
freeglut (./test_gl): illegal glutInit() reinitialization attempt
root cause is in: test_conformance/gl/main.cpp:343
if (glEnv->Init(&argc, (char **)argv, CL_TRUE))
the glEnv->Init has already called in same file line:260, the function glutInit in glEnv->Init can not be called twice, then a error will occur although all the gl / CLGL cases are passed. Then in the full quick CTS running it will appear:
(12-Jul 03:54:01)     BEGIN  OpenCL-GL Sharing                       : 
PASSED sub-test.
PASSED 23 of 23 tests.
(12-Jul 04:01:48)     FAILED OpenCL-GL Sharing                       : (467s, test  34/53)
Although all the gl/CLGL cases are …
> Add flag to track wether glut has been initialized

- test_conformance/images/kernel_read_write/test_loops.cpp
'./test_image_streams test_mipmaps CL_FILTER_NEAREST' already skips many tests, but doesn't do so for cl_ext_image_raw10_raw12, causing it to fail.
Add a check similar to how it is done in the other tests already.
On a device which doesn't support mipmap'd access:
W/o fix
```
./test_image_streams test_mipmaps CL_FILTER_NEAREST
...
1Darray passed
2Darray...
-----------------------------------------------------
This device does not support cl_khr_mipmap_image.
Skipping mipmapped image test. 
-----------------------------------------------------
-----------------------------------------------------
This device does not support cl_khr_mipmap_image.
Skipping mipmapped image test. 
-----------------------------------------------------
2Darray passed
cl_image_requirements_size_ext_negative... …
```
> Skip testing mipmaps if extension is not available

- test_conformance/images/kernel_image_methods/test_1D_buffer.cpp
Buffer size needs to be greater than or equal the image row pitch which was not the case.
> Fix 1D buffer image tests

- test_conformance/printf/test_printf.h
- test_conformance/printf/util_printf.cpp
Due to change request from #2037
> Correction for printing long type variables in 32-bit system

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_event_sync.cpp
- test_conformance/generic_address_space/main.cpp
fixes several issues:
* `generic_address_space` test: add check for program scope variables. The test uses both generic AS and program-scope variables, however it only checked the generic-AS presence in `clGetDeviceInfo`.
* `compiler/test_compiler_defines_for_extensions.cpp`: add `cl_khr_command_buffer_multi_device` to the list of recognized extensions
* `command_buffer_event_sync.cpp`: add delays for testing `clSetEventCallback` - according to specification, these can be executed asynchronously (in a separate thread) by the OpenCL implementation, hence the event callback is not quaranteed to be called before `clFinish()` returns. Existing test `events/test_callbacks.cpp` also waits for callback with loops of usleep.
* `images/kernel_image_methods/test_1D_buffer.cpp`: fix allocation size …
> fix generic_address_space, command_buffer_event_sync, test_compiler and images/test_1D_buffer

- test_conformance/math_brute_force/binary_two_results_i_half.cpp
Comparing test (of type cl_half) with 0.0f is incorrect because cl_half is a typedef of uint16_t (or unsigned short in c)
> bruteforce: Fix comparions of unsigned shorts with 0.0f

- test_conformance/common/vulkan_wrapper/vulkan_wrapper.cpp
Increase Vulkan version to 1.1, which is required to support vkGetBufferMemoryRequirements2.
> vulkan: Use Vulkan 1.1

- test_conformance/api/test_api_min_max.cpp
before: Filling constant buffer with 553805440 cl_ints (-2079745536 bytes).
after: Filling constant buffer with 553805440 cl_ints (2215221760 bytes).
> Fix printing in test_api_min_max

- test_conformance/math_brute_force/ternary_half.cpp
Replace the occurrences of 0.0f == test' with 0.0f == HTF(test)'. The types of 0.0f and test are not the same, so the equality comparison will get undesired result when the test represents a -0.0h (i.e., test is 32768=0x8000). In this situation, 0.0f == test will be false, but 0.0f == HTF(test) will be true.
Revise each if-statement to match the OpenCL s7.5.3 Item 4, specifically modify to check that the result is subnormal instead of checking that it is zero. "If the result of 3. is a sub-normal before rounding, the result may be flushed to zero"
> bruteforce: Fix retry logic for cases with subnormals

- test_conformance/extensions/cl_khr_command_buffer/command_buffer_event_sync.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_test_barrier.cpp
- test_conformance/thread_dimensions/test_thread_dimensions.cpp
some fixes we've been carrying in our CTS fork:
* fix UB in `command_buffer_event_sync.cpp`: enqueue of two commands in two separate queues, with both using the same buffer argument, and no synchronization between the commands.
* fix UB in `command_buffer_test_barrier.cpp`: missing synchronization between zeroing command and command-buffer using two separate queues
* make `test_thread_dimensions.cpp` thread-safe to avoid spurious errors.
> a few fixes (thread safety & cl_khr_command_buffer UB)

- test_conformance/extensions/cl_khr_semaphore/test_semaphores_negative_wait_signal.cpp
Following the re-enablement of narrowing warnings, this fixes a compilation error when running the `ubuntu 22.04 arm` GitHub action.
> Fix warning now treated as error

- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
Vulkan descriptors are being programmed incorrectly, use fix from 1676 in other subtest
> vulkan: Propagate fix to multiImport diffCtx

- test_conformance/vulkan/shaders/CMakeLists.txt
- generate shader files in VULKAN_TEST_RESOURCES directory
- allows for outside CMakeLists to specify arbitrary destination
> vulkan: Choose where Shaders are generated

- test_conformance/extensions/cl_khr_semaphore/test_semaphores_queries.cpp
Looks like https://github.com/KhronosGroup/OpenCL-CTS/pull/2063 has a "narrowing" warning that is now treated as an error and is hence causing CI builds to fail.
Applies the same fix as https://github.com/KhronosGroup/OpenCL-CTS/pull/2107 to fix this warning.
> fixes a narrowing warning (treated as an error) affecting some platforms

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_full_dispatch.cpp
The test is missing clFinish after clEnqueueSVMUnmap. Add clFinish after clEnqueueSVMUnmap.
> Fix bug in `mutable_command_full_dispatch`

- test_conformance/conversions/basic_test_conversions.cpp
Commit b6941b6c ("Add fp16 testing to conversions and bruteforce (#1975)", 2024-06-18) introduced a behavioural change for non-half tests.  The `-cl-denorms-are-zero` option could be added for non-half tests such as `char_rtn_float` even when `gForceFTZ` was `false`.  Fix the condition by also taking the input and output types into account.
> conversions: fix condition for adding -cl-denorms-are-zero

- test_conformance/spirv_new/CMakeLists.txt
- test_conformance/spirv_new/spirvInfo.hpp
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fadd_int.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fadd_int.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fadd_uint.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fadd_uint.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fmul_int.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fmul_int.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fmul_uint.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fmul_uint.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fnegate_int.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fnegate_int.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fshiftleft_int.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fshiftleft_int.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fshiftleft_uint.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fshiftleft_uint.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fsub_int.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fsub_int.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fsub_uint.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.4/no_integer_wrap_decoration_fsub_uint.spvasm64
- test_conformance/spirv_new/test_no_integer_wrap_decoration.cpp
This PR adds targeted testing for SPIR-V 1.4 features. Specifically, this PR adds testing for the NoSignedWrap and NoUnsignedWrap decorations.
We can reuse large parts of the testing for the `cl_khr_spirv_no_integer_wrap_decoration` extension to test the SPIR-V 1.4 feature.
> add SPIR-V 1.4 testing for no integer wrap decorations

- test_conformance/common/vulkan_wrapper/opencl_vulkan_wrapper.cpp
- test_conformance/common/vulkan_wrapper/vulkan_api_list.hpp
- test_conformance/common/vulkan_wrapper/vulkan_wrapper.cpp
- test_conformance/common/vulkan_wrapper/vulkan_wrapper.hpp
When importing a Vulkan external image, query and
pass OpenCL a row pitch if OpenCL is assuming linear for the imported external handle type.  Additionally fix a bug where OpenCL is being told to create mipmapped images at all times.
> vulkan: Use image row pitch

- test_conformance/mem_host_flags/checker_mem_host_no_access.hpp
- test_conformance/mem_host_flags/checker_mem_host_read_only.hpp
- test_conformance/mem_host_flags/checker_mem_host_write_only.hpp
In test_mem_host_flags, some events are not released. In fact, they are not used, so they can be removed altogether.
> Some events are not released in test_mem_host_flags

- test_common/harness/errorHelpers.cpp
- test_common/harness/imageHelpers.cpp
- test_common/harness/kernelHelpers.cpp
- test_conformance/images/common.cpp
- test_conformance/images/kernel_read_write/test_common.cpp
All existing tests in `test_image_streams`, that are capable of testing image formats using the `CL_UNORM_INT_2_101010_EXT` data type, do so.
> Add testing of `CL_UNORM_INT_2_101010_EXT`

- test_conformance/relationals/test_comparisons_fp.cpp
Fix a "format string is not a string literal (potentially insecure)" warning.
There is no security issue here as the format string argument is constructed using a stringstream right before.  Fix this occurrence anyway to allow enabling the warning globally.
> [NFC] relationals: fix -Wformat-security warnings

- test_conformance/vulkan/main.cpp
- read CL_DEVICE_TYPE_ when specified like other conformance tests
- reject non-GPU device types
> vulkan: accept device selection

- test_conformance/math_brute_force/binary_half.cpp
- test_conformance/math_brute_force/binary_i_half.cpp
- test_conformance/math_brute_force/binary_operator_half.cpp
- test_conformance/math_brute_force/binary_two_results_i_half.cpp
- test_conformance/math_brute_force/ternary_half.cpp
- test_conformance/math_brute_force/unary_half.cpp
- test_conformance/math_brute_force/unary_two_results_half.cpp
- test_conformance/math_brute_force/unary_two_results_i_half.cpp
- test_conformance/math_brute_force/unary_u_half.cpp
Call `getAllowedUlpError` to obtain the allowed ULP error for all of the half type (fp16) tests.  The aim is to standardise obtaining the desired ULP requirement and pave the way for adding the Embedded Profile ULP errors.
Contributes to https://github.com/KhronosGroup/OpenCL-CTS/issues/867
Contributes to https://github.com/KhronosGroup/OpenCL-CTS/issues/1685
> [NFC] math_brute_force: use getAllowedUlpError for half

- test_conformance/subgroups/test_subgroup_clustered_reduce.cpp
Rounding up the clusters_results size to avoid out of bounds access when subgroup_size is not a multiple of cluster_size.
> Fix for out of bounds access

- test_conformance/api/test_api_consistency.cpp
When cl_khr_fp16 is not supported, this property is not available.
Note that the spec is different for
CL_DEVICE_{PREFERRED,NATIVE}_VECTOR_WIDTH_HALF: those properties are always available and return 0 if cl_khr_fp16 is not supported, so those checks are left as is.
> Fix check for CL_DEVICE_HALF_FP_CONFIG.

- test_conformance/extensions/cl_khr_semaphore/test_semaphores_negative_getinfo.cpp
- test_conformance/extensions/cl_khr_semaphore/test_semaphores_queries.cpp
Add a `format` parameter to the macro, to be able to specify how to print the expected and actual parameter values.
> cl_khr_semaphore: fix -Wformat warnings

- test_common/harness/parseParameters.cpp
- test_conformance/api/test_clone_kernel.cpp
- test_conformance/api/test_queue_hint.cpp
- test_conformance/api/test_queue_properties.cpp
- test_conformance/gl/test_image_methods.cpp
- test_conformance/gl/test_images_1D.cpp
- test_conformance/gl/test_images_1Darray.cpp
- test_conformance/gl/test_images_2D.cpp
- test_conformance/gl/test_images_2Darray.cpp
- test_conformance/gl/test_images_3D.cpp
- test_conformance/gl/test_images_depth.cpp
- test_conformance/gl/test_images_multisample.cpp
- test_conformance/spirv_new/main.cpp
Removes `using namespace std` and adds `std::` explicitly instead, which is usually on calls to `min`.
This is generally best practice, and it also might be helpful when there are the same function names in the std namespace and in the global namespace (e.g. #1833).
> remove using namespace std and use std namespace explicitly

- test_conformance/images/kernel_image_methods/test_1D_buffer.cpp
Image height is initialized to 0.  But the size calculation should assume a height of 1.
> kernel_image_methods: Fix size checks in 1Dbuffer case

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_work_groups.cpp
Current class wrapper of the CTS test framework allows getting the pointer of the private member object. This puts the object at risk of losing its original value if the pointer gets reassigned, causing a memory leak and potentially other problems.
This happens to the "clMemWrapper kernel" used by
mutable_command_work_groups tests, where the "clMemWrapper kernel" gets initialised by the default basic setup function and then it gets reassigned by the build_program_create_kernel_helper() helper  function through pointer.
This patch fixes this issue by updating mutable_command_work_groups tests: instead of calling basic setup function and then initialise the "clMemWrapper kernel" object again in the helper function, it now overrides the basic setup function to make sure the "clMemWrapper …
> Fix CTS mutable_dispatch memory leak

- test_conformance/vulkan/test_vulkan_api_consistency_for_1dimages.cpp
- test_conformance/vulkan/test_vulkan_api_consistency_for_3dimages.cpp
- negative testing for semaphore functions is accomplished in semaphore tests, as well as create image in the api test
> vulkan: Remove redundant negative testing

- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
When creating a CL semaphore object from a Vulkan semaphore one, we explicitly pass `-1` as the file descriptor value in the case of `VULKAN_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD`. According to the CL specification:
>     The special value -1 for fd is treated like a valid sync file
>     descriptor referring to an object that has already signaled. The
>     import operation will succeed and the semaphore will have a
>     temporarily imported payload as if a valid file descriptor had
>     been provided.
The test currently checks that the semaphore payload is unsignalled, unconditionally, which is incorrect.
Changed the test to check for the correct expected payload value.
> Fix payload value query for external semaphores

- test_common/harness/compat.h
Fixes #1833 according to task description.
> Corrected build under msvc compiler #1833

- test_conformance/extensions/cl_khr_external_semaphore/main.cpp
- test_conformance/extensions/cl_khr_external_semaphore/procs.h
- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
Re-enable a disabled external semaphore test.
Delete obsolete subtests that remain in comments.
> Re-enable simple_semaphore_2

- test_conformance/basic/test_arrayimagecopy.cpp
- test_conformance/basic/test_imagearraycopy.cpp
This change refactors the following files:
1. test_imagearraycopy.cpp
2. test_arrayimagecopy.cpp
The purpose of refactoring is to allow passing different buffer and image flags to the test function as well as passing customisable test functions.
> Refactor test copy from and to image to buffer

- test_common/harness/kernelHelpers.h
None of these are referenced anywhere in the code, so remove them.
> [NFC] kernelHelpers: remove unused macros and prototypes

- test_conformance/gl/test_images_write_common.cpp
- test_conformance/gl/test_renderbuffer.cpp
> Removed usage of half types in CTS gl tests

- test_common/harness/testHarness.cpp
Some platforms (Windows in our case) seem to need this.
> printf: add fflush(stdout) at the end

- test_conformance/SVM/test_enqueue_api.cpp
- test_conformance/allocations/allocation_execute.cpp
- test_conformance/device_partition/test_device_partition.cpp
- test_conformance/images/clCopyImage/test_copy_1D.cpp
- test_conformance/images/samplerlessReads/test_read_1D_array.cpp
- test_conformance/images/samplerlessReads/test_read_3D.cpp
- test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.cpp
- test_conformance/pipes/test_pipe_info.cpp
- test_conformance/relationals/test_shuffles.cpp
- test_conformance/spirv_new/test_get_program_il.cpp
- test_conformance/thread_dimensions/test_thread_dimensions.cpp
- test_conformance/vectors/structs.cpp
- test_conformance/vectors/test_step.cpp
- test_conformance/vectors/test_vec_align.cpp
- test_conformance/workgroups/test_wg_all.cpp
- test_conformance/workgroups/test_wg_any.cpp
test_copy_1D.cpp: num_mip_levels is a cl_uint, so don't cast and just print using `%u`.
test_pipe_info.cpp: arg_type_qualifier is a 64-bit wide bitfield, so print in hexadecimal format using the correct length modifier.
test_device_partition.cpp: it is not clear what the bit width of `cl_device_partition_property` should be, so cast the operands to align with the format specifiers.
> Fix various Wformat warnings

- test_conformance/spirv_new/spirv_asm/branch_conditional.spvasm32
- test_conformance/spirv_new/spirv_asm/branch_conditional.spvasm64
- test_conformance/spirv_new/spirv_asm/branch_conditional_weighted.spvasm32
- test_conformance/spirv_new/spirv_asm/branch_conditional_weighted.spvasm64
- test_conformance/spirv_new/spirv_asm/phi_2.spvasm32
- test_conformance/spirv_new/spirv_asm/phi_2.spvasm64
- test_conformance/spirv_new/spirv_asm/phi_3.spvasm32
- test_conformance/spirv_new/spirv_asm/phi_3.spvasm64
- test_conformance/spirv_new/spirv_asm/phi_4.spvasm32
- test_conformance/spirv_new/spirv_asm/phi_4.spvasm64
- test_conformance/spirv_new/spirv_asm/select_if_dont_flatten.spvasm32
- test_conformance/spirv_new/spirv_asm/select_if_dont_flatten.spvasm64
- test_conformance/spirv_new/spirv_asm/select_if_flatten.spvasm32
- test_conformance/spirv_new/spirv_asm/select_if_flatten.spvasm64
- test_conformance/spirv_new/spirv_asm/select_if_none.spvasm32
- test_conformance/spirv_new/spirv_asm/select_if_none.spvasm64
- test_conformance/spirv_new/test_op_branch_conditional.cpp
- test_conformance/spirv_new/test_op_phi.cpp
- test_conformance/spirv_new/test_op_selection_merge.cpp
The following tests under `spirv_new`:
* `op_branch_conditional`
* `op_phi`
* `op_selection_merge`
were using randomly generated `cl_int` values, and storing the difference between them as a `cl_int`. If one of the generated values is negative and large enough, while the other is positive and large enough, the difference then becomes a larger value that cannot be represented using `cl_int`.
Switch the tests to use `cl_uint` instead, and update the relevant spvasm{32,64} files to use `OpULessThan` instead of `OpSLessThan`.
> Use `cl_uint` in some SPIR-V tests to avoid UB

- .github/workflows/presubmit.yml
- presubmit.sh
On Ubuntu, use the system's package manager, `apt`, to download and install the cross-compilers for Arm and AArch64. This replaces downloading the compilers as tarballs.
To ensure that the correct version of the compiler is used when calling one without the version suffix, e.g. `aarch64-linux-gnu-gcc`, use `update-alternatives`.
On Linux, the compilers for `x86_64`, `arm`, and `aarch64` will now correctly use the filesystem root as their sysroots, i.e. `/usr/include` will be used when searching for headers, instead of each compiler providing its own.
> Use the system package manager to install cross-compilers

- .github/workflows/presubmit.yml
- presubmit.sh
Support building for Android on Arm and AArch64 platforms.
Modify the build matrix to add to new variations. Both variants download, extract and setup the Android Native Development Kit (NDK) on a Linux runner. Each variant specifies a `android_arch_abi`, which is passed to CMake during configuration as its `CMAKE_ANDROID_ARCH_ABI` option.
The CMake toolchain file provided by the NDK is used when building for Android. The NDK version used is r27c, which is the latest Long-Term Support (LTS) version. `ANDROID_PLATFORM` is intentionally not set, so the NDK can default to the minimum supported version, which is 21. The compiler (Clang) version used by this NDK is 18.0.3.
The NDK ships with its own sysroot, which has the Linux kernel headers of version 6.8.0, or `LINUX_VERSION_CODE 395264`. …
> Add Android to the CI build matrix

- test_conformance/SVM/common.h
- test_conformance/SVM/main.cpp
- test_conformance/SVM/test_allocate_shared_buffer.cpp
- test_conformance/SVM/test_allocate_shared_buffer_negative.cpp
- test_conformance/SVM/test_byte_granularity.cpp
- test_conformance/SVM/test_cross_buffer_pointers.cpp
- test_conformance/SVM/test_enqueue_api.cpp
- test_conformance/SVM/test_fine_grain_memory_consistency.cpp
- test_conformance/SVM/test_fine_grain_sync_buffers.cpp
- test_conformance/SVM/test_migrate.cpp
- test_conformance/SVM/test_pointer_passing.cpp
- test_conformance/SVM/test_set_kernel_exec_info_svm_ptrs.cpp
- test_conformance/SVM/test_shared_address_space_coarse_grain.cpp
- test_conformance/SVM/test_shared_address_space_fine_grain.cpp
- test_conformance/SVM/test_shared_address_space_fine_grain_buffers.cpp
- test_conformance/SVM/test_shared_sub_buffers.cpp
Switches the SVM tests to the new test registration framework.
The first commit is the best to review and contains the actual changes.  The second commit purely has formatting changes.
Note that several of these changes were a bit more than mechanical because many of the SVM tests create a new context vs. using the context provided by the harness and passed to each test function.  The previous code named the context provided by the harness differently, and hence could use the name "context" in each test function, but with the new test registration framework this is no longer possible.  Instead, I am creating the new context using the name "contextWrapper" and then assigning it to the "context" passed to the test function, which seems like the best way to avoid using the wrong context …
> switch SVM tests to the new test registration framework

- test_conformance/buffers/test_sub_buffers.cpp
- test_conformance/compiler/test_build_helpers.cpp
- test_conformance/compiler/test_compile.cpp
- test_conformance/contractions/contractions.cpp
- test_conformance/conversions/test_conversions.cpp
- test_conformance/device_partition/test_device_partition.cpp
- test_conformance/images/clCopyImage/test_copy_generic.cpp
- test_conformance/images/clFillImage/test_fill_generic.cpp
- test_conformance/images/kernel_read_write/test_common.h
- test_conformance/images/kernel_read_write/test_iterations.cpp
- test_conformance/images/kernel_read_write/test_write_1D.cpp
- test_conformance/images/kernel_read_write/test_write_1D_array.cpp
- test_conformance/images/kernel_read_write/test_write_2D_array.cpp
- test_conformance/images/kernel_read_write/test_write_3D.cpp
- test_conformance/images/kernel_read_write/test_write_image.cpp
- test_conformance/multiple_device_context/test_multiple_contexts.cpp
- test_conformance/multiple_device_context/test_multiple_devices.cpp
Printing of a `size_t` requires the `%zu` specifier.
This fixes occurrences where the previous wrong specifier appears to work in a typical 64-bit build, but causes a Wformat warning in 32-bit builds.
> Fix more Wformat warnings related to size_t

- .github/workflows/presubmit.yml
Updates CI to use headers with support for the cl_khr_unified_svm extension in the cl_khr_unified_svm branch.
Note that this PR targets the cl_khr_unified_svm branch, not the main branch.
> update CI to use the cl_khr_unified_svm headers

- test_conformance/basic/test_arrayimagecopy.cpp
- test_conformance/basic/test_imagearraycopy.cpp
This change addresses a free function mis-match issue where `delete` is used to free memory allocated via `malloc` within `create_random_data` and in the test function.
The change involves the following tests:
1. arrayimagecopy
2. arrayimagecopy3d
3. imagearraycopy
4. imagearraycopy3d
This should address #2173
> Fix using incorrect free function in arrayimagecopy and imagearraycopy basic tests' unique_ptr

- test_conformance/images/clCopyImage/test_copy_generic.cpp
This change fixes the following issues when running `clCopyImage` test with `use_pitches` flag for 1D buffer images.
1. Query device CL version using `get_device_cl_version` rather than using `CL_DEVICE_VERSION`. Previously, using `char` may not be enough to store the return value.
2. Pass `host_ptr` to `clCreateBuffer` when creating the buffer for the 1D image. `host_ptr` may not be `nullptr` if use_pitches flag is used. Also, `buffer_flags` will contain `CL_MEM_USE_HOST_PTR` which requires a host pointer to be passed.
3. Conditionally use the `host_ptr` when calling `clCreateImage`, it will not be used with 1D image buffer. This is made to align with the spec, in which if `mem_flags` has `CL_MEM_USE_HOST_PTR` a host pointer must be present, but if the memory flag is not present, host …
> Fix clCopyImage 1D buffer images tests with use_pitches flag

- test_common/harness/testHarness.h
- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
Use in cl_khr_external_semaphore suite as an example.
> Add utility macro to skip test when an extension is not supported

- test_conformance/math_brute_force/main.cpp
- to be able to have deterministic results it is useful to have a mechanism
to force the same count of workers
- this commit doesn't change the default settings but expands
functionality
Signed-off-by: Katarzyna Cencelewska <katarzyna.cencelewska@intel.com>
> add option to bruteforce test to force count of worker threads

- test_conformance/extensions/cl_khr_semaphore/test_semaphores_cross_queue.cpp
`i` is an `int`, so shouldn't use the `%zu` specifier for printing.
> semaphore: fix Wformat warning

- CMakeLists.txt
- test_conformance/basic/CMakeLists.txt
- test_conformance/c11_atomics/CMakeLists.txt
- test_conformance/commonfns/CMakeLists.txt
- test_conformance/conversions/CMakeLists.txt
- test_conformance/relationals/CMakeLists.txt
Move the global `-Wno-format` compiler option to the individual tests that still trigger Wformat warnings.  The majority of the tests now compile cleanly with `-Wformat` enabled.
> cmake: remove global -Wno-format

- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_enqueue.cpp
negative_command_buffer_enqueue_with_different_context does not need to use CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
Fix #2205
> fix negative_command_buffer_enqueue_with_different_context

- test_conformance/SVM/test_pointer_passing.cpp
The `svm_pointer_passing` test has unflushed buffer unmap commands queued, which a runtime might process after the `clSVMFree` calls at the end of the test (through implicit flushing when destroying the queues at e.g. program exit handlers).
This is only an issue when running the test with multiple devices.
However I think this was caused by a simple typo given the `clFinish` was simply in the wrong block.
> svm: finish all queues in svm_pointer_passing

- test_conformance/spirv_new/CMakeLists.txt
- test_conformance/spirv_new/spirv_asm/spv1.5/non_uniform_broadcast_dynamic_index.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.5/non_uniform_broadcast_dynamic_index.spvasm64
- test_conformance/spirv_new/spirv_asm/spv1.5/ptr_bitcast.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.5/ptr_bitcast.spvasm64
- test_conformance/spirv_new/test_spirv_15.cpp
fixes #2140 
Adds testing for SPIR-V 1.5 features:
* Adds a test for bitcasts between pointers and vectors of integers.  Note, SPIR-V 1.5 only supports bitcasts to vectors of two 32-bit integers.  Therefore, the SPIR-V 1.5 behavior will only be exercised on devices with 64-bit pointers.  The test will run on devices with 32-bit pointers, but will instead bitcast to scalars.
* Adds a test for OpGroupNonUniformBroadcast with a dynamic index.  Note, this is not an exhaustive test, and only unsigned integer types are tested, to avoid duplicating testing for cl_khr_subgroup_ballot.
> add testing for SPIR-V 1.5

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_basic.h
- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_info.cpp
As described in Issue https://github.com/KhronosGroup/OpenCL-CTS/issues/2152 we currently check the provisional extension version supported by a vendor is the same or older than a test specified version. However, it was discussed in the WG that this should be a check for equality to avoid hitting issues when a implementation tests against an older version of the CTS using a lower extension version, with API breaking changes having occurred since.
The tests for the command-buffer family of extensions are the only provisional KHR tests using this versioning check, so this PR updates all those cases to equality.
> Check command-buffer extension version for equality

- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_create.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_nd_range_kernel.cpp
It was noticed during another PR review https://github.com/KhronosGroup/OpenCL-CTS/pull/2207/files#r1903921283 that there 
was a case where the return value of a `Skip()` check was ignored, this is fixed in this PR.
I've also tracking down occurrences of derived class overriding the `Skip()` test fixture method, but not calling the parents class `Skip()` check inside of the method. I believe omitting this parent skip check wasn't intentional, it's clearer to explicitly respect the parent classes skip conditions, even if we've got away with not needing too due to the way the derived class skip conditions have been defined.
> Fix derived command-buffer Skip() checks

- test_conformance/relationals/CMakeLists.txt
- test_conformance/relationals/test_shuffles.cpp
Avoid a
```
‘%zu’ directive writing between 1 and 20 bytes into a region of size 16
```
warning by using `std::string` for `generate_shuffle_mask`.
As this fixes the last remaining Wformat warning in the relationals suite, drop the local `-Wno-format` compiler option.
> relationals: fix -Wformat warnings

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_profiling.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_create.cpp
CTS test update to match OpenCL-Doc & OpenCL-Header PRs:
* https://github.com/KhronosGroup/OpenCL-Headers/pull/265
* https://github.com/KhronosGroup/OpenCL-Docs/pull/850
Tested with https://github.com/bashbaug/SimpleOpenCLSamples/pull/126 locally using a checkout of the linked OpenCL-Headers branch
> Command-buffer query for supported queue properties

- test_conformance/math_brute_force/function_list.cpp
CTS test update to match proposed spec update https://github.com/KhronosGroup/OpenCL-Docs/issues/1278
> bruteforce: Update ULP for half-precision divide to 1.0f

- test_common/harness/errorHelpers.cpp
- test_conformance/common/vulkan_wrapper/vulkan_api_list.hpp
- test_conformance/common/vulkan_wrapper/vulkan_utility.cpp
- test_conformance/common/vulkan_wrapper/vulkan_utility.hpp
- test_conformance/vulkan/test_vulkan_api_consistency.cpp
- test_conformance/vulkan/test_vulkan_api_consistency_for_1dimages.cpp
- test_conformance/vulkan/test_vulkan_api_consistency_for_3dimages.cpp
- test_conformance/vulkan/test_vulkan_interop_buffer.cpp
- test_conformance/vulkan/test_vulkan_interop_image.cpp
This fixes three problems in `test_vulkan`:
1. One negative test is violating the OpenCL specification. A call to `clEnqueue{Wait,Signal}SemaphoresKHR` with an invalid semaphore should return `CL_INVALID_SEMAPHORE_KHR` and not `CL_INVALID_VALUE`.
> [CL_INVALID_SEMAPHORE_KHR](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_INVALID_SEMAPHORE_KHR) if any of the semaphore objects specified by sema_objects is not valid.
2. When populating the list of supported external memory handle types for Vulkan, the types are unconditionally added to the list, without checking if the device supports it or not, this fix is namely for `VULKAN_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD`.
3. If a device does not support an optional extension (that is required for a test), the test …
> Fix errors in `test_vulkan`

- test_conformance/math_brute_force/binary_half.cpp
In the half-precision `fdim` test, the original code used `CL_HALF_RTE` to convert the float result back to half, causing a mismatch in computation results when the hardware uses RTZ. Some of the examples:
```
fdim(0x365f, 0xdc63) = fdim( 0.398193f,  -280.75f)     =   281.148193f (RTE=0x5c65, RTZ=0x5c64)
fdim(0xa4a3, 0xf0e9) = fdim(-0.018112f, 10056.0f)      = 10055.981445f (RTE=0x70e9, RTZ=0x70e8)
fdim(0x1904, 0x9ab7) = fdim( 0.002449f,    -0.003279f) =     0.005728f (RTE=0x1dde, RTZ=0x1ddd)
```
Fixed this by using the hardware's default rounding mode when converting the result back to half.
> math_brute_force: fix `fdim` to use device's rounding when converting result back to half.

- test_conformance/profiling/execute_multipass.cpp
The buffer size input to the test function clEnqueueReadBuffer was incorrect, which cause segmentation  fault. And it didn't match the size for the host allocation outptr
> Fix profiling execute_multipass failure with segmentation fault

- test_conformance/printf/test_printf.cpp
- test_conformance/printf/util_printf.cpp
1. In vector test, prepare RTZ answer for RTZ rounding.
2. In mixed_format_random test, for a given float 'arg', the test previously used 'arg' directly to generate ref_str: 
```
ref_str << str_sprintf(format, arg);
```
This approach incorrectly assumes:
```
(float) arg == to_fp(to_str(arg));
```
However, this assumption fails under RTZ rounding. For example: 
```
arg = 0xC642549C 
to_str(arg) = -12437.152343f 
to_fp_rtz(-12437.152343f) = 0xC642549B (-0X1.84A936P+13) 
to_fp_rte(-12437.152343f) = 0xC642549C (-0X1.84A938P+13)
```
To address this, the reference result is now computed based on the literal float string rather than the original 'arg' value.
> printf: Fix floating-point rounding consistency for RTZ devices

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_profiling.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_queue_substitution.cpp
- test_conformance/extensions/cl_khr_command_buffer/main.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_create.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_enqueue.cpp
- test_conformance/extensions/cl_khr_command_buffer/procs.h
Update cl_khr_command_buffer tests to reflect changes from https://github.com/KhronosGroup/OpenCL-Docs/pull/1292
* Moves negative test for `CL_DEVICE_COMMAND_BUFFER_SUPPORTED_QUEUE_PROPERTIES_KHR` from command-buffer creation to enqueue.
* Moves negative test for `CL_DEVICE_COMMAND_BUFFER_REQUIRED_QUEUE_PROPERTIES_KHR` from command-buffer creation to enqueue.
* Introduces a negative test for `CL_INVALID_DEVICE` on command-buffer enqueue for new error condition in spec. Although it requires a context to be contain more than 1 device, which I'm not sure if possible in current test framework.
* Introduces a new test that created a command-buffer using a queue without the profiling property set, then enqueues the command-buffer to a queue with the profiling property set.
* Introduces a new …
> Command-buffer queue compatibility test update

- test_conformance/allocations/allocation_execute.cpp
- test_conformance/allocations/main.cpp
- Fix malloc for 'access_string' and 'kernel_string'.
- Fix typo in 'number_of_work_itmes'.
> allocations: Make buffer kernel more efficient for multiple allocations

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_create.cpp
fixes #2247 
* For the `negative_create_command_buffer_not_supported_properties` test, the only property we can check for is simultaneous use.  All other properties are part of other extensions and hence will generate `CL_INVALID_VALUE`, not `CL_INVALID_PROPERTY`.
* Checks whether the `cl_khr_command_buffer_multi_device` extension is supported when using `CL_COMMAND_BUFFER_DEVICE_SIDE_SYNC_KHR`, instead of `device_side_enqueue_support`.
* If the `cl_khr_command_buffer_multi_device` extension is NOT supported and the `CL_COMMAND_BUFFER_DEVICE_SIDE_SYNC_KHR` command buffer creation flag is used, the expected error code is `CL_INVALID_VALUE`, not `CL_INVALID_PROPERTY`.
> fix negative_create_command_buffer_not_supported_properties test

- test_common/harness/os_helpers.cpp
- test_conformance/spirv_new/CMakeLists.txt
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_fp32.spvasm32
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_fp32.spvasm64
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_fp64.spvasm32
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_fp64.spvasm64
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_int32.spvasm32
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_int32.spvasm64
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_int64.spvasm32
- test_conformance/spirv_new/spirv_asm/printf_operands_scalar_int64.spvasm64
- test_conformance/spirv_new/test_extinst_printf.cpp
Adds targeted SPIR-V tests for printf with scalar operands.  See:
* https://github.com/KhronosGroup/OpenCL-Docs/issues/1211
* https://github.com/KhronosGroup/OpenCL-Docs/pull/1236
The fp32 test is likely to be the most interesting, especially on devices that support fp64, because printf with scalar fp32 operands is not generated by default in this case with Clang and the SPIR-V LLVM Translator.
> adds SPIR-V tests for scalar printf operands

- test_conformance/vulkan/test_vulkan_api_consistency.cpp
Fixes #2153 according to issue description.
> Removed vulkan sub-tests overlapping with semaphore negative tests

- test_conformance/images/kernel_read_write/test_cl_ext_image_raw10_raw12.cpp
Images with a `CL_UNSIGNED_INT_RAW10_EXT` and `CL_UNSIGNED_INT_RAW12_EXT` data type are unnormalised, so the normalised tests with theses images are invalid and will be skipped.
> Remove unsupported raw10/raw12 tests

- test_conformance/SVM/CMakeLists.txt
- test_conformance/SVM/test_unified_svm_consistency.cpp
Adds a unified SVM consistency check test, as per the description in #2150.
Note that the target branch for this PR is the cl_khr_unified_svm branch, not the main branch.
> add a unified SVM consistency check test

- test_conformance/SVM/CMakeLists.txt
- test_conformance/SVM/test_unified_svm_apis.cpp
- test_conformance/SVM/unified_svm_fixture.h
This PR includes tests for `clSVMAllocWithPropertiesKHR` and `clGetSVMPointerInfoKHR` for valid pointers, as per the unified SVM test plan.  These tests are passing on many devices with the unified SVM emulation layer.
Note, these tests use the same test fixture and unified SVM wrapper as the unified SVM capability tests in #2210.
> add initial unified SVM API tests

- test_conformance/spirv_new/CMakeLists.txt
- test_conformance/spirv_new/spirv_asm/spv1.6/image_operand_nontemporal.spvasm32
- test_conformance/spirv_new/spirv_asm/spv1.6/image_operand_nontemporal.spvasm64
- test_conformance/spirv_new/test_spirv_16.cpp
Adds a basic test for reading from and writing to an image with the optional Nontemporal image operand.
> add SPIR-V 1.6 testing for Nontemporal Image Operand

- test_conformance/basic/test_async_copy2D.cpp
- test_conformance/basic/test_async_copy3D.cpp
- test_conformance/basic/test_bufferreadwriterect.cpp
- test_conformance/basic/test_constant.cpp
- test_conformance/basic/test_global_work_offsets.cpp
- test_conformance/basic/test_imagearraycopy.cpp
- test_conformance/basic/test_imagedim.cpp
- test_conformance/basic/test_local.cpp
- test_conformance/basic/test_local_kernel_scope.cpp
- test_conformance/basic/test_simple_image_pitch.cpp
- test_conformance/basic/test_sizeof.cpp
Printing of a `size_t` requires the `%zu` specifier.
> basic: fix size_t Wformat warnings

- test_common/harness/errorHelpers.cpp
- test_common/harness/errorHelpers.h
- test_conformance/spirv_new/main.cpp
Print the build log when building the program in `get_program_with_il` fails, to make it easier to investigate spirv_new test failures.
Factor out a global helper function `OutputBuildLog` for printing the build log for a single device.
> spirv_new: print build log in get_program_with_il

- test_conformance/vulkan/vulkan_test_base.h
Throwing an exception in the constructor for VulkanTestBase was always reported as an error.
> Report external sharing tests as skipped instead of failed when not supported

- test_conformance/printf/test_printf.cpp
%a or %A with printf on MSVC platforms have a default precision of 13, which is in contrast to OpenCL C specification for printf which only allows for exact digits required if precision is not specified.
> printf: Fix printf 'mixed_format_random'

- test_conformance/basic/test_fpmath.cpp
This PR fixes the validation logic for cases where the data type is not half. Because the variable nan_test is always false, types like float never trigger a validation failure.
> bugfix nan test for basic fpmath

- test_conformance/math_brute_force/reference_math.cpp
The reference was always being calculated using round to nearest even for fma when testing half precision.
Fixes https://github.com/KhronosGroup/OpenCL-CTS/issues/2224
> Correct reference for fma for RTZ devices for half

- test_common/harness/alloc.cpp
Project fails to build on systems with a kernel version older than 5.6.0 because of `-Wunused-function` combined with `-Werror`.
Expand the conditional compilation guard to include the offending code.
> Fix compilation failure caused by DMA heaps

- test_conformance/spirv_new/test_extinst_printf.cpp
The `extinst_printf_operands_scalar_int64` test could fail on 32-bit platforms with `CL_INVALID_ARG_SIZE`, because the helper function was not guaranteed to be instantiated using a 64-bit integer template type.
> spirv_new: ensure int64 printf test uses 64 bits

- test_common/harness/testHarness.h
- test_conformance/extensions/cl_khr_external_semaphore/test_external_semaphore.cpp
Both `REGISTER_TEST` and `REQUIRE_EXTENSION` expect cl_device_id variable but the variable name is inconsistent which makes both macros unusable together.
This change renames `deviceID` in `REQUIRE_EXTENSION` to `device` to be consistent with `REGISTER_TEST`.
> Fix inconsistent variable name in REGISTER_TEST and REQUIRE_EXTENSION

- test_conformance/spirv_new/spirv_asm/op_spec_constant_half_simple.spvasm32
- test_conformance/spirv_new/spirv_asm/op_spec_constant_half_simple.spvasm64
A recent improvement to the SPIR-V validator added checks to ensure the **Float16** capability is declared when directly operating on fp16 values, which identified issues in one of our SPIR-V test files.  This PR fixes the SPIR-V files to add the missing capability.
> add missing Float16 capability

- test_conformance/basic/test_work_item_functions.cpp
The value printed in the error message is not the correct one (used in the comparison statement)
> fix error message in work_item_functions_out_of_range

- CMakeLists.txt
`CL_ENABLE_BETA_EXTENSIONS` was just introduced in https://github.com/KhronosGroup/OpenCL-Headers/pull/276
to guard provisional and other experimental extensions. The CTS currently assumes
all definitions are always present.
> Always enable beta extensions

- test_conformance/math_brute_force/function_list.cpp
- test_conformance/math_brute_force/unary_float.cpp
Reflects the changes to the specification: https://github.com/KhronosGroup/OpenCL-Docs/pull/1318
Relaxed embedded exp and exp2 ulps will be 4 + floor(fabs(2 * x)).
Reciprocal and divide are unchanged because the code already handles the embedded profile case, see unary_float.c and binary_operator_float.c.
> Change relaxed exp exp2 embedded error to 4 + floor(fabs(2x))

- test_conformance/basic/test_vloadstore.cpp
Fix warnings such as:
test_vloadstore.cpp:330:49: error: format string is not a string literal (potentially insecure)
There were no security issues here as the format string arguments do not contain any conversion specifiers and are never written to.  Make that latter fact explicit to avoid the warnings.
> basic: fix -Wformat-security warnings

- test_conformance/api/test_sub_group_dispatch.cpp
The test is using CL_DEVICE_MAX_WORK_GROUP_SIZE as first dimension of local work size. But it can be bigger than the first dimension of CL_DEVICE_MAX_WORK_ITEM_SIZEs which results in failure.
This patch corrects it to query and use the first dimension of CL_DEVICE_MAX_WORK_ITEM_SIZES instead.
> Use max work item size instead

- .github/workflows/presubmit.yml
LunarG has changed the SDK file hosted for MacOS v1.3.275.0 from a .zip file to a .dmg file with the old hyperlink transparently redirecting to the new one.
The script expects a .zip archive so it fails when it downloads a .dmg file.
Bump the Vulkan SDK version to 1.4.309.0, which is the latest version and is provided as a .zip archive.
> Fix broken CI on MacOS

- test_conformance/SVM/CMakeLists.txt
- test_conformance/SVM/test_unified_svm_api_query_defaults.cpp
- test_conformance/SVM/test_unified_svm_apis.cpp
Note, this PR is setup to merge to the `cl_khr_unified_svm` branch.
Querying a non-USVM pointer should return default values and should not return an error.  This is the next item on the `cl_khr_unified_svm` test plan.
> add tests for clGetSVMPointerInfoKHR with a non-USVM pointer

- test_conformance/basic/CMakeLists.txt
- test_conformance/basic/test_bufferreadwriterect.cpp
- test_conformance/basic/test_constant.cpp
- test_conformance/basic/test_intmath.cpp
- test_conformance/basic/test_kernel_memory_alignment.cpp
- test_conformance/basic/test_numeric_constants.cpp
- test_conformance/basic/test_sizeof.cpp
- test_conformance/basic/test_vector_swizzle.cpp
Fix all `-Wformat` warnings in the basic test suite, and re-enable the warning.
> basic: fix Wformat warnings

- test_conformance/extensions/cl_khr_semaphore/test_semaphores_negative_create.cpp
Due to the improvements developed during work on #2237 with @bashbaug
> Modernization of semaphores_negative_create_invalid_device related to creating sub-devices

- test_conformance/printf/test_printf.cpp
We noticed such issue 
expected: ^(K{C, -30304.8, -22634.574219, 24476.882812, E4929EC2, 1467582223, 96vL.+
got:      ^(K{C, -30304.8, -22634.574219, 24476.882813, E4929EC2, 1467582223, 96vL.+
The input value is 24476.882812 and cannot be precisely represented as a single-floating point, so compilers are allowed to round it to the nearest representable value. In this case, the closest representable value to 24476.882812 is 24476.8828125, which rounds to 24476.882813.
Even some versions of MSVC prints that value as 24476.882813 and some 24476.882812 : https://godbolt.org/z/5GhEf8KPT
The proposal is to set precisely how many number should be displayed to avoid rounding.
> Test printf - set more precisely printing floating point numbers

- test_common/harness/imageHelpers.h
- test_conformance/images/clCopyImage/test_copy_1D.cpp
- test_conformance/images/clCopyImage/test_copy_1D_array.cpp
- test_conformance/images/clCopyImage/test_copy_1D_buffer.cpp
- test_conformance/images/clCopyImage/test_copy_2D.cpp
- test_conformance/images/clCopyImage/test_copy_2D_2D_array.cpp
- test_conformance/images/clCopyImage/test_copy_2D_3D.cpp
- test_conformance/images/clCopyImage/test_copy_2D_array.cpp
- test_conformance/images/clCopyImage/test_copy_3D.cpp
- test_conformance/images/clCopyImage/test_copy_3D_2D_array.cpp
- test_conformance/images/clCopyImage/test_loops.cpp
- test_conformance/images/clFillImage/test_fill_1D.cpp
- test_conformance/images/clFillImage/test_fill_1D_array.cpp
- test_conformance/images/clFillImage/test_fill_1D_buffer.cpp
- test_conformance/images/clFillImage/test_fill_2D.cpp
- test_conformance/images/clFillImage/test_fill_2D_array.cpp
- test_conformance/images/clFillImage/test_fill_3D.cpp
- test_conformance/images/clFillImage/test_loops.cpp
- test_conformance/images/common.cpp
This change mainly extends `clFillImage` and `clCopyImage` test function to include memory flags to be used during creating the image instead of hard-coding these values. The memory flags are also different parameters for source and destination images in `clCopyImage` tests.
> Refactor clCopyImage and clFillImage tests

- test_conformance/printf/util_printf.cpp
OpenCL C says that printing nan is implementation-defined for floating-point numbers - https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#printf-format-string
> Fix test_printf - any nan format is allowed by OpenCL C spec

- test_conformance/conversions/CMakeLists.txt
- test_conformance/conversions/basic_test_conversions.cpp
Using C++17's `if constexpr` avoids Wformat warnings in this template function, as it is now made explicit that the various format strings are only used with appropriate types.
> conversions: use C++17 to avoid Wformat warnings

- test_conformance/math_brute_force/binary_double.cpp
- test_conformance/math_brute_force/binary_i_double.cpp
- test_conformance/math_brute_force/binary_operator_double.cpp
- test_conformance/math_brute_force/binary_two_results_i_double.cpp
- test_conformance/math_brute_force/ternary_double.cpp
- test_conformance/math_brute_force/unary_double.cpp
- test_conformance/math_brute_force/unary_two_results_double.cpp
- test_conformance/math_brute_force/unary_two_results_i_double.cpp
- test_conformance/math_brute_force/unary_u_double.cpp
Call `getAllowedUlpError` to obtain the allowed ULP error for all of the double type (fp64) tests.  The aim is to standardise obtaining the desired ULP requirement and pave the way for adding the Embedded Profile ULP errors.
Contributes to https://github.com/KhronosGroup/OpenCL-CTS/issues/867
> [NFC] math_brute_force: use getAllowedUlpError for double

- test_conformance/spir/CMakeLists.txt
`test_spir` and its data are not installed correctly when building the installation target.
This change makes sure both the binary and the test data are installed correctly to `${CMAKE_INSTALL_BINDIR}/$<CONFIG>`.
> Add test_spir installation target

- test_conformance/api/test_zero_sized_enqueue.cpp
- Cases with a NULL global_work_size were not tested
- The specification states that zero-sized enqueues behave similarly to marker commands. Test that events for NDRange kernel commands have the correct CL_COMMAND_NDRANGE_KERNEL command type to guard against implementations naively using a marker command.
- Tidy up the code a bit and add missing error checking.
> Add missing coverage to api::zero_sized_enqueue

- test_common/harness/errorHelpers.cpp
- test_common/harness/imageHelpers.cpp
- test_common/harness/imageHelpers.h
- test_common/harness/kernelHelpers.cpp
- test_conformance/images/common.cpp
- test_conformance/images/kernel_read_write/test_common.cpp
This change add the following image formats to the supported image formats:
1. CL_UNSIGNED_INT10X6_EXT
2. CL_UNSIGNED_INT12X4_EXT
3. CL_UNSIGNED_INT14X2_EXT
4. CL_UNORM_INT10X6_EXT
5. CL_UNORM_INT12X4_EXT
6. CL_UNORM_INT14X2_EXT
For reference, the specification for `cl_ext_image_unsigned_10x6_12x4_14x2` can be found here: https://github.com/KhronosGroup/OpenCL-Docs/pull/1352
> Test image formats of cl_ext_image_unsigned_10x6_12x4_14x2

- test_conformance/conversions/basic_test_conversions.cpp
- test_conformance/conversions/basic_test_conversions.h
- test_conformance/conversions/test_conversions.cpp
Remove the test timing functionality from the conversions test, because it
- is not advertised in the help,
- is not supported on all platforms, triggering warnings during the build,
- goes beyond the core purpose of the conformance test suite.
> conversions: remove timing functionality

- test_conformance/spirv_new/test_spirv_14.cpp
- test_conformance/spirv_new/test_spirv_16.cpp
The tests for new image operands should not run on devices that do not support images.
> add missing image support checks to a few SPIR-V tests

- test_conformance/vulkan/main.cpp
Switch the test_vulkan default to use device local memory
> test_vulkan: switch defaults on device local memory

- test_conformance/api/CMakeLists.txt
- test_conformance/api/negative_enqueue_map_image.cpp
- test_conformance/api/test_kernels.cpp
- test_conformance/basic/test_enqueue_map.cpp
- test_conformance/extensions/cl_khr_command_buffer/command_buffer_with_immutable_memory.h
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_copy.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_fill.cpp
This change provides partial test coverage for KhronosGroup/OpenCL-Docs#1280
Adding CTS tests for:
1. clEnqueueMapBuffer, clEnqueueMapImage.
2. Command buffer negative tests.
3. clSetKernelArgs negative tests.
The bulk of the tests is to make sure that the CL driver does not allow writing to a memory object that is created with `CL_MEM_IMMUTABLE_EXT` flag when used with the above APIs.
> Add tests for cl_ext_immutable_memory_objects

- test_conformance/api/test_kernel_local_memory_size.cpp
- test_conformance/api/test_queue.cpp
This commit fixes three tests that have memory leaks due to unreleased CL objects.
- `kernel_local_memory_size`
- `multi_queue_flush_on_release`
- `queue_flush_on_release`
> Fix memory leaks in `api` test suite

- test_conformance/basic/test_imagecopy.cpp
- test_conformance/basic/test_imagecopy3d.cpp
- test_conformance/basic/test_imagereadwrite.cpp
- test_conformance/basic/test_imagereadwrite3d.cpp
Refactor the following tests:
1. `test_imagecopy`
2. `test_imagecopy3d`
3. `test_imagereadwrite`
4. `test_imagereadwrite3d`
The change does the following:
1. Use RAII to manage allocated resources
2. For `imagecopy` and `imagecopy3d`, the change allows for a custom src image memory flags and adjusts how the source image is created according to the input flags.
> Refactor imagecopy and imagereadwrite tests

- test_conformance/profiling/execute_multipass.cpp
- Fixed leaks caused by missing clRelease calls
- Improved error handling readability
Signed-off-by: Oskar Hubert Weber [oskar.hubert.weber@intel.com](mailto:oskar.hubert.weber@intel.com)
> Fix memory leaks in test_profiling execute_multipass

- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.cpp
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer.h
- test_conformance/extensions/cl_khr_command_buffer/basic_command_buffer_tests.cpp
Add cl_khr_command_buffer test that is it valid to release a command-buffer after it has been enqueued but before execution is finished.
This stresses the semantics from [clReleaseCommandBufferKHR](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clReleaseCommandBufferKHR.html#_description) that: "After the command_buffer reference count becomes zero **and has finished execution**, the command-buffer is deleted"
> Test releasing a command-buffer after submission but before execution has finished

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
Adds cl_khr_unified_svm to the list of known extensions in the compiler defines for extension test.
> Add cl_khr_unified_svm to the list of known extensions in the compiler defines for extension test.

- test_conformance/images/kernel_read_write/test_common.cpp
- test_conformance/images/kernel_read_write/test_iterations.cpp
Do not remove calls to `sample_image_pixel_float_offset` as it is using the `verbose` mode.
> clean unused variables

- test_conformance/spir/main.cpp
`clGetDeviceInfo` should fail with `CL_INVALID_VALUE` when queried for `CL_DEVICE_SPIR_VERSIONS` on devices that do not claim to support the extension that provides it, `cl_khr_spir`.
Following this change, the test is skipped instead of failing on devices that do not support `cl_khr_spir`.
> Fix test_spir not checking for the required extension

- test_conformance/non_uniform_work_group/CMakeLists.txt
- test_conformance/non_uniform_work_group/test_advanced_2d.cpp
- test_conformance/non_uniform_work_group/test_advanced_3d.cpp
- test_conformance/non_uniform_work_group/test_advanced_other.cpp
- test_conformance/non_uniform_work_group/test_basic.cpp
- test_conformance/non_uniform_work_group/tools.cpp
- test_conformance/non_uniform_work_group/tools.h
Modify the prime numbers generator function to return `size_t` instead of `int` and use `0` as a sentinal value instead of hardcoded negative ones. `0` is not a prime number, so it is suitable to use to indicate an error.
Fixes #1159
> Enable -Wnarrowing in non_uniform_work_group test suite.

- test_conformance/compiler/test_compiler_defines_for_extensions.cpp
While #2409 is under review, could we please add "cl_khr_spirv_queries" to the list of known extensions?  This will prevent test "failures" for implementations that support the extension.
> add cl_khr_spirv_queries to list of known extensions

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_simultaneous.cpp
Prior to this change, both `clEnqueueReadBuffer` calls before and after updating the command buffer were writing to the same `output_buffer`, causing a data race condition and the first call's result to be overwritten. This commit introduces separate destination vectors (`output_buffer` and `updated_output_buffer`) for these operations and verifies both results independently to ensure test integrity.
> Fix data race in mutable command buffer simultaneous execution test

- test_conformance/SVM/CMakeLists.txt
- test_conformance/SVM/test_unified_svm_corner_cases.cpp
- test_conformance/SVM/unified_svm_fixture.h
This PR adds tests for a number of interesting unified SVM corner cases.
Not all of these may be valid tests!  If we decide that some of these tests are invalid, I will remove them.
Added tests include:
* Calling clSVMAllocWithPropertiesKHR to allocate zero bytes for each unified SVM type.
* Calling clSVMFreeWithPropertiesKHR to free a NULL pointer.
* Calling clEnqueueSVMFree to asynchronously free an empty set of SVM pointers.
* Calling clEnqueueSVMFree to asynchronously free a NULL pointer.
* Calling clSetKernelArgSVMPointer to set a NULL pointer kernel argument.
* Calling clSetKernelArgSVMPointer to set a bogus pointer kernel argument.
* Calling clSetKernelExecInfo with CL_KERNEL_EXEC_INFO_SVM_PTRS with an empty set of SVM pointers.
* Calling clSetKernelExecInfo with …
> add tests for unified SVM corner cases

- test_conformance/extensions/cl_khr_external_memory_ahb/debug_ahb.cpp
- test_conformance/extensions/cl_khr_external_memory_ahb/test_ahb.cpp
- test_conformance/extensions/cl_khr_external_memory_ahb/test_ahb_negative.cpp
Update the test to use
`CL_EXTERNAL_MEMORY_HANDLE_ANDROID_HARDWARE_BUFFER_KHR` instead of `CL_EXTERNAL_MEMORY_HANDLE_AHB_KHR` to match the headers.
Handle missing format in switch statement.
> Fix compilation errors cl_khr_external_memory_ahb

- .github/workflows/presubmit.yml
- test_conformance/d3d10/CMakeLists.txt
- test_conformance/d3d11/CMakeLists.txt
Both tests depend on a very old DirectX SDK (August 2009) and expect it to be extracted to an {NV_TOOLS} environment variable. They additionally require definining {ARCH} as a CMake configuration option, which is not needed.
Update both projects to use DirectX libraries provided by the Windows SDK and drop the unneeded configuration options.
> Update D3D10 and D3D11 interop tests

- test_conformance/extensions/cl_khr_command_buffer/cl_khr_command_buffer_mutable_dispatch/mutable_command_info.cpp
The check implementated by that Skip function is already implemented in 'InfoMutableCommandBufferTest::Skip()'.
Also this is trying to get the extension_version before checking whether the extension is supported, leading to false negative for device not supporting the extension.
> mutable_command_info: remove unnecessary Skip function

- test_conformance/basic/test_progvar.cpp
The test was mapping a memory object using CL_MAP_READ but then writing to its host_ptr using memset.
> Fix basic progvar_prog_scope_init and progvar_prog_scope_uninit

- test_conformance/extensions/cl_khr_command_buffer/command_buffer_get_command_buffer_info.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_enqueue.cpp
- test_conformance/extensions/cl_khr_command_buffer/negative_command_buffer_finalize.cpp
This is a very small subset of the changes in #2477 to get things building again, since the command-buffer pending state is no longer in the spec or headers.
> remove checks for the command-buffer pending state

- test_conformance/spir/main.cpp
This handles the case where test_spir is called without arguments.
> Fix -list option in test_spir

- test_conformance/api/test_kernels.cpp
The image was created with 4 channels, but the initialization data only accounted for a single channel.
> Fix OOB read in negative_set_immutable_memory_to_writeable_kernel_arg

- test_conformance/subgroups/test_subgroup_ballot.cpp
- test_conformance/subgroups/test_subgroup_non_uniform_vote.cpp
This allows implementors to support `cl_khr_subgroup_ballot` and `cl_khr_subgroup_non_uniform_vote` without requiring non uniform workgroup support.
> Make subgroup tests run on devices without non uniform work groups

- test_conformance/SVM/test_unified_svm_mem_cpy.cpp
- test_conformance/SVM/test_unified_svm_mem_fill.cpp
* Refactor check_for_common_memory_type to only check for device access.
* rename check_for_common_memory_type to caps_compatibility_check
* Update test_unified_svm_mem_cpy and test_unified_svm_mem_fill.
fixes #2517
> Unified SVM Memcpy and check_for_common_memory_type

- test_conformance/SVM/test_unified_svm_mem_cpy.cpp
- test_conformance/SVM/test_unified_svm_mem_fill.cpp
Removes unused code from the unified SVM memory fill test.
Adds an informational message when a unified SVM capability combination is skipped for memcpy and memfill.
> clean up unified SVM memory fill test

- test_conformance/compiler/main.cpp
Although run_conformance.py runs from test_conformance, it will change the current working directory before launching each individual test. Adjust the path accordingly.
> One last file path fix for test_compiler.
