.travis.yml
CMakeVendor.txt

Add basic Travis config for Linux builds
Performs a single build on Linux using the unified
headers and linking against the ICD.
Unified headers are broken for 2.x on OSX (see
https://github.com/KhronosGroup/OpenCL-Headers/issues/31).
Adding OSX builds should hopefully be a one-line change
once this is fixed.

 Add basic Travis config for Linux builds

---

test_conformance/basic/test_hostptr.c

0 is passed in for map_flags but valid values are CL_MAP_READ, CL_MAP_WRITE and CL_MAP_WRITE_INVALIDATE_REGION.
Fix is to use CL_MAP_READ in this case.

cl12: Incorrect value passed to clEnqueueMapImage in basic/hostptr

---

test_conformance/basic/test_hostptr.c

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/76

cl21: Pass CL_MAP_READ to clEnqueueMapImage as passing 0 is invalid

---

test_conformance/basic/test_hostptr.c

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/76

cl22: Pass CL_MAP_READ to clEnqueueMapImage as passing 0 is invalid

---

test_conformance/compatibility/test_conformance/api/test_api_min_max.c

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/82

cl21: Khronos Bug 15683 Missing OpenCL 2.1 support in API compatibility tests

---

test_conformance/api/test_api_min_max.c

Fix Issue https://github.com/KhronosGroup/OpenCL-CTS/issues/65

cl22: Khronos Bug 15347 test_api_min_max allocates too much memory

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/37

cl22: Fix Issue 37 - Test compiler - cl_khr_spirv_no_integer_wrap_decoration

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/37

cl21: Fix Issue 37 - Test compiler - cl_khr_spirv_no_integer_wrap_decoration

---

test_conformance/printf/util_printf.c

This patch solves issue #98 by changing return value from false to 1 in function verifyOutputBuffer to indicate mismatches.

cl21: Fix Issue #98 - Fix verifyOutputBuffer return value in printf

---

test_conformance/printf/util_printf.c

Fix issue #98 in cl12_trunk branch

cl12: Fix Issue #98 - Fix verifyOutputBuffer return value in printf

---

test_conformance/printf/util_printf.c

Fix issue #98 in cl20_trunk branch

cl20: Fix Issue #98 - Fix verifyOutputBuffer return value in printf

---

test_conformance/printf/util_printf.c

This patch solves issue #98 in cl22_trunk branch

cl22: Fix Issue #98 - Fix verifyOutputBuffer return value in printf

---

test_conformance/spir/main.cpp

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/115

cl21: Khronos Bug 15728 SPIR 1.2 tests fail when some cases are skipped

---

test_conformance/spir/main.cpp

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/115

cl22: Khronos Bug 15728 SPIR 1.2 tests fail when some cases are skipped

---

test_conformance/SVM/test_allocate_shared_buffer.cpp

The buffer was never unmapped.
Change-Id: If8be7f9f08ae7c26a537039f2bbeeb674cc30059
Signed-off-by: Georgios Pinitas <georgios.pinitas@arm.com>
fix issue: https://github.com/KhronosGroup/OpenCL-CTS/issues/126

cl22: Fix resource leak in SVM test

---

test_conformance/printf/test_printf.c
test_conformance/printf/test_printf.h

cl22: Reuse test harness code in printf

---

test_conformance/printf/test_printf.c
test_conformance/printf/test_printf.h

cl21: Reuse test harness code in printf

---

test_conformance/printf/test_printf.c
test_conformance/printf/test_printf.h

cl20: Reuse test harness code in printf

---

test_conformance/spirv_new/main.cpp

cl21: Segfault when passing arguments to test_conformance_spirv_new

---

test_conformance/basic/test_numeric_constants.cpp

There is no mention of this rule that I could find in the
OpenCL 1.2 specification. cl12_trunk was the only branch
with this behaviour.

Don't require image support on GPU devices

---

test_conformance/conversions/test_conversions.c

cl21: Reuse test harness code in conversions

---

test_conformance/conversions/test_conversions.c

cl22: Reuse test harness code in conversions

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

Updated the list of known extensions to include all extensions referenced in the OpenCL Extension Specification 1.2 - Revision 25 and OpenCL Specification 1.2 - Revision 19 documents.
Also removed extensions from later OpenCL versions.

cl12: Compiler - updated extension list for compiler_defines_for_exensions

---

test_conformance/math_brute_force/FunctionList.c
test_conformance/math_brute_force/FunctionList.h
test_conformance/math_brute_force/main.c
test_conformance/spir/CMakeLists.txt
test_conformance/spir/kernelargs.h
test_conformance/spir/run_build_test.cpp
test_conformance/spir/run_services.cpp
test_conformance/spir/run_services.h

Spir test compares floating-point kernel results bit-by-bit with
correct results. However, for math_brute_force kernels, specification
does not ask for SPIR and OpenCL C path to match bit-to-bit. This patch
reuses ulps threshold from math_brute_force folder for math_brute_force
kernels in spir test. See issue #135

cl12: Reuse math_brute_force ulp threshold in spir test

---

test_conformance/math_brute_force/FunctionList.c
test_conformance/math_brute_force/FunctionList.h
test_conformance/spir/CMakeLists.txt
test_conformance/spir/kernelargs.h
test_conformance/spir/run_build_test.cpp
test_conformance/spir/run_services.cpp
test_conformance/spir/run_services.h

Spir test compares floating-point kernel results bit-by-bit with
correct results. However, for math_brute_force kernels, specification
does not ask for SPIR and OpenCL C path to match bit-to-bit. This patch
reuses ulps threshold from math_brute_force folder for math_brute_force
kernels in spir test. See issue #135

cl20: Reuse math_brute_force ulp threshold in spir test

---

test_conformance/math_brute_force/FunctionList.c
test_conformance/math_brute_force/FunctionList.h
test_conformance/spir/CMakeLists.txt
test_conformance/spir/kernelargs.h
test_conformance/spir/run_build_test.cpp
test_conformance/spir/run_services.cpp
test_conformance/spir/run_services.h

Spir test compares floating-point kernel results bit-by-bit with
correct results. However, for math_brute_force kernels, specification
does not ask for SPIR and OpenCL C path to match bit-to-bit. This patch
reuses ulps threshold from math_brute_force folder for math_brute_force
kernels in spir test. See issue #135

cl21: Reuse math_brute_force ulp threshold in spir test

---

test_conformance/math_brute_force/FunctionList.c
test_conformance/math_brute_force/FunctionList.h
test_conformance/spir/CMakeLists.txt
test_conformance/spir/kernelargs.h
test_conformance/spir/run_build_test.cpp
test_conformance/spir/run_services.cpp
test_conformance/spir/run_services.h

Spir test compares floating-point kernel results bit-by-bit with
correct results. However, for math_brute_force kernels, specification
does not ask for SPIR and OpenCL C path to match bit-to-bit. This patch
reuses ulps threshold from math_brute_force folder for math_brute_force
kernels in spir test. See issue #135

cl22: Reuse math_brute_force ulp threshold in spir test

---

test_conformance/allocations/main.cpp

cl20: Reuse test harness code in allocations

---

test_conformance/math_brute_force/Utility.h
test_conformance/math_brute_force/main.c

cl20: Reuse test harness code in math_brute_force

---

test_conformance/math_brute_force/Utility.h
test_conformance/math_brute_force/main.c

cl21: Reuse test harness code in math_brute_force

---

test_conformance/math_brute_force/Utility.h
test_conformance/math_brute_force/main.c

cl22: Reuse test harness code in math_brute_force

---

test_conformance/printf/test_printf.c

cl20: Remove redundant releaseOutputStream call in printf

---

test_conformance/printf/test_printf.c

cl21: Remove redundant releaseOutputStream call in printf

---

test_conformance/printf/test_printf.c

cl22: Remove redundant releaseOutputStream call in printf

---

test_conformance/half/Test_roundTrip.c
test_conformance/half/Test_vLoadHalf.c
test_conformance/half/Test_vStoreHalf.c
test_conformance/half/cl_utils.c
test_conformance/half/cl_utils.h
test_conformance/half/main.c
test_conformance/half/tests.h

cl22: Reuse test harness code in half

---

test_conformance/half/Test_roundTrip.c
test_conformance/half/Test_vLoadHalf.c
test_conformance/half/Test_vStoreHalf.c
test_conformance/half/cl_utils.c
test_conformance/half/cl_utils.h
test_conformance/half/main.c
test_conformance/half/tests.h

cl20: Reuse test harness code in half

---

test_conformance/half/Test_roundTrip.c
test_conformance/half/Test_vLoadHalf.c
test_conformance/half/Test_vStoreHalf.c
test_conformance/half/cl_utils.c
test_conformance/half/cl_utils.h
test_conformance/half/main.c
test_conformance/half/tests.h

cl21: Reuse test harness code in half

---

test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_image_methods/test_1D.cpp
test_conformance/images/kernel_image_methods/test_1D_array.cpp
test_conformance/images/kernel_image_methods/test_2D.cpp
test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_3D.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp

cl22: Reuse test harness code in kernel_image_methods

---

test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_image_methods/test_1D.cpp
test_conformance/images/kernel_image_methods/test_1D_array.cpp
test_conformance/images/kernel_image_methods/test_2D.cpp
test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_3D.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp

cl21: Reuse test harness code in kernel_image_methods

---

test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_image_methods/test_1D.cpp
test_conformance/images/kernel_image_methods/test_1D_array.cpp
test_conformance/images/kernel_image_methods/test_2D.cpp
test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_3D.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp

cl20: Reuse test harness code in kernel_image_methods

---

test_conformance/spirv_new/main.cpp

Previously this was determined by checking `sizeof(void *)` but this causes issues when the device address width differs from the host.

cl21: Check device address width when deciding which SPIR-V binary to read

---

test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clGetInfo/test_1D.cpp
test_conformance/images/clGetInfo/test_1D_2D_array.cpp
test_conformance/images/clGetInfo/test_2D.cpp
test_conformance/images/clGetInfo/test_3D.cpp
test_conformance/images/clGetInfo/test_loops.cpp

cl22: Reuse test harness code in clGetInfo

---

test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clGetInfo/test_1D.cpp
test_conformance/images/clGetInfo/test_1D_2D_array.cpp
test_conformance/images/clGetInfo/test_2D.cpp
test_conformance/images/clGetInfo/test_3D.cpp
test_conformance/images/clGetInfo/test_loops.cpp

cl21: Reuse test harness code in clGetInfo

---

test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clGetInfo/test_1D.cpp
test_conformance/images/clGetInfo/test_1D_2D_array.cpp
test_conformance/images/clGetInfo/test_2D.cpp
test_conformance/images/clGetInfo/test_3D.cpp
test_conformance/images/clGetInfo/test_loops.cpp

cl20: Reuse test harness code in clGetInfo

---

test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/clReadWriteImage/test_read_1D.cpp
test_conformance/images/clReadWriteImage/test_read_1D_array.cpp
test_conformance/images/clReadWriteImage/test_read_2D.cpp
test_conformance/images/clReadWriteImage/test_read_2D_array.cpp
test_conformance/images/clReadWriteImage/test_read_3D.cpp

cl22: Reuse test harness code in clReadWriteImage

---

test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/clReadWriteImage/test_read_1D.cpp
test_conformance/images/clReadWriteImage/test_read_1D_array.cpp
test_conformance/images/clReadWriteImage/test_read_2D.cpp
test_conformance/images/clReadWriteImage/test_read_2D_array.cpp
test_conformance/images/clReadWriteImage/test_read_3D.cpp

cl21: Reuse test harness code in clReadWriteImage

---

test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/clReadWriteImage/test_read_1D.cpp
test_conformance/images/clReadWriteImage/test_read_1D_array.cpp
test_conformance/images/clReadWriteImage/test_read_2D.cpp
test_conformance/images/clReadWriteImage/test_read_2D_array.cpp
test_conformance/images/clReadWriteImage/test_read_3D.cpp

cl20: Reuse test harness code in clReadWriteImage

---

test_conformance/images/clCopyImage/main.cpp
test_conformance/images/clCopyImage/test_copy_1D.cpp
test_conformance/images/clCopyImage/test_copy_1D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D.cpp
test_conformance/images/clCopyImage/test_copy_2D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D_3D.cpp
test_conformance/images/clCopyImage/test_copy_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_3D.cpp
test_conformance/images/clCopyImage/test_copy_3D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/clCopyImage/test_loops.cpp

cl22: Reuse test harness code in clCopyImage

---

test_conformance/images/clCopyImage/main.cpp
test_conformance/images/clCopyImage/test_copy_1D.cpp
test_conformance/images/clCopyImage/test_copy_1D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D.cpp
test_conformance/images/clCopyImage/test_copy_2D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D_3D.cpp
test_conformance/images/clCopyImage/test_copy_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_3D.cpp
test_conformance/images/clCopyImage/test_copy_3D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/clCopyImage/test_loops.cpp

cl21: Reuse test harness code in clCopyImage

---

test_conformance/images/clCopyImage/main.cpp
test_conformance/images/clCopyImage/test_copy_1D.cpp
test_conformance/images/clCopyImage/test_copy_1D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D.cpp
test_conformance/images/clCopyImage/test_copy_2D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D_3D.cpp
test_conformance/images/clCopyImage/test_copy_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_3D.cpp
test_conformance/images/clCopyImage/test_copy_3D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/clCopyImage/test_loops.cpp

cl20: Reuse test harness code in clCopyImage

---

test_conformance/images/clFillImage/main.cpp
test_conformance/images/clFillImage/test_fill_1D.cpp
test_conformance/images/clFillImage/test_fill_1D_array.cpp
test_conformance/images/clFillImage/test_fill_2D.cpp
test_conformance/images/clFillImage/test_fill_2D_array.cpp
test_conformance/images/clFillImage/test_fill_3D.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp
test_conformance/images/clFillImage/test_loops.cpp

cl22: Reuse test harness code in clFillImage

---

test_conformance/images/clFillImage/main.cpp
test_conformance/images/clFillImage/test_fill_1D.cpp
test_conformance/images/clFillImage/test_fill_1D_array.cpp
test_conformance/images/clFillImage/test_fill_2D.cpp
test_conformance/images/clFillImage/test_fill_2D_array.cpp
test_conformance/images/clFillImage/test_fill_3D.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp
test_conformance/images/clFillImage/test_loops.cpp

cl21: Reuse test harness code in clFillImage

---

test_conformance/images/clFillImage/main.cpp
test_conformance/images/clFillImage/test_fill_1D.cpp
test_conformance/images/clFillImage/test_fill_1D_array.cpp
test_conformance/images/clFillImage/test_fill_2D.cpp
test_conformance/images/clFillImage/test_fill_2D_array.cpp
test_conformance/images/clFillImage/test_fill_3D.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp
test_conformance/images/clFillImage/test_loops.cpp

cl20: Reuse test harness code in clFillImage

---

test_conformance/printf/test_printf.c

This patch solves #100 by using a unique file for each test, so that parallel printf tests will not fail.

cl21: Use unique tmp file to allow parallel printf tests

---

test_conformance/printf/test_printf.c

This patch solves #100 by using a unique file for each test, so that parallel printf tests will not fail.

cl22: Use unique tmp file to allow parallel printf tests

---

test_conformance/printf/test_printf.c
test_conformance/printf/test_printf.h
test_conformance/printf/util_printf.c

This patch solves #100 by using a unique file for each test, so that parallel printf tests will not fail.

cl12: Use unique tmp file to allow parallel printf tests

---

CMakeLists.txt
test_conformance/gl/CMakeLists.txt
test_conformance/gl/main.cpp

* Fixes compilation when setting GL_IS_SUPPORTED:
* due to CMakeLists.txt referencing non-existent files and missing an include folder;
* due to gl/main.cpp referencing an undefined variable.
* Add OpenGL tests that are present but were not referenced by CMakeLists.txt;
* Expose the graphics interop test toggles via CMake, allowing the user to enable/disable them without modifying CMakeLists.txt;
* Add such a toggle for OpenGL ES tests.

OpenCL 2.2 graphics fixes

---

CMakeLists.txt
test_conformance/gl/CMakeLists.txt
test_conformance/gl/main.cpp

* Fixes compilation when setting GL_IS_SUPPORTED:
* due to CMakeLists.txt referencing non-existent files and missing an include folder;
* due to gl/main.cpp referencing an undefined variable.
* Add OpenGL tests that are present but were not referenced by CMakeLists.txt;
* Expose the graphics interop test toggles via CMake, allowing the user to enable/disable them without modifying CMakeLists.txt;
* Add such a toggle for OpenGL ES tests.

OpenCL 2.1 graphics fixes

---

CMakeLists.txt
test_conformance/gl/CMakeLists.txt
test_conformance/gl/main.cpp

* Fixes compilation when setting GL_IS_SUPPORTED:
* due to CMakeLists.txt referencing non-existent files and missing an include folder;
* due to gl/main.cpp referencing an undefined variable.
* Add OpenGL tests that are present but were not referenced by CMakeLists.txt;
* Expose the graphics interop test toggles via CMake, allowing the user to enable/disable them without modifying CMakeLists.txt;
* Add such a toggle for OpenGL ES tests.

OpenCL 2.0 graphics fixes

---

test_common/harness/msvc9.c

FP_ILOGB0, FP_ILOGBNAN, ilogbm, ilogbf, ilogbl, fetestexcept and
feclearexcept are supported in Visual Studio 2013. See #183

cl21: Fix ilogbl crash and fetestexcept build if _MSC_VER>=1800

---

test_common/harness/msvc9.c

FP_ILOGB0, FP_ILOGBNAN, ilogbm, ilogbf, ilogbl, fetestexcept and
feclearexcept are supported in Visual Studio 2013. See #183

cl12: Fix ilogbl crash and fetestexcept build if _MSC_VER>=1800

---

test_common/harness/msvc9.c

FP_ILOGB0, FP_ILOGBNAN, ilogbm, ilogbf, ilogbl, fetestexcept and
feclearexcept are supported in Visual Studio 2013. See #183

cl20: Fix ilogbl crash and fetestexcept build if _MSC_VER>=1800

---

test_common/harness/msvc9.c

FP_ILOGB0, FP_ILOGBNAN, ilogbm, ilogbf, ilogbl, fetestexcept and
feclearexcept are supported in Visual Studio 2013. See #183

cl22: Fix ilogbl crash and fetestexcept build if _MSC_VER>=1800

---

test_conformance/images/samplerlessReads/main.cpp
test_conformance/images/samplerlessReads/test_iterations.cpp
test_conformance/images/samplerlessReads/test_loops.cpp
test_conformance/images/samplerlessReads/test_read_1D.cpp
test_conformance/images/samplerlessReads/test_read_1D_array.cpp
test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
test_conformance/images/samplerlessReads/test_read_2D_array.cpp
test_conformance/images/samplerlessReads/test_read_3D.cpp

cl20: Reuse test harness code in samplerlessReads

---

test_conformance/images/samplerlessReads/main.cpp
test_conformance/images/samplerlessReads/test_iterations.cpp
test_conformance/images/samplerlessReads/test_loops.cpp
test_conformance/images/samplerlessReads/test_read_1D.cpp
test_conformance/images/samplerlessReads/test_read_1D_array.cpp
test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
test_conformance/images/samplerlessReads/test_read_2D_array.cpp
test_conformance/images/samplerlessReads/test_read_3D.cpp

cl21: Reuse test harness code in samplerlessReads

---

test_conformance/images/samplerlessReads/main.cpp
test_conformance/images/samplerlessReads/test_iterations.cpp
test_conformance/images/samplerlessReads/test_loops.cpp
test_conformance/images/samplerlessReads/test_read_1D.cpp
test_conformance/images/samplerlessReads/test_read_1D_array.cpp
test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
test_conformance/images/samplerlessReads/test_read_2D_array.cpp
test_conformance/images/samplerlessReads/test_read_3D.cpp

cl22: Reuse test harness code in samplerlessReads

---

test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.cpp
test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.h

in non_uniform_work_group the required buffer size may exceed the available device memory size.

Fix Issue #53: required buffer size exceed the available size

---

test_conformance/conversions/CMakeLists.txt
test_conformance/integer_ops/CMakeLists.txt
test_conformance/math_brute_force/CMakeLists.txt

This resulted in “unknown target CPU 'i686'” error messages on my laptop, as `CMAKE_SYSTEM_PROCESSOR` was `x86_64` which matches the `x86` string.

cl12: Do not mistake x86_64 platforms as x86

---

test_conformance/headers/test_headers.c

cl20: Reuse test harness code in headers

---

test_conformance/headers/test_headers.c

cl22: Reuse test harness code in headers

---

test_conformance/headers/test_headers.c

cl21: Reuse test harness code in headers

---

test_conformance/contractions/contractions.c

cl22: Reuse test harness code in contractions

---

test_conformance/contractions/contractions.c

cl21: Reuse test harness code in contractions

---

test_common/harness/testHarness.c
test_conformance/images/kernel_read_write/main.cpp
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp
test_conformance/images/testBase.h

cl20: Reuse test harness code in kernel_read_write

---

test_common/harness/testHarness.c
test_conformance/images/kernel_read_write/main.cpp
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp
test_conformance/images/testBase.h

cl21: Reuse test harness code in kernel_read_write

---

test_common/harness/testHarness.c
test_conformance/images/kernel_read_write/main.cpp
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp
test_conformance/images/testBase.h

cl22: Reuse test harness code in kernel_read_write

---

test_common/harness/imageHelpers.cpp

This fix is required due to char defaulting to unsigned on
arm platforms while the test code assumes char will be signed.
Signed-off-by: Sam Laynton <sam.laynton@arm.com>

cl21: Khronos Bug 16192: Make image helpers work on ARM hosts

---

test_conformance/device_execution/host_queue_order.cpp

Use convert_int_rte for the result of the sqrt instead of casting to int.
Fixes possible rounding issues.

Bugfix for Khronos Bug 16242.

---

test_common/harness/errorHelpers.h
test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h

This moves from numeric values to enum values to keep result state of
the test, so we can easily save this information in JSON results.

Use test_status for test results

---

test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h

This moves from numeric values to enum values to keep result state of
the test, so we can easily save this information in JSON results.

cl20: Use test_status for test results

---

test_common/harness/errorHelpers.h
test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h

This moves from numeric values to enum values to keep result state of
the test, so we can easily save this information in JSON results.

cl21: Use test_status for test results

---

test_common/harness/errorHelpers.h
test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/errorHelpers.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h

This adds functionality to define minimal required version through the
ADD_TEST* macros. Tests that don't meet the version requirement will
be skipped.
By default the minimal required version is set to 1.0, subsequent
patches will set the appropriate version for each of the tests.

Add minimal required version functionality

---

test_common/harness/errorHelpers.h
test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/errorHelpers.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h
test_conformance/spirv_new/main.cpp

This adds functionality to define minimal required version through the
ADD_TEST* macros. Tests that don't meet the version requirement will
be skipped.
By default the minimal required version is set to 1.0, subsequent
patches will set the appropriate version for each of the tests.

cl21: Add minimal required version functionality

---

test_common/harness/errorHelpers.h
test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/errorHelpers.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h

This adds functionality to define minimal required version through the
ADD_TEST* macros. Tests that don't meet the version requirement will
be skipped.
By default the minimal required version is set to 1.0, subsequent
patches will set the appropriate version for each of the tests.

cl20: Add minimal required version functionality

---

test_conformance/device_execution/host_queue_order.cpp

Currently, test_host_queue_order relies on bit accurate float ops.
It expects expects that sqrt((float)i * i) == i.
This is not always true due to floating point precision limitations.
The test does not really need the sqrt operation and it can be removed
instead of trying to correct the floating point check.
Replace problematic float operation with constant value of 1.

Fix test_host_queue_order not to rely on bit accurate float ops

---

test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h

This patch ensures `runTestHarness` returns either `EXIT_FAILURE` or `EXIT_SUCCESS` to avoid undefined behaviour.

Improve exit codes (#32)

---

test_common/harness/compat.h

Fix Issue #284 Intel compiler supports in different way the following functions. Here is the need to move down if ! defined( __INTEL_COMPILER ) expression. Additionally I justify formatting.

cl21: Intel compiler changes compat.h

---

test_common/harness/compat.h

Fix Issue #284 Intel compiler supports in different way the following functions. Here is the need to move down `if ! defined( __INTEL_COMPILER )` expression. Additionally I justify formatting.

Intel compiler changes compat.h

---

test_conformance/SVM/main.cpp

Fix Issue #284 . Intel compiler returned assert for the following code. Because code was redundant I decided use harness available function which is used for OCL version checking. Looks more readable and clearly.

cl21: Intel compiler - fix assert when checking OCL version

---

test_conformance/SVM/main.cpp

Fix Issue #284 . Intel compiler returned assert for the following code. Because code was redundant I decided use harness available function which is used for OCL version checking. Looks more readable and clearly.

Intel compiler - fix assert when checking OCL version

---

CMakeLists.txt

Fix Issue #284 . Add support for long double type as a compiler flag

cl21: Intel compiler changes in cmake

---

CMakeLists.txt

Fix Issue #284 . Add support for long double type as a compiler flag

Intel compiler changes in cmake

---

test_conformance/math_brute_force/reference_math.c

Fix Issue #284 . When Intel compiler is used then embeded signbitl will be used

Intel compiler bruteforce -  fix signbitl function

---

test_conformance/math_brute_force/reference_math.c

Fix Issue #284 . When Intel compiler is used then embeded signbitl will be used

cl21: Intel compiler bruteforce -  fix signbitl function

---

test_conformance/images/clFillImage/test_fill_generic.cpp

The copy_image (for OpenCL 1.2) and fill_image (for 1.2 and 2.x) conformance tests incorrectly use the row pitch instead of the slice pitch when mapping the image.

master: Use slice pitch instead of row pitch for 1D arrays.

---

test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp

The copy_image (for OpenCL 1.2) and fill_image (for 1.2 and 2.x) conformance tests incorrectly use the row pitch instead of the slice pitch when mapping the image.
See #312

CL12: Use slice pitch instead of row pitch for 1D arrays.

---

test_conformance/images/clFillImage/test_fill_generic.cpp

The copy_image (for OpenCL 1.2) and fill_image (for 1.2 and 2.x) conformance tests incorrectly use the row pitch instead of the slice pitch when mapping the image.
See #312

CL21: Use slice pitch instead of row pitch for 1D arrays.

---

test_conformance/images/clFillImage/test_fill_generic.cpp

The copy_image (for OpenCL 1.2) and fill_image (for 1.2 and 2.x) conformance tests incorrectly use the row pitch instead of the slice pitch when mapping the image.
See #312

CL20: Use slice pitch instead of row pitch for 1D arrays.

---

test_conformance/api/test_queue_hint.cpp

cl21: Fix test_api - query for device extensions in queue hint test

---

test_conformance/c11_atomics/test_atomics.cpp

Cast operand type to AddSubOperandType. See issue #325
This patch will make file test_atomics.cpp identical as in cl20 trunk.

c11_atomics: fix ambiguous call atomic_fetch_add

---

test_common/harness/errorHelpers.c
test_common/harness/kernelHelpers.c
test_common/harness/parseParameters.cpp
test_common/harness/parseParameters.h
test_conformance/compiler/test_build_helpers.c
test_conformance/spirv_new/main.cpp

These changes simplify the command line interface for controlling offline compilation, reduce the set of global variables that control offline compilation, and improve the naming of these variables.

cl21: Simplify command line and globals for offline compilation

---

test_common/harness/errorHelpers.c
test_common/harness/kernelHelpers.c
test_common/harness/parseParameters.cpp
test_common/harness/parseParameters.h
test_conformance/compiler/test_build_helpers.c

These changes simplify the command line interface for controlling offline compilation, reduce the set of global variables that control offline compilation, and improve the naming of these variables.

Simplify command line and globals for offline compilation

---

test_conformance/computeinfo/main.c

cl21: Test fix - Test computeinfo should know each existing OCL version

---

test_conformance/computeinfo/main.c

cl20: Test fix - Test computeinfo should know each existing OCL version

---

test_conformance/computeinfo/main.c

Test fix - Test computeinfo should know each existing OCL version

---

test_conformance/basic/test_progvar.cpp

Enable 64bit atomics extentions in order to use 64bit atomic types in
test_progvar_prog_scope_init and test_progvar_prog_scope_uninit.
See issue #369

cl21: test_basic/progvar: fix 64bit atomic types error

---

test_conformance/basic/test_progvar.cpp

Enable 64bit atomics extentions in order to use 64bit atomic types in
test_progvar_prog_scope_init and test_progvar_prog_scope_uninit.
See issue #369
This patch aligns test_progvar.cpp with cl20 branch.

master: test_basic/progvar: fix 64bit atomic types error

---

test_conformance/conversions/basic_test_conversions.c

These changes bring this code back in line with the 2.x branches.

cl12: Use cl types in conversion reference functions. (#383)

---

test_conformance/SVM/common.h

This patch fixes SVM run segfault, see issue #381

cl20: SVM: use InterlockedCompareExchange64 for 64-bit type

---

test_conformance/SVM/common.h
test_conformance/SVM/test_fine_grain_memory_consistency.cpp

Need to enable 64-bit atomic extensions in kernel source.
Use InterlockedCompareExchange64 for 64-bit type. See issue #381
This patch modifies test_fine_grain_memory_consistency.cpp to be the same as in cl20_branch.

master: Fix SVM if 64-bit atomic extensions are supported

---

test_conformance/SVM/common.h
test_conformance/SVM/test_fine_grain_memory_consistency.cpp

Need to enable 64-bit atomic extensions in kernel source.
Use InterlockedCompareExchange64 for 64-bit type. See issue #381
This patch modifies test_fine_grain_memory_consistency.cpp to be the same as in cl20_branch.

cl21: Fix SVM if 64-bit atomic extensions are supported

---

test_conformance/CMakeLists.txt

Aarch64 devices also need `-fsigned-char` but previously would not have hit this branch of the if statement.

cl12: Add aarch64 to system processor if statement in CMakeLists

---

test_conformance/conversions/CMakeLists.txt

This eliminates some warnings for a few compiler configurations.  This change
is not required on master branch.

cl12: Do not set -std=c99 on files that are set to be C++

---

test_common/harness/compat.h

M_PI is not part of C99 or C++ and thus aren't provided in all configurations.
This used to be handled in reference_math.c directly but was recently removed.
Just tweak the M_PI handling in the compatibility headers to restore builds.

cl12: Reintroduce M_PI compatibility

---

test_common/harness/compat.h

M_PI is not part of C99 or C++ and thus aren't provided in all configurations.
This used to be handled in reference_math.c directly but was recently removed.
Just tweak the M_PI handling in the compatibility headers to restore builds.

Reintroduce M_PI compatibility

---

test_conformance/compatibility/test_conformance/api/test_api_min_max.c

This was causing some tests to fail on 2.1 conformance
with : device version string does not match required format!
Signed-off-by: Oualid Khelifi <oualid.khelifi@arm.com>

cl21: Add 2.1 device version for compatibility conf

---

test_conformance/basic/test_enqueued_local_size.c

The test enqueued_local_size in test_basic used a
local work group size larger than the minimum max
supported work group size supported by some platforms.
This change checks the max and clamps to it if
requested size would be larger than supported.
Signed-off-by: Sam Laynton <sam.laynton@arm.com>

Check max work group size in test basic

---

CMakeLists.txt

This reduces the size of binaries, and makes the tests finish tiny
bit faster. The debug symbols can be enabled by passing to cmake one of:
-DCMAKE_BUILD_TYPE=Debug
-DCMAKE_BUILD_TYPE=RelWithDebInfo

Remove -g flag from conformance build

---

test_conformance/integer_ops/test_abs.c
test_conformance/integer_ops/test_absdiff.c
test_conformance/integer_ops/test_add_sat.c
test_conformance/integer_ops/test_popcount.c
test_conformance/integer_ops/test_sub_sat.c

The test harness already prints if the test passed, no need to duplicate
this information.

Remove redundant prints from integer_ops

---

test_conformance/api/test_api_min_max.c
test_conformance/compatibility/test_conformance/api/test_api_min_max.c

The test has been ignoring potential failures in memory allocations,
giving misleading error messages.
Add a simple check and return early if the allocation failed.

Handle failed memory allocations

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h
test_common/harness/testHarness.c
test_common/harness/testHarness.h
test_conformance/compatibility/test_common/harness/testHarness.c
test_conformance/compatibility/test_common/harness/testHarness.h
test_conformance/conversions/test_conversions.c
test_conformance/half/cl_utils.c
test_conformance/half/cl_utils.h
test_conformance/half/main.c
test_conformance/images/clCopyImage/main.cpp
test_conformance/images/clCopyImage/test_loops.cpp
test_conformance/images/clFillImage/main.cpp
test_conformance/images/clFillImage/test_loops.cpp
test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clGetInfo/test_loops.cpp
test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp
test_conformance/images/kernel_read_write/main.cpp
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp
test_conformance/images/samplerlessReads/main.cpp
test_conformance/images/samplerlessReads/test_loops.cpp
test_conformance/math_brute_force/main.c

This removes all the duplicated code from each test, and moves it to
test harness so that we have single place where this information is
printed.

Move printing sub-test information into test harness

---

test_conformance/half/Test_roundTrip.c
test_conformance/half/Test_vLoadHalf.c
test_conformance/half/Test_vStoreHalf.c

The test harness already prints if the test passed, no need to duplicate
this information.

Remove redundant prints from half

---

test_conformance/select/test_select.c

The local parsing of arguments in test_select.c throws away any unknown arguments.  Pass these to parseCustomParam() before the local argument parsing, so that the offline compilation options work as expected.

Fix parsing of offline compilation options in test_select

---

CMakeLists.txt

- remove compiler-specific options
- disable GNU extensions
- require C++11 and C99 for the whole code base

Set required language standards using CMake

---

test_conformance/printf/test_printf.c

The cl_arm_printf extension uses a call-back to tell the user-code
that some printf output has appeared from the execution of the CL
kernel.
The extsiting Printf tests assume output to stdout.
This change adds code to detect the cl_arm_printf extension, and an
implementation of the callback code to write to stdout.
Also fix a couple of formatting errors and don't "poll" when waiting
for events.
Signed-off-by: Mats Petersson <mats.petersson@arm.com>

Add support for arm printf extension.

---

test_conformance/math_brute_force/macro_unary.c

Fix for Khronos https://github.com/KhronosGroup/OpenCL-CTS/issues/249 where incoming errors are overwritten by exit block
Co-contributor jlewis-austin

Fix for Khronos https://github.com/KhronosGroup/OpenCL-CTS/issues/249

---

test_conformance/SVM/test_enqueue_api.cpp

This was the only combination that was not exercised.
Fixes #419

Add host/host test for clEnqueueSVMMemcpy

---

test_common/harness/compat.h
test_common/harness/msvc9.c

-- #ifdef out duplicate definitions
-- remove make_nan() dead code
Fixes #466

Fix inconsistent dll linking warnings for VS 2015/17 (#466)

---

test_conformance/images/clReadWriteImage/test_loops.cpp

Both allocations are made with new[].

Fix delete calls

---

test_conformance/contractions/contractions.c
test_conformance/conversions/test_conversions.c
test_conformance/math_brute_force/binary.c
test_conformance/math_brute_force/binaryOperator.c
test_conformance/math_brute_force/binary_i.c
test_conformance/math_brute_force/macro_binary.c
test_conformance/math_brute_force/macro_unary.c
test_conformance/math_brute_force/main.c
test_conformance/math_brute_force/unary.c
test_conformance/multiple_device_context/test_multiple_contexts.c
test_conformance/multiple_device_context/test_multiple_devices.cpp
test_conformance/printf/test_printf.c

In all these cases, the new entrypoint is not necessary. These
changes enable the tests to work or are a necessary step to get
the tests to work on an OpenCL 1.2 implementation.
While this may not be the final approach we want to solve this
specific compatibility issue, it also has the nice property of
reducing the diff with cl12_trunk until we merge.

Use clCreateCommandQueue when possible (in a few tests)

---

test_conformance/events/test_userevents.cpp

This code probably predates the move to the test framework and is
no longer useful.

Remove dead code from test_userevents

---

test_conformance/select/test_select.c

A test writer really shouldn't have to think about this...

select: don't forget to count tests when failing to create programs

---

test_common/harness/imageHelpers.cpp
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp

* Require exact for match normals, instead of arbitrary .005 relative error
* Add relaxation to allow 0 when float denormal is expected
* Refactor to use common validation function

Allow CL_FLOAT denorm flushing for write tests (#28)

---

test_conformance/api/CMakeLists.txt
test_conformance/api/main.c
test_conformance/api/procs.h
test_conformance/api/test_kernel_arg_info_compatibility.c
test_conformance/compatibility/test_conformance/api/CMakeLists.txt
test_conformance/compatibility/test_conformance/api/main.c

The diff between the compatibility and non-compatibility tests
is rather big. These tests should both be replaced by a new
maintainable one (see #522).
Contributes to #494.

Move kernel_arg_info compatibility test to the main api suite

---

test_conformance/images/clCopyImage/test_copy_3D_2D_array.cpp

test_3D_2D_array uses max limits of 3D images
for both 3D images and 2D_array.
This leads to testing of sizes larger than
2D array limits.
Use correct CL_MEM_OBJECT_IMAGE_TYPE to avoid
test-cases with invalid sizes.

Fix max limit query for test_3D_2D_array.

---

test_conformance/computeinfo/main.c

Currently capabilities with size_t type like CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE
are printed as signed values for example:
CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE == -881700864

cl12_trunk - computeinfo: Fix printing of size_t values

---

test_conformance/computeinfo/main.c

Currently capabilities with size_t type like CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE
are printed as signed values for example:
CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE == -881700864

computeinfo: Fix printing of size_t values

---

test_common/harness/imageHelpers.cpp
test_conformance/api/main.c
test_conformance/basic/main.c
test_conformance/clcpp/images/main.cpp
test_conformance/images/clCopyImage/main.cpp
test_conformance/images/clFillImage/main.cpp
test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_read_write/main.cpp
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/samplerlessReads/main.cpp
test_conformance/images/samplerlessReads/test_iterations.cpp
test_conformance/images/samplerlessReads/test_read_1D.cpp
test_conformance/images/samplerlessReads/test_read_1D_array.cpp
test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
test_conformance/images/samplerlessReads/test_read_2D_array.cpp
test_conformance/images/samplerlessReads/test_read_3D.cpp
test_conformance/profiling/main.c

This is the first step in trying to refactor gDeviceType, from comments in this Closed PR: https://github.com/KhronosGroup/OpenCL-CTS/pull/560
gDeviceType is now moved to imageHelper.cpp, and only in imageHelper.cpp/.h are they declared and defined.

Moved all instances of gDeviceType to imageHelper.cpp

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp
test_conformance/computeinfo/CMakeLists.txt
test_conformance/computeinfo/extended_versioning.cpp
test_conformance/computeinfo/main.c

Tests that the new queries work, and that what they return is consistent with
the information returned by the string-based queries.
Signed-off-by: Einar Hov <einar.hov@arm.com>

Add conformance tests for cl_khr_extended_versioning

---

test_common/harness/compat.h

Fixes #605.
Signed-off-by: Ben Ashbaugh <ben.ashbaugh@intel.com>

use strtok_s in place of strtok_r on Windows

---

test_common/harness/testHarness.cpp
test_common/harness/testHarness.h
test_conformance/contractions/contractions.c
test_conformance/conversions/test_conversions.c
test_conformance/half/main.c
test_conformance/math_brute_force/main.c
test_conformance/printf/test_printf.c

Moved all duplicate 'PrintArch' functions to testHarness.c
Replaced sysctl system call used in 'PrintArch' function with uname
system call
Signed-off-by: bhargavdas <bhargav_das@mentor.com>

Improved PrintArch functions (#595)

---

test_conformance/api/test_sub_group_dispatch.cpp

In the kernel source code for test_api sub_group_dispatch. Although subgroups
is a core feature there is no separate 2.1 language spec
so we use the 2.0 with the pragma.

Add missing cl_khr_subgroups pragma enable

---

test_conformance/allocations/allocation_functions.cpp

Add size_t overflow contingency code for 32-bit platforms where
max_width,max_height are 64k each. The code is modified to avoid
the overflowing multiplication.

Fix overflow in OpenCL 2.x CTS allocations tests

---

.appveyor.yml

Enables AppVeyor Windows builds, using similar build steps as for Travis Linux and OSX builds.  This will help to prevent, or at least identify, future Windows build breaks.
Example build output:
* https://ci.appveyor.com/project/bashbaug/opencl-cts
I've enabled builds for Visual Studio 2017, for 32-bit and 64-bit builds, for Release builds only, for now at least.  It's reasonably straightforward to add support for other builds if we so desire.
Fixes #11 (I think).

enable Appveyor Windows builds

---

CMakeLists.txt
test_conformance/CMakeLists.txt

This commit introduces a generic method of copying the opencl_conformance_tests_*.csv files during the build.
Fixes any unspecified files from being omitted during the copy process.

Copy all csv files during build.

---

test_common/harness/testHarness.cpp
test_common/harness/testHarness.h
test_conformance/SVM/main.cpp
test_conformance/allocations/main.cpp
test_conformance/contractions/contractions.cpp
test_conformance/conversions/test_conversions.cpp
test_conformance/device_execution/main.cpp
test_conformance/half/main.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/pipes/main.cpp
test_conformance/printf/test_printf.cpp
test_conformance/spirv_new/main.cpp
test_conformance/subgroups/main.cpp

The imageSupportRequired param is not needed in runTestHarnessWithCheck,
so just remove it.

Remove unused parameter

---

test_common/harness/testHarness.cpp

Android has linux/sysctl.h, but the functions that need it are not
used when targeting Android at the moment.

Do not include sys/sysctl.h on Android

---

test_common/CMakeLists.txt

The common library stopped being useful when we got rid of the
last compatibility suite.

Build a single library for the test harness

---

test_common/harness/alloc.h

posix_memalign requires alignment to be a power of two and a multiple
of sizeof(void*). All powers of two greater than sizeof(void*) are
multiples of sizeof(void*) so we only need to make sure sizeof(void*)
is the minimum value passed to posix_memalign.
Fixes #644

Fix align_malloc on Linux

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h
test_conformance/basic/test_readimage3d.cpp
test_conformance/images/clGetInfo/test_loops.cpp

This change adds checks to see if testing against an embedded implementation and if so, queries whether BGRA is supported or not.

Conditionally test BGRA in Basic readimage3d (#623)

---

CMakeLists.txt

The compiler test requires that directories named "includeTestDirectory" and "secondIncludeTestDirectory" are present with the binary.

Build: Ensure compilers required directory structure is present.

---

test_common/harness/testHarness.cpp
test_common/harness/testHarness.h
test_conformance/device_timer/main.cpp

Fix test skip handling while test initialization - device_timer

---

test_conformance/printf/test_printf.cpp

Printf was requiring only a 1.2 implementation. It should really be >= 1.2.

Update printf to query the correct device version

---

test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_retain.cpp

* Add `retain_mem_object_set_kernel_arg` to test that calling
clSetKernelArg with a cl_mem object does not retain that mem object
This issue came up from https://github.com/kpet/clvk/issues/157. @kpet requested I add a conformance test to cover it. Tested on a desktop implementation and clvk.

Add a test that clSetKernelArg does not retain the arg

---

test_conformance/api/test_zero_sized_enqueue.cpp

The test enqueues kernel and requests event associated with its
execution, but then never releases the event.

Fix memory leak in api - zero_sized_enqueue

---

test_conformance/basic/main.cpp
test_conformance/basic/procs.h
test_conformance/basic/test_explicit_s2v.cpp

The test does not do anything other than print a skipping test
message.
Fixes #438

Remove explicit_s2v_bool test

---

test_conformance/api/test_queries.cpp

Mask off vendor extensions when querying host command queue properties.
Khronos Bug: https://github.com/KhronosGroup/OpenCL-CTS/issues/642
Test Suite Affected: api

cl20: api:  Allow vendor flags

---

test_conformance/opencl_conformance_tests_12_quick.csv
test_conformance/opencl_conformance_tests_20_full.csv
test_conformance/opencl_conformance_tests_20_full_no_math_or_conversions.csv
test_conformance/opencl_conformance_tests_20_quick.csv
test_conformance/opencl_conformance_tests_21_full_spirv.csv
test_conformance/opencl_conformance_tests_21_legacy_wimpy.csv
test_conformance/opencl_conformance_tests_full.csv
test_conformance/opencl_conformance_tests_full_no_math_or_conversions.csv
test_conformance/opencl_conformance_tests_generate_spirv.csv
test_conformance/opencl_conformance_tests_math.csv
test_conformance/opencl_conformance_tests_quick.csv

The following test executable name changes have been made in the
conformance CSV files to match those found in the `test_conformance`
build directory:
* `contractions` -> `test_contractions`
* `computeinfo` -> `test_computeinfo`
* `bruteforce` -> `test_bruteforce`
* `Test_half` -> `test_half`
* `test_SVM` -> `test_svm`

Fix test executable names in CSV files

---

test_common/harness/kernelHelpers.cpp

Fixes #693 by returning `TEST_SKIP` instead of `TEST_FAIL` from the
`verifyImageSupport()` kernel helper function when
`checkForImageSupport()` reports the device does not support images.

Skip, don't fail, image tests on no image support

---

test_conformance/c11_atomics/test_atomics.cpp

The spec states that the minimum amount of local memory for embedded devices is 1KB. This change clamps work group sizes to 1024 for embedded devices, and sets the number of local variables per thread to 1.
Fixes #690.

c11_atomics: do not overallocate local memory for embedded devices #690.

---

test_common/harness/imageHelpers.cpp

An existing workaround on the max_image size calulcation that disallows
the width of an image to be less than 16 can stress the calculcation of
the remainder dimension to be less than 1.0 in size. In three dimentional
objects (3d,2d array) where one dimention is set to max and the other is
set to 16 there might not be enough space left for the 3rd one.
This workaround clamps the third dimension to a minimum of 1.0

Failure in copy_images max_images

---

test_common/harness/testHarness.cpp

Add function to set gDeviceType  on kernel_read_write tests(image_streams)
as the device type affects the way validation is performed in the test.

Global variable gDeviceType correctly set

---

test_conformance/generic_address_space/main.cpp
travis.sh

Where a device does not have to support this test, skip it.

Generic Address Space: Skip test on unsupported devices.

---

test_common/gl/setup_osx.cpp
test_common/gl/setup_win32.cpp
test_common/gl/setup_x11.cpp
test_common/harness/testHarness.cpp
test_conformance/api/test_api_min_max.cpp
test_conformance/api/test_clone_kernel.cpp
test_conformance/api/test_kernel_arg_info.cpp
test_conformance/api/test_kernel_arg_info_compatibility.cpp
test_conformance/api/test_queue_properties.cpp

(Patch1)
A number of tests have got their own code for checking the presence of
extensions. This change replaces that code with is_extension_available
function.
Contributes to #627
Change-Id: I8dd2233719aa8c84841ac61776437d7f6e3fafe6

is_extension_available used throughout code

---

test_common/harness/mt19937.h
test_conformance/basic/test_enqueue_map.cpp

- Introduce MTdataHolder
- Use BufferOwningPtr to manage allocations (fixes a few leaks in error cases)
- Introduce variable for common expressions
- Remove image format support check as the format is required by OpenCL 1.0
Contributes to #700

Clean up enqueue_map_{buffer,image} tests a bit

---

test_conformance/contractions/contractions.cpp
test_conformance/d3d11/harness.cpp
test_conformance/gl/test_images_write_common.cpp
test_conformance/gles/setup_egl.cpp
test_conformance/half/cl_utils.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/printf/test_printf.cpp
test_extensions/media_sharing/main.cpp
test_extensions/media_sharing/utils.cpp
test_extensions/media_sharing/utils.h

(Patch2)
A number of tests have got their own code for checking the presence of
extensions. This change replaces that code with is_extension_available
function.
Contributes to #627

Ensure is_extension_available is used where possible

---

test_conformance/api/test_queue_properties.cpp

enqueue_kernel was being run when the cl_khr_create_command_queue was *not* present. The test should only be run when the extension *is* present.
Regressed in 93e76a8a4a7d63b7e507ac72ae13a7e755cbda88.

API: Fixed condition based on is_extension_available.

---

test_common/harness/deviceInfo.cpp
test_common/harness/kernelHelpers.cpp

is_extension_available is modified to handle errors by throwing
exceptions.
Fixes #627

Add exceptions as errors in is_extension_available

---

test_conformance/printf/test_printf.cpp
test_conformance/printf/test_printf.h
test_conformance/printf/util_printf.cpp

The PR aims to fix issues identified in #673 and #675.
The reference results had two issues:
- They did not take into account the rounding mode of the device.
- Scientific notation results did not have trailing zero's, meaning that the exponent could be a single digit, despite the requirement being at least two digits.
This PR introduces runtime generated reference results for types with numerical representations (float, int, hex, etc) where a direct mapping to standard C99 printf is possible to execute on the CPU (as opposed to tests such as address space, vectors etc which cannot be directly mapped to C99 printf).

Printf fixes for reference results #673 #675

---

.travis.yml
check-format.sh

The default version on Xenial is old, and it doesn't understand the non-boolean version of `AllowShortIfStatementsOnASingleLine`.

Use clang-format-9 for Travis CI formatting checks

---

test_conformance/basic/test_enqueue_map.cpp

Don't update the memory passed as host_ptr with the correct result
and compute the reference result using a separate allocation so that
implementations that use copies to manage the host_ptr and never update
as part of map/unmap commands the memory pointed to by host_ptr fail
the test.
Rename initialData to hostPtrData for clarity.
Fixes #700

Make it possible for enqueue_map tests to catch more USE_HOST_PTR issues

---

test_common/harness/conversions.h
test_common/harness/imageHelpers.h
test_conformance/half/cl_utils.h
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp

* On mismatch, add relaxation when denormal half result is expected
* Refactor to use common validation function
* Clean up some diagnostics

Allow CL_HALF_FLOAT denorm flushing for write tests (#452)

---

test_conformance/api/test_bool.cpp
test_conformance/api/test_kernel_arg_info.cpp
test_conformance/api/test_kernel_arg_info_compatibility.cpp

Added some missing clProgramWrapper/clkernelWrapper, to avoid 
resource leaks.

Fix minor resource leaks in test_api.

---

test_common/harness/deviceInfo.cpp
test_common/harness/deviceInfo.h
test_common/harness/kernelHelpers.cpp

Removes need to use BufferOwningPtr to avoid memory leaks.
Contributes to #723.

Use std::string for get_device_*_string helpers

---

test_conformance/images/clCopyImage/CMakeLists.txt
test_conformance/images/clCopyImage/test_loops.cpp
test_conformance/images/clFillImage/CMakeLists.txt
test_conformance/images/clFillImage/test_loops.cpp
test_conformance/images/clGetInfo/CMakeLists.txt
test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clGetInfo/test_loops.cpp
test_conformance/images/clReadWriteImage/CMakeLists.txt
test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/common.cpp
test_conformance/images/common.h
test_conformance/images/kernel_image_methods/CMakeLists.txt
test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp
test_conformance/images/kernel_read_write/CMakeLists.txt
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/samplerlessReads/CMakeLists.txt
test_conformance/images/samplerlessReads/test_loops.cpp

This moves the filter_formats and get_format_list functions to a common
file. These functions were roughly the same, with an optional filtering
in some tests for testing mipmaps.

Remove duplicate format functions

---

CMakeLists.txt
test_common/harness/testHarness.cpp
test_conformance/SVM/main.cpp
test_conformance/device_execution/main.cpp
test_conformance/device_timer/main.cpp
test_conformance/generic_address_space/advanced_tests.cpp
test_conformance/generic_address_space/main.cpp
test_conformance/pipes/main.cpp
test_conformance/subgroups/main.cpp
test_conformance/workgroups/main.cpp

There were a number of tests against 2.2 that are clearer against 3.0.
Fixes #751

Accept OpenCL 3.0 in version parsing code and use where appropriate

---

check-format.sh

If a change is not added to an origin/master branch, an argument
can be used to specify the relevant branch name for the clang-format
comparison.

Add argument to specify branch for clang-format check

---

test_conformance/images/clFillImage/test_loops.cpp
test_conformance/images/common.cpp
test_conformance/images/common.h
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/samplerlessReads/test_loops.cpp

Some of the image code is needlessly copied over, where all you need is
a simple for loop.

Reduce code duplication in images

---

test_conformance/images/clCopyImage/test_copy_2D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D_3D.cpp
test_conformance/images/clCopyImage/test_copy_3D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/common.cpp
test_conformance/images/common.h

This function is duplicated across clCopyImages files, so just keep one
definition in common file, and get rid of the duplicated ones.

Remove duplicated random_in_ranges function

---

test_common/harness/deviceInfo.h
test_common/harness/testHarness.h
test_conformance/basic/test_progvar.cpp

Reproduction steps - Compile with flags `-Werror -Wreturn-type`

Fix return-type warnings with harness library and basic test

---

test_conformance/api/test_clone_kernel.cpp

* Remove the call to `clCreatePipe` in the `test_clone_kernel` test as
the result of this call (the pipe object) is unused. Further more
`clCreatePipe` is an optional API in OpenCL-3.0, so even if the pipe
object did have a use, support for this API would need to be queried in
the case of a OpenCL-3.0 driver where returning `CL_INVALID_OPERATION`
would be conformant behaviour. As it stands this test will incorrectly
fail for a 3.0 driver which does not support pipes.
* Correct comment regarding pipes and SVM since these features were not
actually tested in the source.

Remove `clCreatePipe` call from test_clone_kernel

---

test_conformance/api/test_api_min_max.cpp

OpenCL 3.0 version not found in test_api min_max_image_2d_hight and min_max_image_2d_width:
ERROR: device version string does not match required format! (returned: OpenCL 3.0 )

test_api - fix minRequiredDimension in case of new OpenCL version

---

test_conformance/computeinfo/extended_versioning.cpp
test_conformance/computeinfo/main.cpp

Besides the code reformatting and addressing compilation warnings, the main contribution is to ensure that computeinfo does not test for image types and flags that are not supported by the OpenCL version being tested.

Update computeinfo tests

---

test_conformance/basic/test_progvar.cpp
test_conformance/basic/test_work_item_functions.cpp

The "returning reference to temporary" one was introduced recently by #776. The other one showed up on my machine when enabling `-Werror`.

Fix warnings in basic suite

---

test_conformance/gl/test_images_write_common.cpp

Overwriting 'error' variable after check for Msaa/Depth support was clearing
the error counter incremented after failure in test_image_format_write. In
effect the test might return 0 even if there were errors.

Fix test_gl error reporting

---

test_conformance/pipes/test_pipe_info.cpp
test_conformance/pipes/test_pipe_limits.cpp
test_conformance/pipes/test_pipe_query_functions.cpp
test_conformance/pipes/test_pipe_read_write.cpp
test_conformance/pipes/test_pipe_readwrite_errors.cpp
test_conformance/pipes/test_pipe_subgroups.cpp

Fix various memory leaks around events.
Convert test to use supplied typewrappers
to avoid memory leaks. Also use error helper
functions to reduce code size.
Use stringstreams to synthesize kernel sources, and
raw c+11 string literals.

Mem-leaks from conformance pipes

---

CMakeLists.txt
test_common/harness/imageHelpers.cpp
test_conformance/api/test_null_buffer_arg.cpp
test_conformance/basic/test_work_item_functions.cpp
test_conformance/buffers/test_buffer_migrate.cpp
test_conformance/buffers/test_image_migrate.cpp
test_conformance/compiler/test_image_macro.cpp
test_conformance/computeinfo/main.cpp
test_conformance/half/cl_utils.h
test_conformance/images/clCopyImage/test_copy_2D_2D_array.cpp
test_conformance/images/clCopyImage/test_copy_2D_3D.cpp
test_conformance/images/kernel_image_methods/test_1D.cpp
test_conformance/images/kernel_image_methods/test_1D_array.cpp
test_conformance/images/kernel_image_methods/test_2D.cpp
test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp
test_conformance/images/kernel_read_write/test_common.h
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/reference_math.cpp
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp
test_conformance/spir/datagen.h
test_conformance/spir/main.cpp
test_conformance/spir/run_build_test.cpp

Fixes many of the errors this produces, and disables a handful that
didn't have solutions that were obvious (to me).

Enable -Werror for GCC/Clang builds

---

test_conformance/compiler/test_async_build.cpp

Check that the program build status can be queried from inside the
program completion callback, and also add a test to ensure that the
completion callback is called when the build fails.
This was clarified in the specification in [a recent change](https://github.com/KhronosGroup/OpenCL-Docs/pull/285).

Improve async build callback testing

---

test_conformance/math_brute_force/FunctionList.h
test_conformance/math_brute_force/Utility.h
test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binaryOperator.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/binary_two_results_i.cpp
test_conformance/math_brute_force/i_unary.cpp
test_conformance/math_brute_force/macro_binary.cpp
test_conformance/math_brute_force/macro_unary.cpp
test_conformance/math_brute_force/mad.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/ternary.cpp
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp
test_conformance/math_brute_force/unary_two_results_i.cpp
test_conformance/math_brute_force/unary_u.cpp

* The global variable `gTestFastRelaxed` has state which is used to
control the behaviour of the compiler flag `-cl-fast-relaxed-math` and
the precision testing of relaxed, fp32 and fp64 types. This is confusing
since the global variable is being set and read in different translation
units, making it very difficult to reason about the logic of the brute
force framework. It is particular difficult to follow since the global
variables is cached and then turned off in the case of fp32 and f64 in
order to use the same code path as relaxed testing, after it is then
turned back on.
* Remove uses of the global variable outside of `main.cpp` (the global
variable remains in use within `main.cpp` since it is a command line
option and used to turn of relaxed testing completely). Replace all uses
of …

Remove `gTestFastRelaxed` Dependencies in Brute Force

---

test_common/harness/conversions.h
test_conformance/half/cl_utils.h
test_conformance/math_brute_force/Utility.h

Is{Double,Float,Half}Subnormal function duplicates are currently in the codebase.
Fixes #511

Remove duplicate IsXSubnormal functions

---

test_common/harness/kernelHelpers.cpp

which contains
device specific information for the purposes of offline compilation. For
devices with images support `CL_DEVICE_IMAGE_SUPPORT=1` is printed,
otherwise `CL_DEVICE_IMAGE_SUPPORT=0`.

Add `CL_DEVICE_IMAGE_SUPPORT` to clDeviceInfo File

---

test_common/harness/cl_offline_compiler-interface.txt
test_common/harness/deviceInfo.cpp
test_common/harness/deviceInfo.h
test_common/harness/kernelHelpers.cpp

clDeviceInfo file for offline compilation testing.
`CL_DEVICE_NAME` and `CL_DEVICE_IMAGE_SUPPORT` which was missed from
this file when added.

Add `CL_DEVICE_NAME` to clDeviceInfo File

---

test_conformance/math_brute_force/main.cpp

* OpenCL versions before 2.0 do not have precision requirements for
reduced precision math.
* Skip reduced precision testing for devices with
versions < 2.0.

Skip Reduced Precision Testing

---

test_conformance/computeinfo/CMakeLists.txt
test_conformance/computeinfo/device_uuid.cpp
test_conformance/computeinfo/main.cpp

Basic conformance testing for the cl_khr_device_uuid extension.  Checks
that the ID queries return the right sizes and that the returned IDs are
stable across two calls to clGetDeviceInfo. If device LUID validity is
true, also checks that one and only one bit is set in the device node
mask.
Signed-off-by: Einar Hov <einar.hov@arm.com>

Tests for cl_khr_device_uuid

---

test_conformance/spir/run_services.cpp

Avoid missing non-void function return 
Fixes #846

Fix clang release build

---

test_conformance/math_brute_force/binary_i.cpp

This fixes the problem with reporting not precise enough information in case of verification failure.

Print hex values when reporting a failure

---

CMakeLists.txt
test_conformance/compiler/CMakeLists.txt
test_conformance/computeinfo/extended_versioning.cpp

* Move headers copy from top level CMakeLists.txt down to test_compile module as post-build copy
* Fix windows VS2015 build break
resolves #848

Arbitrary output directory support for compiler test build copies (#848)

---

.appveyor.yml
travis.sh

Until OpenCL 3.0 is finalized and supported by default in the OpenCL ICD loader, we need to pass a special flag to enable OpenCL 3.0 provisional APIs in the OpenCL ICD loader.  This will be necessary when we start testing OpenCL 3.0 APIs, such as in PR #857.
Fixes #859

build an OpenCL 3.0 ICD loader for CI builds

---

test_conformance/compiler/test_unload_platform_compiler.cpp

Test assumes all 3.0 devices support IL.

Test for IL support in unload_platform_compiler

---

test_conformance/SVM/test_migrate.cpp

This is a basic test to ensure that the new OpenCL 3.0 event command type `CL_COMMAND_SVM_MIGRATE_MEM` is properly returned for events from `clEnqueueSVMMigrateMem`.  This is not a test that exhaustively tests all event command types - see https://github.com/KhronosGroup/OpenCL-CTS/issues/613 - but it does ensure that we have coverage for the new event type added in OpenCL 3.0.
Note, I considered adding this test to [test_enqueue_api.cpp](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/SVM/test_enqueue_api.cpp) since it includes tests for the event command type for other SVM-related APIs, but I ultimately decided this was a better place for it because the other SVM APIs were introduced in OpenCL 2.0 and the SVM migrate API was included in OpenCL 2.1.  I'm happy to …

add OpenCL 3.0 test for CL_COMMAND_SVM_MIGRATE_MEM

---

test_common/harness/testHarness.cpp
test_conformance/spirv_new/main.cpp

This allows 1.2 implementations with the cl_khr_il_program extension to run them.

Set new minimum version for the spirv_new tests.

---

test_conformance/api/test_sub_group_dispatch.cpp

If sub groups aren't supported, skip the test.

Skip sub_group_dispatch.

---

test_common/harness/kernelHelpers.cpp

The offline compiler tries to compile the same source multiple times and
more importantly write out to the same filename. Adding a lock to prevent
simultaneous compilation solves this issue. This is particularly
noticeable in integer_ops testing.
Signed-off-by: Mats Petersson <mats.petersson@arm.com>

Add lock around offline-compiling

---

test_conformance/math_brute_force/FunctionList.cpp
test_conformance/math_brute_force/FunctionList.h
test_conformance/math_brute_force/Utility.cpp
test_conformance/math_brute_force/Utility.h
test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binaryOperator.cpp
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp

The crux of this issue revolved specifically around `exp`, which has differing base ULP requirements between `FULL_PROFILE` and `EMBEDDED_PROFILE`
This change adds an additional field to the `Func` struct, which allows the specification of an embedded, relaxed ULP requirement.
Given that this issue specifically revolves around `exp` the change to `Func` could be technically be dropped, but this approach allows us some flexibility in future if required and gives good separation between the profiles.
Fixes #760

Bruteforce - embedded, relaxed ulp requirements

---

test_conformance/images/kernel_read_write/test_loops.cpp

Fixes #872 
Currently the image streams test will fail if a device does not support `cl_khr_3d_image_writes`, but this extension is only required for OpenCL 2.x devices and is not required for OpenCL 1.x or OpenCL 3.0 devices.  So, rather than failing the test if 3D image writes are unsupported, we can simply skip these test cases instead.
Note that there is already a check that `cl_khr_3d_image_writes` is supported for OpenCL 2.x devices in `test_min_max_device_version`, so we don't need to add any similar checks here.

skip test cases rather than fail without cl_khr_3d_image_writes

---

test_conformance/basic/test_progvar.cpp

* Optionally skip the proram scope globa variable tests on OpenCL-3.0
devices that optionally do not support programscope global variables.

Optionally Skip `progvar` Tests

---

CMakeLists.txt
test_common/harness/rounding_mode.h
test_conformance/conversions/test_conversions.cpp

We have been seeing fails in `test_conversions` on x86_64 when converting to the following integer types from `cl_double` with a non-default rounding mode:
```
char_rtn_double
char_rtp_double
int_rtn_double
int_rtp_double
long_rtn_double
long_rtp_double
long_sat_rtn_double
long_sat_rtp_double
short_rtn_double
short_rtp_double
uchar_rtp_double
uint_rtp_double
ulong_rtp_double
ushort_rtp_double
```
After investigation it was discovered that `rint()` was incorrectly rounding `cl_double` inputs despite the rounding mode being correctly set using `fesetround()` beforehand. E.g  For 'char_rtn_double' `-3.5` was getting rounding to `-3.0` rather than `-4.0`.
This is a gcc issue https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92164 when using the builtin `rint()` implementation, rather than …

Specify GCC flag `-frounding-math` on x86

---

test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_api_consistency.cpp

This is the start of an "API Feature Consistency" test.  It is designed to ensure that when an optional OpenCL 3.0 API feature is not supported that other queries and APIs related to the feature can be called even if they return an error, and that when an optional OpenCL 3.0 API feature is supported, any other required features are also supported.
I've modeled this test very heavily on [Appendix H](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#opencl-3.0-backwards-compatibility) in the OpenCL 3.0 spec.  So far I have added API consistency tests for SVM, the memory consistency model, device-side enqueue, and pipes.
I am mostly looking for high-level feedback on the overall approach before adding additional API feature consistency checks.  I think most of the remaining checks …

API Feature Consistency Test, Part 1

---

test_common/harness/kernelHelpers.cpp
test_common/harness/kernelHelpers.h
test_conformance/basic/test_sizeof.cpp
test_conformance/basic/test_wg_barrier.cpp

* Dynamically select the `-cl-std` option on the basic `sizeof` and
`wg_barrier` tests to be one of `CL1.X`, `CL2.0` or `CL3.0`.
Use the most recent CL C standard supported on the device.

Dynamically Select `-cl-std` Option

---

test_common/harness/testHarness.cpp
test_conformance/conversions/test_conversions.cpp
test_conformance/half/main.cpp
test_conformance/printf/test_printf.cpp
test_conformance/select/test_select.cpp

glibc deprecated that header in version 2.30, and removed it in 2.32.

Only include sys/sysctl.h on for Apple

---

test_common/harness/errorHelpers.h
test_conformance/spirv_new/test_get_program_il.cpp

Added a test to check SpirV as an IL for programs built with IL
which includes a negative test for programs built without IL.
Added a test_fail macro.
Fixes #164

Adds testing for CL_PROGRAM_IL

---

test_conformance/device_execution/CMakeLists.txt
test_conformance/device_execution/enqueue_profiling.cpp
test_conformance/device_execution/main.cpp
test_conformance/device_execution/procs.h

The test checks profiling value CL_PROFILING_COMMAND_COMPLETE
compared to CL_PROFILING_COMMAND_END for two cases:
1) kernel with children with different levels of nesting
2) kernel without children

Add test for CL_PROFILING_COMMAND_COMPLETE

---

test_conformance/c11_atomics/common.h
test_conformance/c11_atomics/main.cpp
test_conformance/c11_atomics/test_atomics.cpp

This PR makes two changes.
1. The bare minimum capabilities for a device reporting >= 3.0 are tested during initialisation.
2. Tests are skipped for >= 3.0 devices where optional capabilities are tested.
Fixes #905

Memory consistency model optionality

---

test_conformance/compiler/test_pragma_unroll.cpp

* Stop assuming `-cl-std=CL2.0` for the `pragma unroll` test. This
allows us to run this test for OpenCL-3.0 drivers which optionally do
not support OpenCL C 2.0. Use the CTS framework to automatically select
the latest OpenCL C supported by the driver.

Automatically Select Latest `-cl-std` for `pragma unroll` Test

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

* Automatically select the `-cl-std` build option (stop assuming
`CL2.0`) in the `compiler_defines_for_extensions` test. This will allow
us to test `test_compiler_defines_for_extensions` with an OpenCL-3.0
driver that optionally might not support OpenCL C 2.0. Use the CTS
framework to automatically select the latest version of OpenCL C
supported by the device.

Automatically Select `-cl-std` for Compiler Defines Test

---

test_common/harness/kernelHelpers.cpp
test_common/harness/kernelHelpers.h
test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_queue.cpp

... as required by the OpenCL specification.
Also introduce a utility function to manage polling for changes
via a user-supplied function. Several tests we introduced lately
could have used this.

Test that queues are flushed by clReleaseCommandQueue

---

test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.cpp
test_conformance/non_uniform_work_group/TestNonUniformWorkGroup.h

* Pass `-cl-std=CL3.0` as build option for OpenCL-3.0.
* For an OpenCL-3.0 driver that optionally does not support non-uniform
work-groups round up the global size and run the tests with uniform
work-groups. This increases coverage and allows testing of the
`get_enqueued_local_size` builtin for uniform work-groups.

Change Behviour of non-uniform-work-group tests for OpenCL-3.0

---

test_common/harness/ThreadPool.cpp

In two places, a stray semicolon between an if statement and its body would cause the body to be executed unconditionally.  Fix this.

[MinGW] Fix if statements with stray semicolons after condition

---

test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp

Clamp input arrays to valid domains of several math functions being
tested.
Khronos Bug: https://github.com/KhronosGroup/OpenCL-CTS/issues/491
Test Suite Affected: bruteforce Subtests: sin, cos, sincos, reciprocal

[QC] cl20: bruteforce: Fix domains used in fast math mode. 

---

test_conformance/api/test_api_consistency.cpp

Fixes #933 
This PR aligns the CTS feature consistency test with the spec changes in https://github.com/KhronosGroup/OpenCL-Docs/pull/434, which requires that supporting a strong atomic memory order or a wide atomic scope also requires supporting all weaker memory orders and narrower scopes.

add checks for atomic feature consistency

---

test_conformance/api/test_api_consistency.cpp

Fixes #945.
This PR aligns the CTS feature consistency test with the spec changes in KhronosGroup/OpenCL-Docs#418, which originally specified that `clGetPipeInfo` should return `CL_INVALID_MEM_OBJECT` if pipes are not supported, but recently switched back to `CL_INVALID_MEM_OBJECT` for this case.

switch back to CL_INVALID_MEM_OBJECT for clGetPipeInfo

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h

Using RGB 32bpc textures causes the CTS to request 12-byte-aligned data, but aligned allocation methods require power-of-two alignments. Fixes #822.

Use power-of-two alignment values for allocating pixel data

---

test_conformance/api/test_queries_compatibility.cpp

Mask off vendor extensions when querying host command queue properties.

api:  Allow vendor flags

---

test_conformance/device_execution/enqueue_profiling.cpp

As per the spec CL_PROFILING_COMMAND_COMPLETE is required to
be equal to CL_PROFILING_COMMAND_END only on devices that
do not support the on-device queue.
For other cases it can be >= CL_PROFILING_COMMAND_END

device_execution: Modify the check in profiling subtest

---

test_common/harness/kernelHelpers.cpp
test_common/harness/kernelHelpers.h
test_conformance/basic/test_preprocessors.cpp

Currently, it fails if `__OPENCL_C_VERSION__` is greater than the version reported by `CL_DEVICE_OPENCL_C_VERSION`.
However (as of the 3.0 provisional spec), it's possible to have an OpenCL 3.0 device which reports 1.2 as the highest backwards-compatible version (from querying `CL_DEVICE_OPENCL_C_VERSION`), but supports 3.0 according to `CL_DEVICE_OPENCL_C_ALL_VERSIONS`.
In that case, this test should only fail if `__OPENCL_C_VERSION__ > CL_DEVICE_OPENCL_C_VERSION` _and_ `__OPENCL_C_VERSION__` is not in the list returned by `CL_DEVICE_OPENCL_C_ALL_VERSIONS`.
I took the liberty of refactoring some of the test to make use of some helper functions in `kernelHelpers.h`.

Ensure basic/test_basic/kernel_preprocessor_macros checks the OpenCL C version correctly for 3.0 onwards.

---

test_conformance/compiler/test_unload_platform_compiler.cpp

The called function (get_device_info_string) subtracts 1 from
length before returning it. Hence, to check for an empty string
(that the spec requires the implementation to return when
CL_DEVICE_IL_VERSION is not supported) the check should be modified
to check for empty and not length == 1

compiler: Modify the IL check code to check for an empty string

---

test_common/harness/errorHelpers.h
test_conformance/c11_atomics/common.cpp
test_conformance/c11_atomics/common.h
test_conformance/c11_atomics/main.cpp
test_conformance/c11_atomics/test_atomics.cpp

* Change setup code in `KernelCode()` to use `_explicit` builtin
variants that are common to both OpenCL-2.X and OpenCL-3.0.
* Only test optional supported builtin variants (`_explicit` signature
memory_order/scope) for OpenCL-3.0.
* Disable program scope global variable and generic address space tests
for a OpenCL-3.0 driver which does not optionally support these
features.

Change Behaviour of C11 Atomic Tests for OpenCL-3.0

---

test_conformance/c11_atomics/test_atomics.cpp

* The `atomic_flag` test assumes support for the `atomic_scope_device`
scope in the global scope test case. Since `atomic_scope_device` is
optional on an OpenCL-3.0 driver, this test should check for support and
skip otherwise.

Skip atomic_flag Test on for OpenCL-3.0 not Supporting Device Scope

---

test_conformance/spir/main.cpp

The current method of using `std::find(versions, 1.2f)` is unreliable due to
performing a floating point comparison.  I.e. on some compiles it will
spuriously report that the required version is missing and skip the tests.

Use Version type for cl_khr_spir extension version checks

---

test_conformance/c11_atomics/common.h

The code generated placed the next valid line on the end of a previous comment.

Fix kernel compilation issue in c11 atomics.

---

test_conformance/api/test_mem_object_properties_queries.cpp

Fixes #914.
This adds several test cases to the `buffer_properties_queries` and `image_properties_queries` tests, for standard buffers, sub-buffers, and standard images.  For these objects, there should be no queried properties, or in other words the queried property size should be zero.
I've also made a small improvement to compile the kernel once and reuse it for all sub-tests vs. compiling it for each sub-test, which should improve the test execution time slightly.

add a test case for subbuffer property queries

---

test_conformance/compiler/test_feature_macro.cpp

The test compiles programs to determine compiler support, which isn't possible
if the compiler is not available, so skip the test.

Skip feature macro consistency tests if no compiler is available

---

test_conformance/compiler/main.cpp

see #977 
Different implementations of the OpenCL ICD loader treat a null platform differently, so this case does not reliably return `CL_INVALID_PLATFORM` in all cases.  Temporarily disable this test while we discuss what the proper behavior should be.

temporarily disable the unload_invalid test case

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h
test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_min_image_formats.cpp
test_conformance/images/clGetInfo/test_loops.cpp
test_conformance/images/common.cpp
test_conformance/images/common.h

Fixes #639 
This PR separates the checks for required image formats into a dedicated test and adds checks for required read-and-write image formats.
I think I got this right, but it would be helpful to verify that these checks are correct in the following scenarios:
1. Embedded profile implementation.
2. OpenCL 1.2 implementation, especially without 3D image write support.
3. OpenCL 3.0 implementation without read-write image support.
Thanks!

add a new test to verify reported image formats

---

test_common/CMakeLists.txt
test_common/harness/featureHelpers.cpp
test_common/harness/featureHelpers.h
test_conformance/compiler/CMakeLists.txt
test_conformance/compiler/main.cpp
test_conformance/compiler/procs.h
test_conformance/compiler/test_opencl_c_versions.cpp

fixes #897 
fixes #899 
This PR adds a new test to the `compiler` suite.  There are four sub-tests:
1. For the value returned by `CL_DEVICE_OPENCL_C_VERSION`, first check that it meets any minimum API requirements.  If it does, verify that a program can be built using build options for the reported version and all previous versions.  This sub-test is not OpenCL 3.0-specific and can run on devices that support earlier OpenCL versions.
2. For the versions returned by `CL_DEVICE_OPENCL_C_ALL_VERSIONS`, verify that a program can be built using build options for each reported version.  Also, check that any required API versions are supported.  Since `CL_DEVICE_OPENCL_C_ALL_VERSIONS` is a new query in OpenCL 3.0, this sub-test is OpenCL 3.0-specific.
3. For some values returned by …

add checks for OpenCL C versions

---

test_common/harness/testHarness.cpp
test_common/harness/testHarness.h
test_conformance/submission_details_template.txt

- Remove the requirement to detail values for device queries and list
extensions in the submission template. They are printed by computeinfo.
- Require that tests skipped in accordance with the conformance
process be listed in the submission template.
- Remove support for OPENCL_1_0_DEVICE. This variable doesn't control
anything anymore and the updated conformance process no longer refers
to it.

Align with updated conformance process

---

test_conformance/images/samplerlessReads/test_read_1D_array.cpp

A previously created Image was not being released leading to a
memory leak.

samplerlessReads: Release Image to stop Memory Leak

---

test_conformance/compiler/test_feature_macro.cpp

Because a C++11 `std::equal` only iterates over the first container, and
matches with items in the second, if the second container contains more items
the check can still pass even though they're not identical.  Just use `==`
instead.
Fixes #979

Fail feature macro compare if compiler has more features than runtime

---

test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_pipe_properties_queries.cpp

Fixes #991 
This adds a simple test for CL_PIPE_PROPERTIES.  Since pipes can only be created with `NULL` properties there is only one sub-case to test.

add a basic test for CL_PIPE_PROPERTIES

---

test_conformance/computeinfo/extended_versioning.cpp

Fixes #992 
Adds testing for "extended versioning" for OpenCL 3.0 implementations in addition to implementations supporting `cl_khr_extended_versioning`.
This test assumes (and verifies) that the core enums are equal to the extension enums, so it only tests the queries once.
The only difference between the core functionality and the extension functionality is `CL_DEVICE_OPENCL_C_NUMERIC_VERSION_KHR`, which exists in the extension but was not promoted to a core feature, so this sub-test is skipped if the OpenCL 3.0 implementation does not also support `cl_khr_extended_versioning`.
Note that `CL_DEVICE_OPENCL_C_ALL_VERSIONS` is NOT tested by this test, but it is tested as part of `test_opencl_c_versions`.

added extended versioning tests for OpenCL 3.0

---

test_conformance/half/Test_vLoadHalf.cpp

For vLoadHalf test, the error was
not properly returned leading to
test success whereas it failed.

Fix error handling for test_half

---

test_common/harness/kernelHelpers.h
test_conformance/api/test_api_min_max.cpp
test_conformance/basic/test_arrayimagecopy3d.cpp
test_conformance/basic/test_imagearraycopy3d.cpp

Also fix PASSIVE_REQUIRE_* macros to report tests as skipped instead of passed.

Don't require support for 3D image writes in tests that don't need it

---

test_conformance/opencl_conformance_tests_full_binary.csv

This is identical to the SPIR-V spreadsheet, except spir-v mode is replaced by
binary mode.

Add a binary compile mode CSV

---

test_conformance/api/test_api_min_max.cpp

In embedded profile with cles_khr_int64 support,
the test did not consider the size of long. Thus the
number of argument computation was not coherent with
the returned CL_DEVICE_MAX_PARAMETER_SIZE leaded to test failure.
We fix this by taking the size of long when cles_khr_int64
is available in the device extension.

Fix api/test_api_min_max for Embedded profile with cles_khr_int64 support

---

test_conformance/images/kernel_read_write/test_iterations.cpp

Fix validate_float/half_write_results so that when nan/inf is
encountered on a channel, the rest of the channel values are still
considered for correctness.

Fix floating point validation in write_image tests

---

test_conformance/conversions/CMakeLists.txt
test_conformance/conversions/basic_test_conversions.cpp
test_conformance/conversions/test_conversions.cpp

The host compiler will not always calculate reference values
the same, depending on optimization level.  It generates
instructions that do not respond to CPU rounding mode in
the same way.  Use QCOM rounding mode emulation to correctly
calculate reference values on aarch64.
Change-Id: I4252786da85f77f8f8fcc79c2b8881a2c889e482

conversions: Use ARM emulation for aarch64

---

test_common/harness/testHarness.cpp

When running sub-tests explicitly on the command line and that sub-test
fails, the test harness returns `0` from `main()`. This is problematic
in automated testing environments as failed tests can be hidden.
This patch iterates over all the test results in the `resultTestList`
after all sub-tests have completed, if any of the tests failed a
non-zero value is returned from `parseAndCallCommandLineTests()` which
is then propagated up the call stack to `main()`.

Return a non-zero exit-code when a sub-test fails

---

test_conformance/compiler/procs.h
test_conformance/compiler/test_feature_macro.cpp
test_conformance/compiler/test_opencl_c_versions.cpp
test_conformance/compiler/test_unload_platform_compiler.cpp

Note that tests that use the compiler helper functions but won't work without a
compiler are in the `subtests_to_skip_with_offline_compiler` list.  I didn't do
that here because they tests directly use `clBuildProgram` etc directly,
because they're specifically testing it's behaviour in edge-cases.

Skip compiler unload/reload tests if compiler is not available

---

test_common/harness/errorHelpers.cpp
test_conformance/math_brute_force/Utility.h
test_conformance/math_brute_force/main.cpp

Modify the algorithm for calculating half precision ULP error so
that it duplicates the behaviour of the [single precision ULP algorithm](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/errorHelpers.c#L407-L428),
in regards to allowing overflow within the defined ULP error.
In the case where the test value is infinity, but the reference is
finite, pretend the test value is 63336.0 and calculate the ULP error
against that.
Encountered this while testing half precision `hypot()` in [PR !529](https://github.com/KhronosGroup/OpenCL-CTS/pull/529),
for inputs `hypot(-48864.0, 43648.0)` which has reference
`65519.755799`. With RTE rounding this only just rounds to `65504` as half,
and returning INF is currently infinite ULP error. Using the leniency
introduced by this …

Permit half overflow within allowable ULP

---

test_common/harness/errorHelpers.cpp

The following tests make calls to `clCompileProgram` or
`clBuildProgram` and therefore require a compiler in the runtime:
* `unload_repeated`
* `unload_compile_unload_link`
* `unload_build_unload_create_kernel`
* `unload_link_different↩`
* `unload_build_threaded`
* `unload_build_info`
* `unload_program_binaries`
Skip these tests if no compiler is present in the runtime.

Skip Compiler Unload Tests in Binary Mode

---

test_conformance/basic/test_async_strided_copy.cpp

Fix issue https://github.com/KhronosGroup/OpenCL-CTS/issues/943.
Free buffer while verify failed.
Signed-off-by: Qinyu.Tang <qinyu.tang@verisilicon.com>

Fix memory leak of test_basic (#943)

---

test_conformance/api/test_zero_sized_enqueue.cpp

If I understand correctly, `test_conformance/api/test_zero_sized_enqueue.cpp` tries to execute a kernel with an NDRange that contains a 0, and asserts whether the output buffer was changed to anything other than 0.
Originally, the kernel was copying data from an input buffer to "clobber" the output buffer. However, this input buffer was initialised, so this test wouldn't fail reliably. This PR removes the input buffer completely, replacing the copy operation in the kernel with just `dst[i] = 1;`. I believe this has the same effect.

Remove uninitialised input buffer from test_zero_sized_enqueue

---

test_conformance/compiler/test_build_helpers.cpp

This is so that only one statement needs to be updated if the checks need to be changed in future.

Minor refactoring of CL_PROGRAM_SOURCE tests

---

test_common/harness/testHarness.cpp

"control reaches end of non-void function"

Fix build warning/error introduced by 8d443029

---

test_conformance/images/clReadWriteImage/main.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/clReadWriteImage/test_read_1D.cpp
test_conformance/images/clReadWriteImage/test_read_1D_array.cpp
test_conformance/images/clReadWriteImage/test_read_2D.cpp
test_conformance/images/clReadWriteImage/test_read_2D_array.cpp
test_conformance/images/clReadWriteImage/test_read_3D.cpp

Remove unused code in clReadWriteImage

---

test_conformance/images/clGetInfo/main.cpp
test_conformance/images/clGetInfo/test_1D.cpp
test_conformance/images/clGetInfo/test_1D_2D_array.cpp
test_conformance/images/clGetInfo/test_2D.cpp
test_conformance/images/clGetInfo/test_3D.cpp
test_conformance/images/clGetInfo/test_loops.cpp

Remove unused code in clGetInfo

---

test_conformance/images/clFillImage/main.cpp
test_conformance/images/clFillImage/test_fill_1D.cpp
test_conformance/images/clFillImage/test_fill_1D_array.cpp
test_conformance/images/clFillImage/test_fill_2D.cpp
test_conformance/images/clFillImage/test_fill_2D_array.cpp
test_conformance/images/clFillImage/test_fill_3D.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp
test_conformance/images/clFillImage/test_loops.cpp

Remove unused code in clFillImage

---

test_common/harness/errorHelpers.cpp

calls to `create_single_kernel_helper_create_program` and fails when the
call doesn't return `CL_SUCCESS` which will happen when the offline
compiler fails to compile the kernel which is deliberately supposed to
fail compilation in this test.

Skip `features_macro` Test in Offline Mode

---

test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_kernel_private_memory_size.cpp

* Add the test source to `CMakeLists.txt`
* Register the test with the api suite
* Fix build error in host code
* Use `uint` instead of `ulong` (not all devices support 64-bit types)

Fixes for kernel private memory size test

---

test_conformance/images/kernel_image_methods/main.cpp
test_conformance/images/kernel_image_methods/test_1D.cpp
test_conformance/images/kernel_image_methods/test_1D_array.cpp
test_conformance/images/kernel_image_methods/test_2D.cpp
test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_3D.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp

Remove unused code in kernel_image_methods

---

test_conformance/images/kernel_read_write/main.cpp
test_conformance/images/kernel_read_write/test_common.h
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp

Some definitions got moved to test_common.h, as these are duplicated
across few files. There's further opportunity to improve code reuse
via test_common.h, but that's for future patch.

Remove unused code in kernel_read_write

---

test_conformance/images/samplerlessReads/main.cpp
test_conformance/images/samplerlessReads/test_iterations.cpp
test_conformance/images/samplerlessReads/test_loops.cpp
test_conformance/images/samplerlessReads/test_read_1D.cpp
test_conformance/images/samplerlessReads/test_read_1D_array.cpp
test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
test_conformance/images/samplerlessReads/test_read_2D_array.cpp
test_conformance/images/samplerlessReads/test_read_3D.cpp

Remove unused code in samplerlessReads

---

test_conformance/buffers/test_buffer_fill.cpp
test_conformance/buffers/test_buffer_mem.cpp
test_conformance/buffers/test_buffer_read.cpp
test_conformance/buffers/test_buffer_write.cpp

Local work groups are not relevant to these tests.
Fixes #1019

Remove code under USE_LOCAL_WORK_GROUP

---

test_conformance/images/kernel_image_methods/test_1D.cpp
test_conformance/images/kernel_image_methods/test_1D_array.cpp
test_conformance/images/kernel_image_methods/test_2D.cpp
test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_3D.cpp
test_conformance/images/kernel_image_methods/test_loops.cpp

Pass the right flags to the tests that create images to ensure valid
usage.
Fixes issue #330

Fix write-only image tests in kernel_image_methods (#330)

---

test_conformance/basic/test_rw_image_access_qualifier.cpp

Change from: 
CL_DEVICE_MAX_READ_IMAGE_ARGS to 
CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS

Fix support verification for read write images

---

test_conformance/compiler/test_unload_platform_compiler.cpp

The `get_device_il_version_string()` function throws an exception if the
device does not support the `CL_DEVICE_IL_VERSION` query, so don't call
this unless the version is recent enough.

Fix build_with_il on devices older than 2.1

---

test_conformance/math_brute_force/FunctionList.cpp
test_conformance/math_brute_force/reference_math.cpp
test_conformance/math_brute_force/reference_math.h
test_conformance/math_brute_force/unary.cpp

* Add relaxed tests for functions (in an implementation that uses
derived functions) that define an absolute ULP precision requirement,
but were not tested in the current conformance suite
* acos
* asin
* atan
* cospi
* sinpi
* log10
I've tested these changes (via clvk) on an AMD, Arm, Nvidia and Qualcomm gpu.

Add more relaxed math conformance tests

---

test_conformance/api/test_api_consistency.cpp

Do not use NULL svm pointers.
Add a check for clEnqueueSVMMigrateMem.
Signed-off-by: Filip Hazubski <filip.hazubski@intel.com>

Correct test_consistency_svm

---

test_conformance/buffers/test_buffer_fill.cpp
test_conformance/buffers/test_buffer_map.cpp
test_conformance/buffers/test_buffer_read.cpp
test_conformance/buffers/test_buffer_write.cpp

Extracts program and kernel compilation from mem_flags loop
as they were being recompiled unnecessarily.
Fixes #1020

Reduce number of compilations in buffer suite

---

test_conformance/select/util_select.cpp

If `memcmp` fails, fall back to looping through the result buffer to find the incorrect result.
Improves wimpy runtime by ~26% on my test device.
Starts to address points made in #1054

Use memcmp for select verification.

---

test_common/harness/testHarness.cpp
test_common/harness/testHarness.h
test_common/harness/threadTesting.h

TEST_SKIPPED_ITSELF was originally located in
threadTesting.h but this no longer makes sense.
This change moves the definition to the test_status
struct in testHarness so that it can be used in the same
way that test_status' can be used.

Move TEST_SKIPPED_ITSELF to test_status in testHarness

---

check-format.sh

Travis CI used clang-format-9 to test changes. Attempting to update the Github Actions to use the same

Use clang-format-9 binary in Github Actions

---

test_conformance/compiler/test_build_options.cpp

This kernel is used to test various compiler options including `-Werror`. Some compilers produce a warning about the implicit conversion which results in this test failing when `-Werror` is used.
This first commit contains the trivial change. The second is just formatting.

Fix implicit int->float warning inside kernel

---

test_conformance/api/test_clone_kernel.cpp

In this test we repeated call create_single_kernel_helper
to create different kernels but reuse the same clProgramWrapper.
create_single_kernel_helper() creates a new program each time it
is called, creating a new reference on the underlying context.
When the test ends, the program is released (as it should when
using the clProgramWrapper), however there are multiple program
objects attached to the context resulting in reference leak errors.

Fix Context Leak in api:clone_kernel

---

test_common/harness/errorHelpers.cpp
test_common/harness/imageHelpers.cpp
test_conformance/api/test_create_kernels.cpp
test_conformance/api/test_null_buffer_arg.cpp
test_conformance/api/test_retain.cpp
test_conformance/api/test_retain_program.cpp
test_conformance/d3d10/harness.cpp
test_conformance/d3d11/harness.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/printf/test_printf.cpp
test_conformance/spirv_new/test_cl_khr_spirv_no_integer_wrap_decoration.cpp
test_conformance/spirv_new/test_op_fmath.cpp
test_conformance/spirv_new/test_op_vector_times_scalar.cpp

Uses of clCreateKernel following create program helper
functions, have been incorporated into
create_single_kernel_helper when suitable.
Contributes #31

Using helper functions for clCreateKernel

---

test_conformance/computeinfo/CMakeLists.txt
test_conformance/computeinfo/conforming_version.cpp
test_conformance/computeinfo/main.cpp

Adding test to validate value returned from clGetDeviceInfo with
CL_DEVICE_LATEST_CONFORMANCE_VERSION_PASSED.
Fixes #993

Validate CL_DEVICE_LATEST_CONFORMANCE_VERSION_PASSED

---

test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/clReadWriteImage/test_read_1D.cpp
test_conformance/images/clReadWriteImage/test_read_1D_array.cpp
test_conformance/images/clReadWriteImage/test_read_2D.cpp
test_conformance/images/clReadWriteImage/test_read_2D_array.cpp
test_conformance/images/clReadWriteImage/test_read_3D.cpp

Test was querying for supported images with CL_MEM_WRITE_ONLY flag, but
always used CL_MEM_READ_ONLY to create images.
Fixes issue #328

Use the right flags when creating images (#328)

---

test_conformance/buffers/test_buffer_fill.cpp

These events are now using clEventWrapper to manage their lifetime. That change was made in #1082.

Remove invalid clReleaseEvent calls

---

test_conformance/images/samplerlessReads/test_loops.cpp

The test was trying to create read_write image with read_only formats.
Make it use common image formats for both read_only and read_write
flags when creating images.
Fixes issue #329

Fix samplerlessReads read_write (#329)

---

test_conformance/gl/test_buffers.cpp
test_conformance/gl/test_image_methods.cpp

In OpenCL spec 1.1:
"Prior to calling clEnqueueAcquireGLObjects, the application must ensure that any pending GL
operations which access the objects specified in mem_objects have completed. This may be
accomplished portably by issuing and waiting for completion of a glFinish command on all GL
contexts with pending references to these objects."
Without this change, there were data errors in a busy GPU or faster CPU.
Signed-off-by: Alex Xie <AlexBin.Xie@amd.com>

Use glFinish to replace glFlush

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h
test_conformance/images/clCopyImage/test_loops.cpp
test_conformance/images/clFillImage/test_loops.cpp
test_conformance/images/clGetInfo/test_loops.cpp
test_conformance/images/clReadWriteImage/test_loops.cpp
test_conformance/images/common.cpp
test_conformance/images/common.h
test_conformance/images/kernel_image_methods/test_loops.cpp
test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_loops.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp
test_conformance/images/samplerlessReads/test_iterations.cpp
test_conformance/images/samplerlessReads/test_loops.cpp
test_conformance/images/samplerlessReads/test_read_1D.cpp
test_conformance/images/samplerlessReads/test_read_1D_array.cpp
test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp
test_conformance/images/samplerlessReads/test_read_2D_array.cpp
test_conformance/images/samplerlessReads/test_read_3D.cpp
test_conformance/images/testBase.h

Avoids memory deallocation issues and generally simplifies the code.
There's a fair bit of churn due to adding lots of `const` qualifiers to function parameters, but it's largely mechanical. The first commit contains the changes, the second is just formatting; I'd recommend reviewing just the first.
Fixes #723

Use std::vector for format lists in images suite

---

test_conformance/mem_host_flags/C_host_memory_block.h

Fixes ASan issues flagged in the mem_host_flags suite.
First commit is the trivial change, second is just formatting.

Use delete[] to deallocate after new[]

---

test_conformance/computeinfo/conforming_version.cpp

Previously this file used the auto keyword to
declare a string. This can cause compilation
issues when used in a later function.

Fix compilation issues for conforming_version.cpp

---

test_conformance/images/clCopyImage/test_copy_generic.cpp

* Use  get_image_size() for size calculations. 
* Report Image size in MBs on failure
* Add clFinish to ensure the trailing unmap call completes

Minor fixes for clCopyImage.

---

test_conformance/math_brute_force/binary_two_results_i.cpp

Reformat code using clang-format.
This is similar to https://github.com/KhronosGroup/OpenCL-CTS/pull/1117/commits/7a391f8b2d5f68876826b3b9dcb4f0c4d032f99b in #1117.

Remove unnecessary scope

---

test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binaryOperator.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/binary_two_results_i.cpp
test_conformance/math_brute_force/i_unary.cpp
test_conformance/math_brute_force/macro_binary.cpp
test_conformance/math_brute_force/macro_unary.cpp
test_conformance/math_brute_force/mad.cpp
test_conformance/math_brute_force/ternary.cpp
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp
test_conformance/math_brute_force/unary_two_results_i.cpp
test_conformance/math_brute_force/unary_u.cpp

Remove unnecessary declarations.

Make functions local to translation unit

---

test_conformance/basic/test_vector_swizzle.cpp

Use vstore3 to ensure padding is not overwritten in destination buffer.
Fixes #1120

Fix test_vector_swizzle overwrite of padding of 3-element vectors

---

test_common/harness/errorHelpers.cpp
test_common/harness/errorHelpers.h
test_common/harness/testHarness.cpp
test_common/harness/testHarness.h
test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/negative_platform.cpp
test_conformance/api/procs.h

This change introduces a negative test for clGetPlatformInfo
as well as changes to the Harness to help with
other negative tests.

Implement Negative Test for Platform Layer Functions

---

test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binaryOperator.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/binary_two_results_i.cpp
test_conformance/math_brute_force/i_unary.cpp
test_conformance/math_brute_force/macro_binary.cpp
test_conformance/math_brute_force/macro_unary.cpp
test_conformance/math_brute_force/mad.cpp
test_conformance/math_brute_force/ternary.cpp
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp
test_conformance/math_brute_force/unary_two_results_i.cpp
test_conformance/math_brute_force/unary_u.cpp

The main goal is to reduce code differences in `math_brute_force`. This will allow refactoring and reducing code duplication later, and identify undesired differences between tests (including bugs).
The changes proposed in this PR should not change any existing behaviour. They were identified iteratively using `nvim -d file1 file2 file3 ...`. See also the commit messages for additional details.

Reduce difference between files in math_brute_force

---

test_conformance/basic/test_basic_parameter_types.cpp

In preparation of adding a new parameter type test, clang-format test_basic_parameter_types.cpp and use raw string literals to make kernel code more readable.

NFC: clang-format test_basic_parameter_types.cpp

---

test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/binary_two_results_i.cpp
test_conformance/math_brute_force/i_unary.cpp
test_conformance/math_brute_force/macro_binary.cpp
test_conformance/math_brute_force/macro_unary.cpp
test_conformance/math_brute_force/mad.cpp
test_conformance/math_brute_force/ternary.cpp
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp
test_conformance/math_brute_force/unary_two_results_i.cpp
test_conformance/math_brute_force/unary_u.cpp

Improve math_brute_force kernels by consistently using size_t to store the result of get_global_id().

Remove undesired conversions from size_t to int

---

test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binaryOperator.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/binary_two_results_i.cpp
test_conformance/math_brute_force/macro_binary.cpp

When creating sub-buffers in math_brute_force, the wrong variables were checked for runtime errors. This patch fixes this and ensures the logs are consistent.

Fix typo in error handling

---

test_conformance/math_brute_force/main.cpp

I ran into this issue when trying to run the math tests on my custom OpenCL implementation supporting the embedded profile.

Fix compilation error in rtz mode detection

---

test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binaryOperator.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/macro_binary.cpp
test_conformance/math_brute_force/macro_unary.cpp
test_conformance/math_brute_force/mad.cpp
test_conformance/math_brute_force/unary.cpp

Another fairly trivial change for math_brute_force that will allow us to reduce code duplication in the long run.
---
Moves `if (!gSkipCorrectnessTesting)` in binary_i.cpp to follow structure of binary.cpp, unary.cpp, macro_unary.cpp and macro_binary.cpp.
Other non-semantic changes include adding/removing new lines and updating comments.

Reduce difference between files

---

test_conformance/math_brute_force/binary.cpp
test_conformance/math_brute_force/binary_i.cpp
test_conformance/math_brute_force/binary_operator.cpp
test_conformance/math_brute_force/binary_two_results_i.cpp
test_conformance/math_brute_force/function_list.cpp
test_conformance/math_brute_force/i_unary.cpp
test_conformance/math_brute_force/macro_binary.cpp
test_conformance/math_brute_force/macro_unary.cpp
test_conformance/math_brute_force/mad.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/reference_math.cpp
test_conformance/math_brute_force/sleep.cpp
test_conformance/math_brute_force/ternary.cpp
test_conformance/math_brute_force/test_functions.h
test_conformance/math_brute_force/unary.cpp
test_conformance/math_brute_force/unary_two_results.cpp
test_conformance/math_brute_force/unary_two_results_i.cpp
test_conformance/math_brute_force/unary_u.cpp
test_conformance/math_brute_force/utility.cpp

Move function declarations to a new header file, with relevant existing documentation.
---
This will allow further cleanups to be easier, such as splitting files to identify undesired differences between float and double versions of the tests.

Regroup vtbl definitions to one translation unit

---

test_conformance/math_brute_force/binary_two_results_i.cpp

This issue was introduced in 8ad1088a (Reduce difference between files in math_brute_force (#1138), 2021-02-10).
Cf https://github.com/KhronosGroup/OpenCL-CTS/pull/1166#issuecomment-781143569
CC @gwawiork

Fix incorrect use of kernel parameter

---

.github/workflows/presubmit.yml
presubmit.sh

A bit cleaner than the written-in-a-haste-to-get-ci-going-again current approach.

ci: move code format check out of the main job/script

---

test_conformance/math_brute_force/binary_i_double.cpp

This relates to my comment: https://github.com/KhronosGroup/OpenCL-CTS/pull/1169#discussion_r578424495.
Because `specialValuesInt2Count < specialValuesIntCount` (when correctly computed), there was no out-of-bound access when running the tests. This also means additional cases will be covered now that the typo is fixed.

Fix typo in array size computation

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h
test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp

clCopyImage and clFillImage contain near-duplicate code for logging of
pixel difference errors.  Move this into imageHelpers.

Deduplicate logging of pixel differences

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/function_list.cpp

Remove unnecessary functions. The first commit adds some asserts to prove that the assumptions used by the second commit are correct.

Fold functions for nextafter

---

test_conformance/images/kernel_image_methods/test_2D_array.cpp
test_conformance/images/kernel_image_methods/test_3D.cpp

Use cl_ulong temporary values for row/slice_pitch.

Fix possible size_t overflow in 32-bit builds.

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_i_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp
test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/binary_two_results_i_float.cpp
test_conformance/math_brute_force/i_unary_double.cpp
test_conformance/math_brute_force/i_unary_float.cpp
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_binary_float.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/macro_unary_float.cpp
test_conformance/math_brute_force/mad_double.cpp
test_conformance/math_brute_force/mad_float.cpp
test_conformance/math_brute_force/ternary_double.cpp
test_conformance/math_brute_force/ternary_float.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp
test_conformance/math_brute_force/unary_two_results_double.cpp
test_conformance/math_brute_force/unary_two_results_float.cpp
test_conformance/math_brute_force/unary_two_results_i_double.cpp
test_conformance/math_brute_force/unary_two_results_i_float.cpp
test_conformance/math_brute_force/unary_u_double.cpp
test_conformance/math_brute_force/unary_u_float.cpp

This further reduces differences between files.
Improve format.
The `binary_operator` tests are left untouched by this commit as they require some non-automatic changes.

Reduce differences by using common names

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/i_unary_double.cpp
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/mad_double.cpp
test_conformance/math_brute_force/ternary_double.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_two_results_double.cpp
test_conformance/math_brute_force/unary_two_results_i_double.cpp
test_conformance/math_brute_force/unary_u_double.cpp

This patch removes the following dead loop:
```c++
for (; j < gMaxVectorSizeIndex; j++) vlog("\t     -- ");
```
which is right after this loop:
```c++
for (j = gMinVectorSizeIndex; j < gMaxVectorSizeIndex; j++) {
// ... no breaks ...
}
```
in other tests.

Remove trivially dead code

---

test_common/harness/testHarness.cpp

When invoking for example
test_c11_atomics test-that-does-not-exist
`parseAndCallCommandLineTests()` would attempt to dereference `resultTestList` which is still a null pointer.

Do not dereference null pointer for no matching tests

---

test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp

Make signature of `BuildKernel` more consistent across tests: now only two variants exist:
```cpp
int BuildKernel(const char *name, int vectorSize, cl_kernel *k,
cl_program *p, bool relaxedMode)
```
or
```cpp
int BuildKernel(const char *name/symbol, int vectorSize,
cl_uint kernel_count, cl_kernel *k, cl_program *p,
bool relaxedMode)
```

Use the same kernel name for all tests

---

test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/binary_two_results_i_float.cpp

Reduce differences between tests by ensuring all these operations are non-blocking.

Improve consistency of clEnqueueWriteBuffer operations

---

test_conformance/compiler/test_build_options.cpp

These are causing test failures for non-Apple implementations of
OpenCL running on macOS.

Remove compiler options that are specific to Apple

---

test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp

To reduce differences between tests, remove APPLE specific code from unary tests as no other test have similar logic.
Ensure gMeasureTimes is consistently initialised regardless of operating systems to ensure a consistent command line interface.
The remaining APPLE specific pieces of code relate either to include paths, or to the implementation of PreventSleep(), ResumeSleep() and GetTime(). Those are not removed in this commit.

Remove unnecessary APPLE specific code

---

test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/utility.h

Make some global variables local to function, or remove them when actually dead.
@EwanC: As hinted in #1211, this removes `gSimdSize` and others. :-)

Make variables and functions local to translation unit

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_i_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_binary_float.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/macro_unary_float.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp

Use one loop to read buffers from device, with the last read operation blocking until complete.
This pattern cannot be elegantly refactored just yet, mainly for two reasons:
- Some tests use goto statements to clean their resources.
- Some tests (not modified in this patch) only use blocking read operations.
Once code is further unified, this pattern can be refactored into a helper function.

Fold code into loop

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_i_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp
test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/binary_two_results_i_float.cpp
test_conformance/math_brute_force/i_unary_double.cpp
test_conformance/math_brute_force/i_unary_float.cpp
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_binary_float.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/macro_unary_float.cpp
test_conformance/math_brute_force/mad_double.cpp
test_conformance/math_brute_force/mad_float.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/ternary_double.cpp
test_conformance/math_brute_force/ternary_float.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp
test_conformance/math_brute_force/unary_two_results_double.cpp
test_conformance/math_brute_force/unary_two_results_float.cpp
test_conformance/math_brute_force/unary_two_results_i_double.cpp
test_conformance/math_brute_force/unary_two_results_i_float.cpp
test_conformance/math_brute_force/unary_u_double.cpp
test_conformance/math_brute_force/unary_u_float.cpp
test_conformance/math_brute_force/utility.h

`gWimpyBufferSize` is never modified and is actually not used to modify the number of tests -- `gWimpyReductionFactor` is used for that purpose by some tests, but not all.
This patch removes this unnecessary global variable to simplify the codebase, and reduce differences between tests.

Fold constant global variable

---

test_conformance/api/negative_platform.cpp

Part of the negative CTS test for clGetPlatformInfo
incorrectly tested with a NULL platform. As this is a
special case it meant that the test was not correct.
This change removes the incorrect part of the test so that
it conforms with the OpenCL specification.

Remove NULL Platform Check for Negative clGetPlatformInfo (#1222)

---

test_conformance/math_brute_force/CMakeLists.txt

Remove CMake statements that have no effect in math_brute_force.
`set_source_files_properties` without a list of files has no effect.
When `MODULE_NAME` is `FOO`, `set_source_files_properties(${MODULE_NAME}_SOURCES ...)` sets the properties of "FOO_SOURCES", not of the files listed in the variable named `FOO_SOURCES`.

Remove dead CMake code

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_i_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp
test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/binary_two_results_i_float.cpp
test_conformance/math_brute_force/i_unary_double.cpp
test_conformance/math_brute_force/i_unary_float.cpp
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_binary_float.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/macro_unary_float.cpp
test_conformance/math_brute_force/mad_double.cpp
test_conformance/math_brute_force/mad_float.cpp
test_conformance/math_brute_force/ternary_double.cpp
test_conformance/math_brute_force/ternary_float.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp
test_conformance/math_brute_force/unary_two_results_double.cpp
test_conformance/math_brute_force/unary_two_results_float.cpp
test_conformance/math_brute_force/unary_two_results_i_double.cpp
test_conformance/math_brute_force/unary_two_results_i_float.cpp
test_conformance/math_brute_force/unary_u_double.cpp
test_conformance/math_brute_force/unary_u_float.cpp

Make variables local to loops, with appropriate types. These variables are not read after the loop without being reset first, so this patch doesn't change behaviour.
These variables should now be used for one purpose only, making it easier to reason about the code. This will make future refactoring easier.

Reduce scope of variables

---

test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/reference_math.cpp
test_conformance/math_brute_force/unary_two_results_float.cpp

These were identified using Clang's -Wunused warning flag.
@EwanC: those are the remaining dead variables spotted while working on #1228.

Remove dead variables and functions

---

test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/binary_two_results_i_float.cpp
test_conformance/math_brute_force/unary_two_results_i_double.cpp
test_conformance/math_brute_force/unary_two_results_i_float.cpp

Builtin functions producing two results can have their worst error, for each result, on different inputs. Report both inputs.
The format might be a bit awkward, but tries to stay minimal like the output formats in other tests. An alternative could be to remove these variables, but someone could find value in them I suppose.

Report inputs for worst errors

---

test_conformance/math_brute_force/main.cpp

Fix heap-buffer-overflow reported by AddressSanitizer: ensure the appropriate number of elements are allocated for the list of tests.

Avoid manual memory management, fixes #975

---

test_conformance/conversions/basic_test_conversions.cpp

* Avoid optimization by using volatile qualifier
* Fix both uint2float and ulong2double

Fix for test_conversions failure with Clang build on Linux #1057

---

test_conformance/basic/test_async_copy2D.cpp
test_conformance/basic/test_async_copy3D.cpp
test_conformance/basic/test_async_copy_fence.cpp

As the extension is vector size and type independent, we only need to check for the extension once per test and not for every possible combination of inputs, thereby drastically reducing the log output of the test when the extension is not supported.

basic/async: Check for extension only once per test

---

test_common/harness/testHarness.cpp

Most other tests seem to print an error string rather than an error code.

testHarness: Print error string when clFinish fails

---

test_common/harness/kernelHelpers.cpp
test_common/harness/kernelHelpers.h
test_conformance/api/CMakeLists.txt
test_conformance/api/main.cpp
test_conformance/api/procs.h
test_conformance/api/test_kernel_attributes.cpp

This test generates dummy kernels which have different
combinations of the following attributes:
* vec_type_hint
* work_group_size_hint
* reqd_work_group_size
It then gets the attributes by using clGetKernelInfo
and validates that the attributes returned are correct
by matching the attributes which were used to generate
the kernel are present in the returned string from
clGetKernelInfo.
Additionally, this PR adds some functionality to the Harness to make it easier and more intuitive to know if a device supports the Half or Double types. 

Add Test for CL_KERNEL_ATTRIBUTES (#832)

---

test_conformance/math_brute_force/unary_u_double.cpp
test_conformance/math_brute_force/unary_u_float.cpp

Only nan() is tested by unary_u_float.cpp and unary_u_double.cpp. Testing of half_sin, half_tan and half_cos is done in unary_float.cpp and unary_double.cpp.
----
This was spotted because Clang complained `fabsf(s[j])` was a no-op (`-Wabsolute-value`).

Remove unnecessary code from unary_u_*.cpp

---

test_common/harness/imageHelpers.h

As per 6.15.15.7, the first three components have to be set to the luminance value and all components to the intensity value.

Fix image pixel reference calculation for CL_{INTENSITY,LUMINANCE} formats

---

test_conformance/buffers/test_buffer_migrate.cpp
test_conformance/buffers/test_image_migrate.cpp

OpenCL-Docs has 45 occurrences of “enqueuing” but a single one of “enqueueing”.

buffers: Switch from enqueueing to enqueuing

---

test_common/harness/alloc.h
test_common/harness/fpcontrol.h
test_conformance/math_brute_force/function_list.h
test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/reference_math.cpp
test_conformance/math_brute_force/utility.h

The first commit focuses on math_brute_force and the second improves some part of the harness, but only as little as possible for the purpose of upcoming changes.
---
Remove static on functions defined headers, as it can result in duplication in binaries.
Remove unnecessary extern keyword on a function declaration, as it is the default behavior and can be puzzling when reading the code.
Remove the unused declaration of my_ilogb, which is never defined.
Remove unnecessary usage of typedef, as they are only increasing the cognitive load of the code for no purpose.
---
Functions declared in header as static can trigger unused warnings when (indirectly) included in translation units that do not use such functions. Use inline instead, which also avoids duplicating symbols in binaries.

Cleanup usage of static, extern and typedef

---

test_conformance/allocations/allocation_fill.cpp
test_conformance/allocations/allocation_functions.cpp
test_conformance/allocations/main.cpp

* The buffer_non_blocking test was being wrongly skipped if images were not supported by the device.
* Fix a few typos in the test.

Allocations fixes

---

CMakeLists.txt

Remove workaround for #783, this was fixed by #1237.
Remove workaround for overflow, #699 has been merged.
Disable errors from -Wimplicit-const-int-float-conversion, the issue is covered by #1250.

Update warning options

---

test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_i_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp
test_conformance/math_brute_force/binary_two_results_i_double.cpp
test_conformance/math_brute_force/binary_two_results_i_float.cpp
test_conformance/math_brute_force/function_list.cpp
test_conformance/math_brute_force/i_unary_double.cpp
test_conformance/math_brute_force/i_unary_float.cpp
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_binary_float.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/macro_unary_float.cpp
test_conformance/math_brute_force/mad_double.cpp
test_conformance/math_brute_force/mad_float.cpp
test_conformance/math_brute_force/ternary_double.cpp
test_conformance/math_brute_force/ternary_float.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp
test_conformance/math_brute_force/unary_two_results_double.cpp
test_conformance/math_brute_force/unary_two_results_float.cpp
test_conformance/math_brute_force/unary_two_results_i_double.cpp
test_conformance/math_brute_force/unary_two_results_i_float.cpp
test_conformance/math_brute_force/unary_u_double.cpp
test_conformance/math_brute_force/unary_u_float.cpp

A program having a type (such as ThreadInfo) defined differently in multiple translation units exhibits undefined behaviour.
This commit fixes such issues in the math_brute_force component by ensuring most types are local to their translation unit with the help of anonymous namespaces. Later refactoring will be able to extract common definitions to a single place.
This patch also removes unnecessary static and typedef keywords. Otherwise, code is only moved around with no change.
---
I appreciate this is rather large patch but it's very mechanical as well.

Fix ODR violations in math_brute_force

---

test_conformance/math_brute_force/CMakeLists.txt
test_conformance/math_brute_force/binary_double.cpp
test_conformance/math_brute_force/binary_float.cpp
test_conformance/math_brute_force/binary_i_double.cpp
test_conformance/math_brute_force/binary_i_float.cpp
test_conformance/math_brute_force/binary_operator_double.cpp
test_conformance/math_brute_force/binary_operator_float.cpp
test_conformance/math_brute_force/common.h
test_conformance/math_brute_force/macro_binary_double.cpp
test_conformance/math_brute_force/macro_binary_float.cpp
test_conformance/math_brute_force/macro_unary_double.cpp
test_conformance/math_brute_force/macro_unary_float.cpp
test_conformance/math_brute_force/main.cpp
test_conformance/math_brute_force/unary_double.cpp
test_conformance/math_brute_force/unary_float.cpp

Prefer std::vector over malloc and free. This will allow removing goto
statements by leveraging RAII.
Use appropriate type (bool) to store overflow predicates and allocate
std::vector<bool> of appropriate sizes: before this change the
allocation was unnecessary bigger than required.
No longer attempt to catch "out of host memory" issues, given that in
such situation it is generally not possible to cleanly report an error.
Rely on std::bad_alloc exception to report such issues.
Introduce a new header for common code in the math_brute_force
component. It is currently complementary to utility.h and is expected to
hold cleaned up content extracted from future refactoring operations.
List all headers as source in CMake for better compatibility with IDEs.
In order to use non-POD types as fields …

Avoid manual memory management

---

test_common/harness/imageHelpers.cpp
test_common/harness/imageHelpers.h
test_conformance/images/clCopyImage/test_copy_generic.cpp
test_conformance/images/clFillImage/test_fill_generic.cpp

The CL_UNORM_SHORT_555 and CL_UNORM_INT_101010 formats contain padding
bits which need to be ignored in clCopyImage and clFillImage testing.
For clFillImage tests, padding was not ignored for the CL_UNORM_SHORT_555
format, and was ignored for CL_UNORM_INT_101010 by modifying actual and
reference data.  For clCopyImage tests, padding was not ignored, both for
CL_UNORM_SHORT_555 and for CL_UNORM_INT_101010.
Fix this by adding a new compare_scanlines() function, which is used for
both of these formats, and does not modify the actual or reference data.

Ignore padding bits in clCopyImage/clFillImage testing

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

Recently added new extension should be defined in the test_compiler test: 
`cl_khr_pci_bus_info`
`cl_khr_extended_bit_ops`
`cl_khr_spirv_linkonce_odr`
`cl_khr_suggested_local_work_size`
Only `cl_khr_extended_bit_ops` adds new functions to OpenCL C language.

Test compiler - extend list of known extensions

---

test_common/harness/ThreadPool.cpp

ThreadSanitizer detects some data race in ThreadPool. They stem from inappropriate usage of volatile which are replaced with `std::atomic` variables in this patch.
This patch focuses on data races identified while running the math_brute_force component. For example, it doesn't fully remove usage of `ThreadPool_AtomicAdd` from other components of the CTS. Furthermore, thread leaks, most likely because threads are not joined, are not addressed.

Address data race in ThreadPool

---

test_common/harness/errorHelpers.cpp
test_common/harness/errorHelpers.h
test_common/harness/testHarness.cpp

The context and queue were not released when the test is not supported in offline mode or the queue couldn't be created.
Inline `test_missing_support_offline_cmpiler_ret` macro, remove dead parameter of `check_functions_for_offline_compiler` and slightly refactor `callSingleTestFunction` to address leaks.

Fix leaks in callSingleTestFunction

---

test_common/harness/kernelHelpers.cpp
test_common/harness/parseParameters.cpp
test_common/harness/parseParameters.h

The common --disable-spirv-validation option has been added to disable
this functionality.

Run spirv-val for SPIR-V offline compilation

---

test_conformance/images/kernel_read_write/test_common.cpp
test_conformance/images/kernel_read_write/test_common.h
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp

* Fix verification for undefined bit
* Relax current infinitely precision requirement for these formats
and move check in common function.
* Add proper debug output.

Minor fixes for CL_UNORM_SHORT_565, CL_UNORM_SHORT_555

---

test_common/harness/typeWrappers.h
test_conformance/buffers/test_sub_buffers.cpp

Related to #465.
The first commit removes unnecessary functions. The second one rewrites the wrappers to handle copy and move semantics, while preserving the existing API and removing code duplication. It also adds error handling around clRelase* and clRetain*.

Fix copy and move semantics of wrapper classes

---

.github/workflows/presubmit.yml

macOS jobs frequently fail. Since macos-11.0 support is considered experimental,
move to macos-10, using macos-latest so we automatically move to 11 when
stable.
See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

Use macOS 10 in CI

---

test_conformance/api/test_mem_object_info.cpp
test_conformance/api/test_mem_objects.cpp

A recent update to the object wrapper classes (#1268) changed the
behavior of assigning to a wrapper, whereby the wrapped object is now
released upon assignment. A couple of tests were manually calling
`clReleaseMemObject` and then assigning `nullptr` to the wrapper,
resulting in the wrapper calling `clReleaseMemObject` on an object that
had already been destroyed.

Fix double-release of memory objects

---

test_conformance/basic/test_sizeof.cpp

Currently test for image3d_t can be skipped only in embedded profile. It should also be skipped if images aren't supported by device.

Fix check for image support in test_basic sizeof

---

test_conformance/computeinfo/CMakeLists.txt
test_conformance/computeinfo/device_uuid.cpp
test_conformance/computeinfo/main.cpp
test_conformance/computeinfo/pci_bus_info.cpp

Adds a minimal test for `cl_khr_pci_bus_info`.  This test simply queries the PCI bus ID and prints it as part of the `computeinfo` test, similar to the test for `cl_khr_device_uuid`.
NOTE: This test requires up-to-date headers with support for the `cl_khr_pci_bus_info` structure and enum: https://github.com/KhronosGroup/OpenCL-Headers/pull/166

add basic test for cl_khr_pci_bus_info

---

test_conformance/subgroups/main.cpp
test_conformance/subgroups/subgroup_common_templates.h
test_conformance/subgroups/subhelpers.h
test_conformance/subgroups/test_ifp.cpp

cl_float testing uses set_value such that a generated cl_ulong of 1 is
stored as 1.0F in a logical sense. However, cl_half values aren't
intrinsic to C++ and generated cl_ulongs less than 1024 in particular
are interpreted bitwise as subnormals. The test fails on compute devices
lacking subnormal support. Perform the logical conversion to cl_half.
Fix independent forward progress check.

subgroups: Fix setting cl_halfs and progress check.

---

test_conformance/workgroups/CMakeLists.txt
test_conformance/workgroups/main.cpp
test_conformance/workgroups/procs.h
test_conformance/workgroups/test_wg_suggested_local_work_size.cpp

Tests added within test_conformance/workgroups. The tests cover several
shapes (num dimensions) and sizes of global work size, kernels using
local memory (dynamic and static) and present/non-present global work
offset.
Signed-off-by: Kallia Chronaki <kallia.chronaki@arm.com>

Add tests for entrypoint cl_khr_suggested_local_work_size

---

test_conformance/c11_atomics/common.h

I see errors on Windows in cases svm_atomic_*
`ERROR: clRelease*() failed! (CL_INVALID_MEM_OBJECT from C:\NewVPG\Repo\public-github\opensource-qb\OpenCL-CTS\test_common\harness/typeWrappers.h:70)`
This is related to changes in Wrapper Class introduced in https://github.com/KhronosGroup/OpenCL-CTS/pull/1268

Fix double free in c11_atomics tests for SVM allocations

---

test_conformance/workgroups/test_wg_suggested_local_work_size.cpp

Use ASCII '-' instead of unicode '–' as subtraction operator.

Fix kernel source for cl_khr_suggested_local_work_size

---

CMakeLists.txt
test_common/harness/kernelHelpers.cpp
test_common/harness/os_helpers.cpp
test_conformance/basic/test_async_copy2D.cpp
test_conformance/basic/test_async_copy3D.cpp
test_conformance/integer_ops/test_integer_dot_product.cpp

I think this is a reasonable fix for #1306.
* Defines NOMINMAX as part of the CMake file for Windows (MSVC) only.
* Removes all (I think!) of the workarounds in the other test files.

define NOMINMAX in the CMakefile to fix std::min and std::max on MSVC

---

CMakeLists.txt
test_common/CMakeLists.txt

This PR adds the `_CRT_NONSTDC_NO_DEPRECATE` define for all files when building with MSVC, not just for the harness.  This suppresses a warning related to `strdup` that was being generated for nearly all files, since `strdup` was called from the commonly included header `errorHelpers.h`.

suppress MSVC strdup warning

---

test_conformance/atomics/test_atomics.cpp

This avoids extremely large local buffer size and slow run.

Limit workgroup size for atomics tests

---

test_conformance/c11_atomics/test_atomics.cpp

In `atomic_flag` sub-tests that modify local memory, compilers may re-order memory accesses between the local and global address spaces which can lead to incorrect test failures.
This commit ensures that both local and global memory operations are fenced to prevent this re-ordering from occurring.
Fixes #134.

Fix memory model issue in `atomic_flag`.

---

test_conformance/gles/test_buffers.cpp

Remove a few explicit frees in the redirect_buffers test which are
already handled by a wrapper.

gles: Fix double frees.

---

test_conformance/subgroups/subhelpers.h
test_conformance/subgroups/test_subgroup_ballot.cpp
test_conformance/subgroups/test_subgroup_clustered_reduce.cpp
test_conformance/subgroups/test_subgroup_extended_types.cpp
test_conformance/subgroups/test_subgroup_non_uniform_arithmetic.cpp
test_conformance/subgroups/test_subgroup_non_uniform_vote.cpp
test_conformance/subgroups/test_subgroup_shuffle.cpp
test_conformance/subgroups/test_subgroup_shuffle_relative.cpp

Also don't check the presence of extensions for each sub-test.

Report unsupported extended subgroup tests as skipped rather than passed

---

test_conformance/subgroups/test_subgroup_extended_types.cpp

Add testing of sub_group_broadcast for (u)char and (u)short types

---

test_conformance/subgroups/subgroup_common_templates.h
test_conformance/subgroups/test_subgroup_ballot.cpp
test_conformance/subgroups/test_subgroup_non_uniform_vote.cpp

This also adds some missing data type logging to the `subgroup_functions_non_uniform_vote` tests.

Remove excessive logging in subgroup tests

---

test_conformance/subgroups/test_subgroup_ballot.cpp

The tests were logging scalar results as vectors padded with zeroes for no apparent benefit.  Fix this.

Clean up logging in cl_khr_subgroup_ballot tests

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

* Added missing extensions related to cl_khr_semaphore
Signed-off-by: Marco Cattani <marco.cattani@arm.com>

Fix missing cl_khr_semaphore extensions in compiler tests

---

test_conformance/conversions/test_conversions.cpp

The way that program sources were being constructed involved capturing
pointers to strings that were allocated on the stack, and then trying
to use them outside of that scope. This change uses a stringstream
defined in the outer scope to build the program instead.

Fix stack-use-after-scope crash in conversions

---

test_conformance/subgroups/test_subgroup_ballot.cpp

`sub_group_ballot_bit_count()` and `sub_group_ballot_find_msb()` mask their input according to a subgroup size, which is assumed to be the maximum subgroup size, and not the actual subgroup size excluding non-existent work-items in the "remainder" subgroup.
Fix this as per the clarification made to the OpenCL C specification in revision 3.0.9 for issue KhronosGroup/OpenCL-Docs#626 by pull request KhronosGroup/OpenCL-Docs#689.

Use maximum subgroup size in sub_group_ballot tests

---

test_conformance/api/test_api_min_max.cpp

This change doesn't touch printing, as it should be fixed by https://github.com/KhronosGroup/OpenCL-CTS/pull/1212

Fix conversion data loss in test api min max constant args

---

test_conformance/subgroups/subgroup_common_templates.h

Reading once again [documentation ](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_arithmetic_operations) I've noticed that test cases for `sub_group_non_uniform_scan_exclusive_ ` have defect. These changes cover part of definition described as:
`If there is no active work item in the subgroup with a subgroup local ID less than this work item’s subgroup local ID then an identity value I is returned. ... `

Subgroups tests - sub_group_non_uniform_scan_exclusive function fixes

---

test_conformance/api/test_api_min_max.cpp

There is possibility to display negative numbers by `printf` because of overloading to `int` from `cl_ulong`.

Test api min max - fix printing cl_ulong data type

---

test_common/gl/setup_win32.cpp
test_common/gl/setup_x11.cpp

This issue has been noticed by @pierremoreau some time ago
https://github.com/KhronosGroup/OpenCL-CTS/pull/3#issuecomment-486544336
This issue is described here as well: https://stackoverflow.com/questions/65009898/incompatible-function-prototypes-between-glew-h-and-glext-h
Because glew delivers more definitions than glext we should stay with glew.

Fix build, glext should not be used with GLEW

---

test_conformance/compiler/test_compiler_defines_for_extensions.cpp

cl_khr_command_buffer is now public as a provisional khr extension, which implementations may report. This extension name needs to be added to the hardcoded list of extensions in the compiler tests

Add cl_khr_command_buffer to list of extensions

---

test_conformance/subgroups/subgroup_common_templates.h
test_conformance/subgroups/subhelpers.h
test_conformance/subgroups/test_barrier.cpp
test_conformance/subgroups/test_ifp.cpp
test_conformance/subgroups/test_subgroup.cpp
test_conformance/subgroups/test_subgroup_ballot.cpp
test_conformance/subgroups/test_subgroup_clustered_reduce.cpp
test_conformance/subgroups/test_subgroup_non_uniform_vote.cpp

Note that this also corrects the start messages logged for the sub_group_ballot_bit_count/find_msb/find_lsb tests.

Refactor logging of subgroup test start/pass messages

---

test_conformance/subgroups/subgroup_common_templates.h
test_conformance/subgroups/test_subgroup_clustered_reduce.cpp

While arithmetic operations for half type (especially mul operation) we notice overflow appear in results. In this proposal I set 4 values different than 1 and for all other workitems 1. I think this will be safe no matter how big is subgroup.

test_subgroups - Set safe input values for half type and mul, add operations

---

test_conformance/api/test_queries.cpp

Decouple host and device out-of-order test enabling
Fixes #1295

Fix test_api get_command_queue_info

---

test_conformance/subgroups/subhelpers.h
test_conformance/subgroups/test_subgroup_non_uniform_arithmetic.cpp
test_conformance/subgroups/test_subgroup_non_uniform_vote.cpp

This changes compilation of subgroup test kernels so that a separate compilation is no longer performed for each divergence mask value.
The divergence mask is now passed as a kernel argument.
This also fixes all subgroup_functions_non_uniform_arithmetic testing and the sub_group_elect and sub_group_any/all_equal subtests of the subgroup_functions_non_uniform_vote test to use the correct order of vector components for GPUs with a subgroup size greater than 64.
The conversion of divergence mask bitsets to uint4 vectors has been corrected to match code comments in WorkGroupParams::load_masks() in test_conformance/subgroups/subhelpers.h.

Refactor divergence mask handling in subgroup tests

---

test_conformance/submission_details_template.txt

Add "Patches" field and description to match wording introduced in the conformance document:
> A conformance submission is valid only if it is made from a tagged version of the conformance test suite, where the tagged commit date is within 6 months of the submission date. If any patches to the tagged version are necessary to fix test bugs, they must be cherry-picked from subsequent main branch commits and applied without merge conflicts. Any required patches must be documented in the submission as a list of commit SHAs.

Sync submission_details with conformance doc v26

---

README.md
check-format.sh

`master` is now `main`, so update `check-format.sh` accordingly.
Also completely drop the Travis badge as we now use GitHub actions.  There is
no replacement badge as the current action is pre-submission, not
post-submission.

Update format script and drop Travis badge for branch rename
